minimum_prek_version = "0.4.0"

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-json" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },   # Keeps line endings safe for Windows
]

[[repos]]
repo = "local"
hooks = [
  { id = "ruff", name = "ruff", entry = "uv run ruff check --fix", language = "system", types = [
    "python",
  ] },
  { id = "ruff-format", name = "ruff format", entry = "uv run ruff format", language = "system", types = [
    "python",
  ] },
]

[[repos]]
repo = "local"
hooks = [
  { id = "ty", name = "ty", entry = "uv run ty check", language = "system", types = [
    "python",
  ] },
]

[[repos]]
repo = "https://github.com/rohaquinlop/complexipy-pre-commit"
rev = "v7.0.1"
hooks = [
  { id = "complexipy", pass_filenames = false, args = [
    ".",
    "--max-complexity-allowed",
    "18",
  ] },
]
