# generated by datamodel-codegen:
#   filename:  _internal_2
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_math_metafields_ReferenceWithMetaNonNegativeQuantitySchedule_schema,
    cdm_base_staticdata_asset_common_AssetIdentifier_schema,
    cdm_base_staticdata_asset_common_Asset_schema,
    cdm_base_staticdata_asset_common_Taxonomy_schema,
    cdm_base_staticdata_party_LegalEntity_schema,
    cdm_observable_asset_Index_schema,
    cdm_observable_asset_metafields_ReferenceWithMetaPriceSchedule_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class BasketConstituent(BaseModel):
    asset: cdm_base_staticdata_asset_common_Asset_schema.Asset | None = Field(
        None,
        alias="Asset",
        description="The object to be observed is an Asset, ie something that can be owned and transferred in the financial markets.",
    )
    basket: Basket | None = Field(
        None,
        alias="Basket",
        description="The object to be observed is a Basket, ie a collection of Observables with an identifier and optional weightings.",
    )
    index: cdm_observable_asset_Index_schema.Index | None = Field(
        None,
        alias="Index",
        description="The object to be observed is an Index, ie an observable computed on the prices, rates or valuations of a number of assets.",
    )
    quantity: (
        list[cdm_base_math_metafields_ReferenceWithMetaNonNegativeQuantitySchedule_schema.ReferenceWithMetaNonNegativeQuantitySchedule]
        | None
    ) = Field(
        None,
        description="Specifies a quantity schedule to be associated to an individual underlier that is a basket constituent. The multiple cardinality is aligned to the one of the PriceQuantity->quantity that this quantity is referencing.",
        min_length=0,
    )
    initial_valuation_price: (
        list[cdm_observable_asset_metafields_ReferenceWithMetaPriceSchedule_schema.ReferenceWithMetaPriceSchedule] | None
    ) = Field(
        None,
        alias="initialValuationPrice",
        description="Specifies an initial price schedule to be associated to an individual underlier that is a basket constituent. The multiple cardinality is aligned to the one of the PriceQuantity->price that this price is referencing.",
        min_length=0,
    )
    interim_valuation_price: (
        list[cdm_observable_asset_metafields_ReferenceWithMetaPriceSchedule_schema.ReferenceWithMetaPriceSchedule] | None
    ) = Field(
        None,
        alias="interimValuationPrice",
        description="Specifies an interim price schedule to be associated to an individual underlier that is a basket constituent. The multiple cardinality is aligned to the one of the PriceQuantity->price that this price is referencing.",
        min_length=0,
    )
    final_valuation_price: (
        list[cdm_observable_asset_metafields_ReferenceWithMetaPriceSchedule_schema.ReferenceWithMetaPriceSchedule] | None
    ) = Field(
        None,
        alias="finalValuationPrice",
        description="Specifies a final price schedule to be associated to an individual underlier that is a basket constituent. The multiple cardinality is aligned to the one of the PriceQuantity->price that this price is referencing.",
        min_length=0,
    )


class Basket(BaseModel):
    identifier: list[cdm_base_staticdata_asset_common_AssetIdentifier_schema.AssetIdentifier] | None = Field(
        None, description="Asset Identifiers are used to uniquely identify an Asset, using a specified Asset Identifier Type.", min_length=1
    )
    taxonomy: list[cdm_base_staticdata_asset_common_Taxonomy_schema.Taxonomy] | None = Field(
        None,
        description="Defines the taxonomy of an object by combining a taxonomy source (i.e. the rules to classify the object) and a value (i.e. the output of those rules on the object.",
        min_length=0,
    )
    is_exchange_listed: bool | None = Field(
        None, alias="isExchangeListed", description="Defines whether the Asset is listed on a public exchange."
    )
    exchange: cdm_base_staticdata_party_LegalEntity_schema.LegalEntity | None = Field(
        None, description="If the Asset is listed, defines the public exchange of the listing."
    )
    related_exchange: list[cdm_base_staticdata_party_LegalEntity_schema.LegalEntity] | None = Field(
        None, alias="relatedExchange", description="Provides the related Exchanges, if applicable.", min_length=0
    )
    basket_constituent: list[FieldWithMetaBasketConstituent] | None = Field(
        None, alias="basketConstituent", description="Identifies the constituents of the basket", min_length=1
    )


class FieldWithMetaBasketConstituent(BaseModel):
    value: BasketConstituent | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None


Basket.model_rebuild()
