# generated by datamodel-codegen:
#   filename:  cdm-base-math-AveragingCalculationMethod.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_math_AveragingCalculationMethodEnum_schema


class AveragingCalculationMethod(BaseModel):
    is_weighted: bool = Field(
        ..., alias="isWeighted", description="Identifies whether the average values will be weighted or unweighted."
    )
    calculation_method: cdm_base_math_AveragingCalculationMethodEnum_schema.AveragingCalculationMethodEnum = Field(
        ...,
        alias="calculationMethod",
        description="Identifies which of the Pythagorean means is being used to compute an average value.",
    )
