# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-DebtInterestEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class DebtInterestEnum(StrEnum):
    FIXED = "Fixed"
    FLOATING = "Floating"
    INDEX_LINKED = "IndexLinked"
    INFLATION_LINKED = "InflationLinked"
    INTEREST_ONLY = "InterestOnly"
    INVERSE_FLOATING = "InverseFloating"
    OTHER_STRUCTURED = "OtherStructured"
    ZERO_COUPON = "ZeroCoupon"
