# generated by datamodel-codegen:
#   filename:  cdm-event-common-ValuationSourceEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ValuationSourceEnum(StrEnum):
    CENTRAL_COUNTERPARTY = "CentralCounterparty"
