# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-NaturalPersonRole.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_metafields_FieldWithMetaNaturalPersonRoleEnum_schema,
    cdm_base_staticdata_party_metafields_ReferenceWithMetaNaturalPerson_schema,
)


class NaturalPersonRole(BaseModel):
    person_reference: cdm_base_staticdata_party_metafields_ReferenceWithMetaNaturalPerson_schema.ReferenceWithMetaNaturalPerson = Field(
        ...,
        alias="personReference",
        description="A reference to the natural person to whom the role refers to.",
    )
    role: (
        list[
            cdm_base_staticdata_party_metafields_FieldWithMetaNaturalPersonRoleEnum_schema.FieldWithMetaNaturalPersonRoleEnum
        ]
        | None
    ) = Field(
        None,
        description="FpML specifies a person role that is distinct from the party role.",
        min_length=0,
    )
