# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-identifier-TradeIdentifierTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class TradeIdentifierTypeEnum(StrEnum):
    unique_swap_identifier = "UniqueSwapIdentifier"
    unique_transaction_identifier = "UniqueTransactionIdentifier"
