# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-credit-ObligationCategoryEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ObligationCategoryEnum(StrEnum):
    BOND = "Bond"
    BOND_OR_LOAN = "BondOrLoan"
    BORROWED_MONEY = "BorrowedMoney"
    LOAN = "Loan"
    PAYMENT = "Payment"
    REFERENCE_OBLIGATIONS_ONLY = "ReferenceObligationsOnly"
