# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValuationDateFrequencyEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ValuationDateFrequencyEnum(StrEnum):
    AS_AGREED = "AsAgreed"
    AS_SELECTED = "AsSelected"
    DAILY = "Daily"
    FORTNIGHTLY = "Fortnightly"
    MONTHLY = "Monthly"
    WEEKLY = "Weekly"
