# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValuationTimeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ValuationTimeEnum(StrEnum):
    AS_SELECTED = "AsSelected"
    CLOSE_OF_BUSINESS = "CloseOfBusiness"
    SPECIFIC_TIME = "SpecificTime"
