# generated by datamodel-codegen:
#   filename:  cdm-regulation-Sngl.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_regulation_Indx_schema


class Sngl(BaseModel):
    isin: str
    indx: cdm_regulation_Indx_schema.Indx
