# generated by datamodel-codegen:
#   filename:  cdm-observable-event-IndexEventConsequenceEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class IndexEventConsequenceEnum(StrEnum):
    CALCULATION_AGENT_ADJUSTMENT = "CalculationAgentAdjustment"
    CANCELLATION_AND_PAYMENT = "CancellationAndPayment"
    NEGOTIATED_CLOSE_OUT = "NegotiatedCloseOut"
    RELATED_EXCHANGE = "RelatedExchange"
