# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-Regime.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_ApplicableRegime_schema


class Regime(BaseModel):
    applicable_regime: list[cdm_legaldocumentation_csa_ApplicableRegime_schema.ApplicableRegime] | None = Field(
        None,
        alias="applicableRegime",
        description="A class to specify the regime(s) that parties to a legal agreement, such as the ISDA 2016 and 2018 CSA for Initial Margin, might agree to apply to one or both parties when acting as collateral taker, and specific terms associated with that application.",
        min_length=1,
    )
    fallback_to_mandatory_method_days: float | None = Field(
        None,
        alias="fallbackToMandatoryMethodDays",
        description="The specification of the number of days after effective delivery of notice that Mandatory method fallback applies. Specification is only required when one or more Regimes have Fall Back to Mandatory Method elected as a SIMM exception.",
    )
