# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-master-MasterAgreementClauseVariant.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_base_staticdata_party_PartyRoleEnum_schema,
    cdm_legaldocumentation_master_MasterAgreementVariableSet_schema,
    cdm_legaldocumentation_master_MasterAgreementVariantIdentifierEnum_schema,
)


class MasterAgreementClauseVariant(BaseModel):
    identifier: cdm_legaldocumentation_master_MasterAgreementVariantIdentifierEnum_schema.MasterAgreementVariantIdentifierEnum = Field(
        ..., description="Unique identifier for this variant."
    )
    name: str | None = Field(None, description="Optional textual description of the variant.")
    counterparty: (
        list[cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum] | None
    ) = Field(
        None,
        description="Optional counterparty role. This can be used where a clause needs to assign a different variant to the different parties on the agreement based upon their role i.e. Party A or Party B.",
        max_length=2,
        min_length=0,
    )
    other_party: list[cdm_base_staticdata_party_PartyRoleEnum_schema.PartyRoleEnum] | None = Field(
        None,
        alias="otherParty",
        description="Optional party. This can be used where a clause needs to assign different variants to different parties who may or may not be on the agreement.",
        min_length=0,
    )
    variable_set: (
        list[
            cdm_legaldocumentation_master_MasterAgreementVariableSet_schema.MasterAgreementVariableSet
        ]
        | None
    ) = Field(
        None,
        alias="variableSet",
        description="For some variants of some clauses additional details are required to work out what has been elected. This array can be used to define the name and value of these variables. Please refer to the agreement documentation for more details of the variables that are available for any clause.",
        min_length=0,
    )
