# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-HoldingAndUsingPostedCollateralElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_legaldocumentation_csa_EligibilityToHoldCollateral_schema,
)


class HoldingAndUsingPostedCollateralElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    eligibility_to_hold_collateral: cdm_legaldocumentation_csa_EligibilityToHoldCollateral_schema.EligibilityToHoldCollateral = Field(
        ...,
        alias="eligibilityToHoldCollateral",
        description="The specification of the conditions under which a party and its custodian(s) are entitled to hold posted collateral.",
    )
    use_of_posted_collateral: bool = Field(
        ...,
        alias="useOfPostedCollateral",
        description="Specifies whether the party to the agreement has the right to rehypothecate the collateral held (True).",
    )
