# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-SubstitutionProvisions.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_Period_schema


class SubstitutionProvisions(BaseModel):
    number_of_substitutions_allowed: int | None = Field(
        None, alias="numberOfSubstitutionsAllowed", description="Specifies if 1 or more substitutions are allowed."
    )
    notice_deadline_period: cdm_base_datetime_Period_schema.Period | None = Field(
        None, alias="noticeDeadlinePeriod", description="Defines the min period for notify of a substitution."
    )
    notice_deadline_date_time: str | None = Field(
        None, alias="noticeDeadlineDateTime", description="A specific date and time for the notice deadline"
    )
