# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-BusinessCenterTime.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_metafields_FieldWithMetaBusinessCenterEnum_schema


class BusinessCenterTime(BaseModel):
    hour_minute_time: str = Field(
        ...,
        alias="hourMinuteTime",
        description="A time specified in hh:mm:ss format where the second component must be '00', e.g. 11am would be represented as 11:00:00.",
    )
    business_center: cdm_base_datetime_metafields_FieldWithMetaBusinessCenterEnum_schema.FieldWithMetaBusinessCenterEnum = Field(
        ...,
        alias="businessCenter",
        description="A code identifying a business day calendar location. A business day calendar location is drawn from the list identified by the business day calendar location enumeration.",
    )
