# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValuationAgentPartyEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ValuationAgentPartyEnum(StrEnum):
    PARTY_1 = "Party 1"
    PARTY_2 = "Party 2"
    PARTY_MAKING_THE_DEMAND = "Party Making the Demand"
