# generated by datamodel-codegen:
#   filename:  cdm-margin-schedule-StandardizedScheduleProductClassEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class StandardizedScheduleProductClassEnum(StrEnum):
    basis_swap = "BasisSwap"
    contract_for_difference = "ContractForDifference"
    correlation_swap = "CorrelationSwap"
    credit_nth_to_default = "CreditNthToDefault"
    credit_total_return_swap_on_a_bond = "CreditTotalReturnSwapOnABond"
    cross_currency_swap = "CrossCurrencySwap"
    deliverable_forward = "DeliverableForward"
    deliverable_option = "DeliverableOption"
    deliverable_option_f = "DeliverableOptionF"
    deliverable_swap = "DeliverableSwap"
    dividend_swap = "DividendSwap"
    fixed_float_swap = "FixedFloatSwap"
    forward = "Forward"
    forward_rate_agreement = "ForwardRateAgreement"
    ir_exotic_swap_with_an_exotic_coupon_against_a_floating_leg = "IRExoticSwapWithAnExoticCouponAgainstAFloatingLeg"
    index_cds = "IndexCDS"
    index_tranche = "IndexTranche"
    non_deliverable_cross_currency_swap = "NonDeliverableCrossCurrencySwap"
    non_deliverable_forward = "NonDeliverableForward"
    non_deliverable_option = "NonDeliverableOption"
    option = "Option"
    single_name_credit_default_swap = "SingleNameCreditDefaultSwap"
    swap = "Swap"
    swap_with_callable_bermudan_right_to_enter_exit_swaps = "SwapWithCallableBermudanRightToEnterExitSwaps"
    swaps_and_portfolio_swaps = "SwapsAndPortfolioSwaps"
    swaption = "Swaption"
    swaption_straddle = "SwaptionStraddle"
    variance_swap = "VarianceSwap"
    volatility_swap = "VolatilitySwap"
