# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-FinalReturns.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class FinalReturns(BaseModel):
    applicable: bool | None = Field(
        None, description="Defines if the clause is applicable to this agreement or any other exceptions."
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
