# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-LegalAgreementPublisherEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class LegalAgreementPublisherEnum(StrEnum):
    afb = "AFB"
    bnym = "BNYM"
    emta = "EMTA"
    icma = "ICMA"
    isda = "ISDA"
    isda_clearstream = "ISDAClearstream"
    isda_euroclear = "ISDAEuroclear"
    isla = "ISLA"
    jp_morgan = "JPMorgan"
    the_fx_committee = "TheFXCommittee"
