# generated by datamodel-codegen:
#   filename:  cdm-product-asset-DividendDateReferenceEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class DividendDateReferenceEnum(StrEnum):
    AD_HOC_DATE = "AdHocDate"
    CASH_SETTLE_PAYMENT_DATE_EX_DIV = "CashSettlePaymentDateExDiv"
    CASH_SETTLE_PAYMENT_DATE_ISSUER_PAYMENT = "CashSettlePaymentDateIssuerPayment"
    CASH_SETTLEMENT_PAYMENT_DATE = "CashSettlementPaymentDate"
    CUMULATIVE_EQUITY_EX_DIV = "CumulativeEquityExDiv"
    CUMULATIVE_EQUITY_EX_DIV_BEFORE_RESET = "CumulativeEquityExDivBeforeReset"
    CUMULATIVE_EQUITY_PAID = "CumulativeEquityPaid"
    CUMULATIVE_EQUITY_PAID_BEFORE_RESET = "CumulativeEquityPaidBeforeReset"
    CUMULATIVE_EQUITY_PAID_INCL_RESET = "CumulativeEquityPaidInclReset"
    CUMULATIVE_INTEREST_EX_DIV = "CumulativeInterestExDiv"
    CUMULATIVE_INTEREST_PAID = "CumulativeInterestPaid"
    CUMULATIVE_INTEREST_PAID_BEFORE_RESET = "CumulativeInterestPaidBeforeReset"
    CUMULATIVE_INTEREST_PAID_INCL_RESET = "CumulativeInterestPaidInclReset"
    DIVIDEND_PAYMENT_DATE = "DividendPaymentDate"
    DIVIDEND_VALUATION_DATE = "DividendValuationDate"
    EQUITY_PAYMENT_DATE = "EquityPaymentDate"
    EX_DATE = "ExDate"
    FLOATING_AMOUNT_PAYMENT_DATE = "FloatingAmountPaymentDate"
    FOLLOWING_PAYMENT_DATE = "FollowingPaymentDate"
    RECORD_DATE = "RecordDate"
    SHARE_PAYMENT = "SharePayment"
    TERMINATION_DATE = "TerminationDate"
    TRADE_DATE = "TradeDate"
    UNWIND_EX_DIV = "UnwindExDiv"
    UNWIND_OR_EQUITY_EX_DIV = "UnwindOrEquityExDiv"
    UNWIND_OR_EQUITY_PAID = "UnwindOrEquityPaid"
    UNWIND_OR_INTEREST_EX_DIV = "UnwindOrInterestExDiv"
    UNWIND_OR_INTEREST_PAID = "UnwindOrInterestPaid"
    UNWIND_PAID = "UnwindPaid"
