# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CreditSupportAmountEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CreditSupportAmountEnum(StrEnum):
    NON_STANDARD___IA_FLOOR__LESS_GIVER_IA_ = "Non-Standard - IA Floor (Less GiverIA)"
    NON_STANDARD___IA_FLOOR__LESS_GIVER_IA_AND_TAKER_IA_ = (
        "Non-Standard - IA Floor (Less GiverIA and TakerIA)"
    )
    NON_STANDARD___OTHER = "Non-Standard - Other"
    NON_STANDARD___RATINGS = "Non-Standard - Ratings"
    STANDARD = "Standard"
