# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-EquityTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class EquityTypeEnum(StrEnum):
    NON_CONVERTIBLE_PREFERENCE = "NonConvertiblePreference"
    ORDINARY = "Ordinary"
