# generated by datamodel-codegen:
#   filename:  cdm-event-workflow-LimitApplicable.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_event_workflow_CreditLimitUtilisation_schema,
    cdm_event_workflow_Velocity_schema,
    cdm_event_workflow_metafields_FieldWithMetaCreditLimitTypeEnum_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class LimitApplicable(BaseModel):
    limit_type: (
        cdm_event_workflow_metafields_FieldWithMetaCreditLimitTypeEnum_schema.FieldWithMetaCreditLimitTypeEnum | None
    ) = Field(
        None,
        alias="limitType",
        description="Standard code to indicate which type of credit line is being referred to - i.e. IM, DV01, PV01, CS01, Notional, Clip Size, Notional, maximumOrderQuantity.",
    )
    clip_size: int | None = Field(
        None,
        alias="clipSize",
        description="This element is required in FpML, optional in CDM for the purpose of accommodating the CME data representation while making reference to the FpML one.",
    )
    amount_utilized: float | None = Field(
        None,
        alias="amountUtilized",
        description="The limit utilised by all the cleared trades for the limit level and limit type. While the attribute is of type integer in FpML and the CME schema, it has been specified to be of type number in the CDM to take into consideration java size limits as well as for consistency purposes with the way most monetary amounts are expressed.",
    )
    utilization: cdm_event_workflow_CreditLimitUtilisation_schema.CreditLimitUtilisation | None = None
    amount_remaining: float | None = Field(
        None,
        alias="amountRemaining",
        description="The limit remaining for the limit level and limit type. This does not take into account any pending trades. While the attribute is of type integer in FpML and the CME schema, it has been specified to be of type number in the CDM to take into consideration java size limits as well as for consistency purposes with the way most monetary amounts are expressed.",
    )
    currency: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None = Field(
        None,
        description="The currency in which the applicable limit is denominated. The list of valid currencies is not presently positioned as an enumeration as part of the CDM because that scope is limited to the values specified by ISDA and FpML. As a result, implementers have to make reference to the relevant standard, such as the ISO 4217 standard for currency codes.",
    )
    velocity: cdm_event_workflow_Velocity_schema.Velocity | None = None
