# generated by datamodel-codegen:
#   filename:  cdm-product-template-FxFeature.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_product_template_Composite_schema,
    cdm_product_template_Quanto_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class FxFeature(BaseModel):
    reference_currency: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString = Field(
        ..., alias="referenceCurrency", description="Specifies the reference currency of the trade."
    )
    composite: cdm_product_template_Composite_schema.Composite | None = Field(
        None,
        description="If 'Composite' is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero.",
    )
    quanto: cdm_product_template_Quanto_schema.Quanto | None = Field(
        None,
        description="If 'Quanto' is specified as the Settlement Type in the relevant Transaction Supplement, an amount, as determined by the Calculation Agent in accordance with the Section 8.2 of the Equity Definitions.",
    )
    cross_currency: cdm_product_template_Composite_schema.Composite | None = Field(
        None,
        alias="crossCurrency",
        description="If 'Cross-Currency' is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier x one unit of the Reference Currency converted into an amount in the Settlement Currency using the rate of exchange of the Settlement Currency as quoted on the Reference Price Source on the Valuation Date, provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero.",
    )
