# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-ConcentrationLimitCriteria.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from ._internal_4 import CollateralCriteria
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_product_collateral_AverageTradingVolume_schema,
    cdm_product_collateral_CollateralMarginTypeEnum_schema,
    cdm_product_collateral_ConcentrationLimitTypeEnum_schema,
    cdm_product_collateral_RatingPriorityResolutionEnum_schema,
)


class ConcentrationLimitCriteria(BaseModel):
    collateral_criteria: CollateralCriteria | None = Field(
        None,
        alias="collateralCriteria",
        description="The specific criteria that applies. It can be created using AND, OR and NOT logic, and both asset and issuer characteristics.",
    )
    applies_to: (
        list[cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum] | None
    ) = Field(
        None,
        alias="appliesTo",
        description="Specifies which of the two counterparties the criteria applies to (either one or both counterparties). This attribute is optional, in case the applicable party is already specified elsewhere within a party election.",
        max_length=2,
        min_length=0,
    )
    restrict_to: (
        cdm_product_collateral_CollateralMarginTypeEnum_schema.CollateralMarginTypeEnum | None
    ) = Field(
        None,
        alias="restrictTo",
        description="Restrict the criteria to only apply to a specific type of margin, ie IM or VM.",
    )
    rating_priority_resolution: (
        cdm_product_collateral_RatingPriorityResolutionEnum_schema.RatingPriorityResolutionEnum
        | None
    ) = Field(
        None,
        alias="ratingPriorityResolution",
        description="Denotes which Criteria has priority if more than one agency rating applies.",
    )
    concentration_limit_type: (
        cdm_product_collateral_ConcentrationLimitTypeEnum_schema.ConcentrationLimitTypeEnum | None
    ) = Field(
        None,
        alias="concentrationLimitType",
        description="Specifies the type of concentration limit to be applied.",
    )
    average_trading_volume: (
        cdm_product_collateral_AverageTradingVolume_schema.AverageTradingVolume | None
    ) = Field(
        None,
        alias="averageTradingVolume",
        description="Specifies an average trading volume on an exchange in relation to Equity products.",
    )
