# generated by datamodel-codegen:
#   filename:  cdm-regulation-Buyr.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_regulation_AcctOwnr_schema


class Buyr(BaseModel):
    acct_ownr: cdm_regulation_AcctOwnr_schema.AcctOwnr = Field(..., alias="acctOwnr")
