# generated by datamodel-codegen:
#   filename:  cdm-product-template-AutomaticExercise.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class AutomaticExercise(BaseModel):
    threshold_rate: float | None = Field(
        None,
        alias="thresholdRate",
        description="A threshold rate. The threshold of 0.10% would be represented as 0.001",
    )
    is_applicable: bool | None = Field(
        None, alias="isApplicable", description="Boolean that indicates if it has an automaticExercise"
    )
