# generated by datamodel-codegen:
#   filename:  cdm-base-math-Schedule.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_math_DatedValue_schema


class Schedule(BaseModel):
    value: float = Field(
        ..., description="The initial rate or amount, as the case may be. An initial rate of 5% would be represented as 0.05."
    )
    dated_value: list[cdm_base_math_DatedValue_schema.DatedValue] | None = Field(
        None,
        alias="datedValue",
        description="The schedule of step date and value pairs. On each step date the associated step value becomes effective. A list of steps may be ordered in the document by ascending step date. An FpML document containing an unordered list of steps is still regarded as a conformant document.",
        min_length=0,
    )
