# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-AlternativeToInterestAmountEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AlternativeToInterestAmountEnum(StrEnum):
    actual_amount_received = "ActualAmountReceived"
    other = "Other"
    standard = "Standard"
    transfer_if_delivery_amount_below_mta = "TransferIfDeliveryAmountBelowMTA"
