# generated by datamodel-codegen:
#   filename:  cdm-product-template-FixedPricePayout.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_PayerReceiver_schema,
    cdm_product_common_schedule_PaymentDates_schema,
    cdm_product_common_settlement_FixedPrice_schema,
    cdm_product_common_settlement_PrincipalPayments_schema,
    cdm_product_common_settlement_ResolvablePriceQuantity_schema,
    cdm_product_common_settlement_SettlementTerms_schema,
    cdm_product_template_CalculationSchedule_schema,
)


class FixedPricePayout(BaseModel):
    payer_receiver: cdm_base_staticdata_party_PayerReceiver_schema.PayerReceiver | None = Field(
        None,
        alias="payerReceiver",
        description="Canonical representation of the payer and receiver parties applicable to each payout leg.",
    )
    price_quantity: (
        cdm_product_common_settlement_ResolvablePriceQuantity_schema.ResolvablePriceQuantity | None
    ) = Field(
        None,
        alias="priceQuantity",
        description="Each payout leg must implement the quantity concept as a 'resolvable' type, which allows for different payout legs to be linked to each other (e.g. in the case of cross-curreny products).",
    )
    principal_payment: (
        cdm_product_common_settlement_PrincipalPayments_schema.PrincipalPayments | None
    ) = Field(
        None,
        alias="principalPayment",
        description="The specification of the principal exchange. Optional as only applicable in the case of cross-currency or zero-coupon swaps with a final payment.",
    )
    settlement_terms: (
        cdm_product_common_settlement_SettlementTerms_schema.SettlementTerms | None
    ) = Field(
        None,
        alias="settlementTerms",
        description="Each payout leg must specifies its settlement terms, including the delivery type (i.e. cash vs physical, and their respective terms), the transfer type (DvP etc.) and settlement date, if any.",
    )
    payment_dates: cdm_product_common_schedule_PaymentDates_schema.PaymentDates = Field(
        ...,
        alias="paymentDates",
        description="Specifies the parameters to generate the payment date schedule, either through a parametric representation or by reference to specified dates.",
    )
    fixed_price: cdm_product_common_settlement_FixedPrice_schema.FixedPrice = Field(
        ...,
        alias="fixedPrice",
        description="Specifies the fixed price on which fixed forward payments are based.",
    )
    schedule: cdm_product_template_CalculationSchedule_schema.CalculationSchedule | None = Field(
        None,
        description="Allows the full representation of a payout by defining a set of schedule periods. It supports standard schedule customization by expressing all the dates, quantities, and pricing data in a non-parametric way.",
    )
