# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CollateralAccessBreach.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class CollateralAccessBreach(BaseModel):
    is_applicable: bool = Field(
        ...,
        alias="isApplicable",
        description="Collateral Access Breach terms are applicable when True and not applicable when False.",
    )
    cab_end_date_election: bool | None = Field(
        None,
        alias="cabEndDateElection",
        description="Determination of whether the Collateral Access Breach end date is a number of days (True) or specified (False).",
    )
    cab_end_date: float | None = Field(
        None,
        alias="cabEndDate",
        description="The business days following the related Collateral Access Breach when the additional terms end.",
    )
    cab_end_date_terms: str | None = Field(
        None,
        alias="cabEndDateTerms",
        description="Specific terms for when Collateral Access Breach terms end.",
    )
