# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CollateralValueMethod.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_ValueCashEnum_schema, cdm_legaldocumentation_csa_ValueSecuritiesEnum_schema


class CollateralValueMethod(BaseModel):
    cash_collateral: cdm_legaldocumentation_csa_ValueCashEnum_schema.ValueCashEnum | None = Field(
        None, alias="cashCollateral", description="Details of how cash collateral is valued."
    )
    securities_collateral: cdm_legaldocumentation_csa_ValueSecuritiesEnum_schema.ValueSecuritiesEnum | None = Field(
        None, alias="securitiesCollateral", description="Details of how securities collateral is valued."
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
