# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-EntityIdentifierTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class EntityIdentifierTypeEnum(StrEnum):
    BIC = "BIC"
    COUNTRY_CODE = "CountryCode"
    LEI = "LEI"
    MIC = "MIC"
    OTHER = "Other"
    REDID = "REDID"
