# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValuationDateFrequencyEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ValuationDateFrequencyEnum(StrEnum):
    as_agreed = "AsAgreed"
    as_selected = "AsSelected"
    daily = "Daily"
    fortnightly = "Fortnightly"
    monthly = "Monthly"
    weekly = "Weekly"
