# generated by datamodel-codegen:
#   filename:  cdm-product-asset-LoadTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class LoadTypeEnum(StrEnum):
    BASE_LOAD = "BaseLoad"
    BLOCK_HOURS = "BlockHours"
    GAS_DAY = "GasDay"
    OFF_PEAK = "OffPeak"
    OTHER = "Other"
    PEAK_LOAD = "PeakLoad"
    SHAPED = "Shaped"
