# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-SingleValuationDate.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class SingleValuationDate(BaseModel):
    business_days: int | None = Field(
        None,
        alias="businessDays",
        description="A number of business days. Its precise meaning is dependant on the context in which this element is used. ISDA 2003 Term: Business Day.",
    )
