# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-EquityAdditionalTerms.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_transaction_ExtraordinaryEvents_schema,
    cdm_legaldocumentation_transaction_UnderlierSubstitutionProvision_schema,
    cdm_legaldocumentation_transaction_additionalterms_DeterminationRolesAndTerms_schema,
)


class EquityAdditionalTerms(BaseModel):
    extraordinary_events: (
        cdm_legaldocumentation_transaction_ExtraordinaryEvents_schema.ExtraordinaryEvents | None
    ) = Field(None, alias="extraordinaryEvents")
    determination_terms: (
        list[
            cdm_legaldocumentation_transaction_additionalterms_DeterminationRolesAndTerms_schema.DeterminationRolesAndTerms
        ]
        | None
    ) = Field(None, alias="determinationTerms", min_length=1)
    substitution_provision: (
        cdm_legaldocumentation_transaction_UnderlierSubstitutionProvision_schema.UnderlierSubstitutionProvision
        | None
    ) = Field(None, alias="substitutionProvision")
