# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-TransferSettlementEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class TransferSettlementEnum(StrEnum):
    delivery_versus_delivery = "DeliveryVersusDelivery"
    delivery_versus_payment = "DeliveryVersusPayment"
    not_central_settlement = "NotCentralSettlement"
    payment_versus_payment = "PaymentVersusPayment"
