# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CashCTSTimeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CashCTSTimeEnum(StrEnum):
    FIRST_LOCAL_BUSINESS_DAY = "First Local Business Day"
    NEXT = "Next"
    OTHER = "Other"
    SAME = "Same"
    SECOND_LOCAL_BUSINESS_DAY = "Second Local Business Day"
