# generated by datamodel-codegen:
#   filename:  cdm-event-common-TransferExpression.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_ScheduledTransfer_schema, cdm_observable_asset_FeeTypeEnum_schema


class TransferExpression(BaseModel):
    price_transfer: cdm_observable_asset_FeeTypeEnum_schema.FeeTypeEnum | None = Field(
        None,
        alias="priceTransfer",
        description="Specifies a transfer amount exchanged as a price or fee for entering into a Business Event, e.g. Premium, Termination fee, Novation fee.",
    )
    scheduled_transfer: cdm_event_common_ScheduledTransfer_schema.ScheduledTransfer | None = Field(
        None,
        alias="scheduledTransfer",
        description="Specifies a transfer created from a scheduled or contingent event on a contract, e.g. Exercise, Performance, Credit Event",
    )
