# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-CreditSupportAgreementTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CreditSupportAgreementTypeEnum(StrEnum):
    collateral_transfer_agreement = "CollateralTransferAgreement"
    credit_support_annex = "CreditSupportAnnex"
    credit_support_deed = "CreditSupportDeed"
