# generated by datamodel-codegen:
#   filename:  cdm-base-math-RoundingDirectionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class RoundingDirectionEnum(StrEnum):
    DOWN = "Down"
    NEAREST = "Nearest"
    UP = "Up"
