# generated by datamodel-codegen:
#   filename:  cdm-observable-event-IndexEventConsequenceEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class IndexEventConsequenceEnum(StrEnum):
    calculation_agent_adjustment = "CalculationAgentAdjustment"
    cancellation_and_payment = "CancellationAndPayment"
    negotiated_close_out = "NegotiatedCloseOut"
    related_exchange = "RelatedExchange"
