# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-CashSettlementMethodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CashSettlementMethodEnum(StrEnum):
    CASH_PRICE_ALTERNATE_METHOD = "CashPriceAlternateMethod"
    CASH_PRICE_METHOD = "CashPriceMethod"
    COLLATERALIZED_CASH_PRICE_METHOD = "CollateralizedCashPriceMethod"
    CROSS_CURRENCY_METHOD = "CrossCurrencyMethod"
    MID_MARKET_CALCULATION_AGENT_DETERMINATION = "MidMarketCalculationAgentDetermination"
    MID_MARKET_INDICATIVE_QUOTATIONS = "MidMarketIndicativeQuotations"
    MID_MARKET_INDICATIVE_QUOTATIONS_ALTERNATE = "MidMarketIndicativeQuotationsAlternate"
    PAR_YIELD_CURVE_ADJUSTED_METHOD = "ParYieldCurveAdjustedMethod"
    PAR_YIELD_CURVE_UNADJUSTED_METHOD = "ParYieldCurveUnadjustedMethod"
    REPLACEMENT_VALUE_CALCULATION_AGENT_DETERMINATION = (
        "ReplacementValueCalculationAgentDetermination"
    )
    REPLACEMENT_VALUE_FIRM_QUOTATIONS = "ReplacementValueFirmQuotations"
    ZERO_COUPON_YIELD_ADJUSTED_METHOD = "ZeroCouponYieldAdjustedMethod"
