# generated by datamodel-codegen:
#   filename:  cdm-product-asset-SpreadSchedule.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_observable_asset_metafields_ReferenceWithMetaPriceSchedule_schema,
    cdm_product_asset_metafields_FieldWithMetaSpreadScheduleTypeEnum_schema,
)


class SpreadSchedule(BaseModel):
    price: (
        cdm_observable_asset_metafields_ReferenceWithMetaPriceSchedule_schema.ReferenceWithMetaPriceSchedule | None
    ) = Field(None, description="The initial rate. An initial rate of 5% would be represented as 0.05.")
    spread_schedule_type: (
        cdm_product_asset_metafields_FieldWithMetaSpreadScheduleTypeEnum_schema.FieldWithMetaSpreadScheduleTypeEnum
        | None
    ) = Field(
        None,
        alias="spreadScheduleType",
        description="An element which purpose is to identify a long or short spread value.",
    )
