# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-PaymentDateSchedule.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableOrRelativeDate_schema,
    cdm_base_datetime_AdjustableRelativeOrPeriodicDates_schema,
)


class PaymentDateSchedule(BaseModel):
    interim_payment_dates: (
        list[cdm_base_datetime_AdjustableRelativeOrPeriodicDates_schema.AdjustableRelativeOrPeriodicDates] | None
    ) = Field(None, alias="interimPaymentDates", min_length=0)
    final_payment_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None,
        alias="finalPaymentDate",
        description="The last payment when specified as an adjustable or relative date, as in the FpML total return construct.",
    )
