# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-LegalEntity.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_EntityIdentifier_schema, com_rosetta_model_metafields_FieldWithMetaString_schema


class LegalEntity(BaseModel):
    entity_id: list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None = Field(
        None,
        alias="entityId",
        description="A legal entity identifier (e.g. RED entity code). This type is deprecated. It is recommended to use entityIdentifier.",
        min_length=0,
    )
    name: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString = Field(..., description="The legal entity name.")
    entity_identifier: list[cdm_base_staticdata_party_EntityIdentifier_schema.EntityIdentifier] | None = Field(
        None, alias="entityIdentifier", description="A legal entity identifier with a source (e.g. RED entity code).", min_length=0
    )
