# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-Index.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_observable_asset_CreditIndex_schema,
    cdm_observable_asset_EquityIndex_schema,
    cdm_observable_asset_ForeignExchangeRateIndex_schema,
    cdm_observable_asset_OtherIndex_schema,
    cdm_observable_asset_metafields_FieldWithMetaInterestRateIndex_schema,
)


class Index(BaseModel):
    credit_index: cdm_observable_asset_CreditIndex_schema.CreditIndex | None = Field(
        None,
        alias="CreditIndex",
        description="An index based on credit risk, typically composed using corporate debt instruments in a region or industry sector, e.g. the iTraxx indices.",
    )
    equity_index: cdm_observable_asset_EquityIndex_schema.EquityIndex | None = Field(
        None,
        alias="EquityIndex",
        description="An index based on equity securities, e.g. the S&P 500.",
    )
    interest_rate_index: (
        cdm_observable_asset_metafields_FieldWithMetaInterestRateIndex_schema.FieldWithMetaInterestRateIndex
        | None
    ) = Field(
        None,
        alias="InterestRateIndex",
        description="An index based in interest rates or inflation rates in a certain market.",
    )
    foreign_exchange_rate_index: (
        cdm_observable_asset_ForeignExchangeRateIndex_schema.ForeignExchangeRateIndex | None
    ) = Field(
        None,
        alias="ForeignExchangeRateIndex",
        description="A rate based on the exchange of a pair of cash assets in specific currencies, e.g. USD versus GBP.",
    )
    other_index: cdm_observable_asset_OtherIndex_schema.OtherIndex | None = Field(
        None,
        alias="OtherIndex",
        description="An index created by a market participant which doesn't align with the other index types.",
    )
