# generated by datamodel-codegen:
#   filename:  cdm-product-asset-LoadTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class LoadTypeEnum(StrEnum):
    base_load = "BaseLoad"
    block_hours = "BlockHours"
    gas_day = "GasDay"
    off_peak = "OffPeak"
    other = "Other"
    peak_load = "PeakLoad"
    shaped = "Shaped"
