# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-calculatedrate-CalculationShiftMethodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CalculationShiftMethodEnum(StrEnum):
    LOOKBACK = "Lookback"
    NO_SHIFT = "NoShift"
    OBSERVATION_PERIOD_SHIFT = "ObservationPeriodShift"
    RATE_CUT_OFF = "RateCutOff"
