# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-DayTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DayTypeEnum(StrEnum):
    business = "Business"
    calendar = "Calendar"
    currency_business = "CurrencyBusiness"
    exchange_business = "ExchangeBusiness"
    scheduled_trading_day = "ScheduledTradingDay"
