# generated by datamodel-codegen:
#   filename:  cdm-product-template-OptionFeature.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_product_template_AveragingCalculation_schema,
    cdm_product_template_Barrier_schema,
    cdm_product_template_FxFeature_schema,
    cdm_product_template_Knock_schema,
    cdm_product_template_PassThrough_schema,
    cdm_product_template_StrategyFeature_schema,
)


class OptionFeature(BaseModel):
    fx_feature: list[cdm_product_template_FxFeature_schema.FxFeature] | None = Field(
        None, alias="fxFeature", description="Describes a quanto or composite FX feature.", min_length=0
    )
    strategy_feature: cdm_product_template_StrategyFeature_schema.StrategyFeature | None = Field(
        None, alias="strategyFeature", description="Defines a simple strategy feature."
    )
    averaging_feature: cdm_product_template_AveragingCalculation_schema.AveragingCalculation | None = Field(
        None,
        alias="averagingFeature",
        description="Defines an option feature in which an average market observation price is determined on valuation and compared to the strike to determine a settlement amount.",
    )
    barrier: cdm_product_template_Barrier_schema.Barrier | None = Field(None, description="Specifies a barrier feature.")
    knock: cdm_product_template_Knock_schema.Knock | None = Field(None, description="Specifies a knock in or knock out feature.")
    pass_through: cdm_product_template_PassThrough_schema.PassThrough | None = Field(
        None, alias="passThrough", description="Specifies the rules for pass-through payments from the underlier, such as dividends."
    )
