# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-metafields-FieldWithMetaContractualSupplementTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import (
    cdm_legaldocumentation_common_ContractualSupplementTypeEnum_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class FieldWithMetaContractualSupplementTypeEnum(BaseModel):
    value: cdm_legaldocumentation_common_ContractualSupplementTypeEnum_schema.ContractualSupplementTypeEnum | None = (
        None
    )
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
