# generated by datamodel-codegen:
#   filename:  cdm-event-common-PositionEventIntentEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class PositionEventIntentEnum(StrEnum):
    corporate_action_adjustment = "CorporateActionAdjustment"
    decrease = "Decrease"
    increase = "Increase"
    option_exercise = "OptionExercise"
    position_creation = "PositionCreation"
    transfer = "Transfer"
    valuation = "Valuation"
