# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-ContractualDefinitionsEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ContractualDefinitionsEnum(StrEnum):
    isda1991_interest_rate = "ISDA1991InterestRate"
    isda1993_commodity_derivatives = "ISDA1993CommodityDerivatives"
    isda1996_equity_derivatives = "ISDA1996EquityDerivatives"
    isda1997_bullion = "ISDA1997Bullion"
    isda1997_government_bond_option = "ISDA1997GovernmentBondOption"
    isda1998_fx_and_currency_option = "ISDA1998FxAndCurrencyOption"
    isda1999_credit_derivatives = "ISDA1999CreditDerivatives"
    isda2000 = "ISDA2000"
    isda2002_equity_derivatives = "ISDA2002EquityDerivatives"
    isda2003_credit_derivatives = "ISDA2003CreditDerivatives"
    isda2004_novation = "ISDA2004Novation"
    isda2005_commodity = "ISDA2005Commodity"
    isda2006 = "ISDA2006"
    isda2006_inflation_derivatives = "ISDA2006InflationDerivatives"
    isda2008_inflation_derivatives = "ISDA2008InflationDerivatives"
    isda2011_equity_derivatives = "ISDA2011EquityDerivatives"
    isda2014_credit_derivatives = "ISDA2014CreditDerivatives"
    isda2021_interest_rate_derivatives = "ISDA2021InterestRateDerivatives"
    isda2022_verified_carbon_credit = "ISDA2022VerifiedCarbonCredit"
    isda2023_digital_asset_derivatives = "ISDA2023DigitalAssetDerivatives"
