# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-master-MasterAgreementBase.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel


class MasterAgreementBase(BaseModel):
    pass
