# generated by datamodel-codegen:
#   filename:  cdm-regulation-AcctOwnr.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_regulation_Id_schema


class AcctOwnr(BaseModel):
    id: cdm_regulation_Id_schema.Id
