# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-DisputeResolution.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_BusinessCenterTime_schema,
    cdm_legaldocumentation_csa_LegacyResolutionAlternative_schema,
    cdm_legaldocumentation_csa_LegacyResolutionValue_schema,
    cdm_legaldocumentation_csa_RecalculationOfValue_schema,
)


class DisputeResolution(BaseModel):
    resolution_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None,
        alias="resolutionTime",
        description="The time by which the dispute needs to be resolved, failure of which would trigger a recalculation alongside a process that is specified as part of the agreement.",
    )
    other_terms: str | None = Field(
        None,
        alias="otherTerms",
        description="The custom Resolution Time election that might be specified by the parties.",
    )
    value_terms: str = Field(
        ...,
        alias="valueTerms",
        description="The method of calculation for determining value for the purposes of a Variation Margin agreement.",
    )
    alternative_terms: str | None = Field(
        None, alias="alternativeTerms", description="The alternative dispute resolution procedure if specified."
    )
    recalculation_of_value: cdm_legaldocumentation_csa_RecalculationOfValue_schema.RecalculationOfValue | None = Field(
        None,
        alias="recalculationOfValue",
        description="The elections to specify terms for recalculation of the market value of posted collateral.",
    )
    legacy_resolution_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None,
        alias="legacyResolutionTime",
        description="Definition of a point of time un the following LBD to the date of notice in the resolution process at which the recalculation of the disputed amount(s) begins if the consultation process has not resolved the dispute.",
    )
    legacy_alternative: (
        cdm_legaldocumentation_csa_LegacyResolutionAlternative_schema.LegacyResolutionAlternative | None
    ) = Field(
        None,
        alias="legacyAlternative",
        description="Alternative procedures to those in the pre-print for resolving collateral related disputes.",
    )
    legacy_value: cdm_legaldocumentation_csa_LegacyResolutionValue_schema.LegacyResolutionValue | None = Field(
        None,
        alias="legacyValue",
        description="Methodology for resolving disputes in respect of the determination of the value of collateral.",
    )
