# generated by datamodel-codegen:
#   filename:  cdm-product-asset-GeneralTerms.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_observable_asset_CreditIndex_schema,
    cdm_product_asset_BasketReferenceInformation_schema,
    cdm_product_asset_ReferenceInformation_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class GeneralTerms(BaseModel):
    reference_information: cdm_product_asset_ReferenceInformation_schema.ReferenceInformation | None = Field(
        None,
        alias="referenceInformation",
        description="This attribute contains all the terms relevant to defining the reference entity and reference obligation(s).",
    )
    index_reference_information: cdm_observable_asset_CreditIndex_schema.CreditIndex | None = Field(
        None,
        alias="indexReferenceInformation",
        description="This attribute contains all the terms relevant to the underlying Index.",
    )
    basket_reference_information: (
        cdm_product_asset_BasketReferenceInformation_schema.BasketReferenceInformation | None
    ) = Field(
        None,
        alias="basketReferenceInformation",
        description="This attribute contains all the terms relevant to defining the Credit Default Swap Basket.",
    )
    additional_term: list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None = Field(
        None,
        alias="additionalTerm",
        description="This attribute is used for representing information contained in the Additional Terms field of the 2003 Master Credit Derivatives confirm.",
        min_length=0,
    )
    substitution: bool | None = Field(
        None, description="Value of this attribute set to 'true' indicates that substitution is applicable."
    )
    modified_equity_delivery: bool | None = Field(
        None,
        alias="modifiedEquityDelivery",
        description="Value of this attribute set to 'true' indicates that modified equity delivery is applicable.",
    )
