# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-AncillaryRoleEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AncillaryRoleEnum(StrEnum):
    calculation_agent_fallback = "CalculationAgentFallback"
    calculation_agent_independent = "CalculationAgentIndependent"
    calculation_agent_mandatory_early_termination = "CalculationAgentMandatoryEarlyTermination"
    calculation_agent_optional_early_termination = "CalculationAgentOptionalEarlyTermination"
    disruption_events_determining_party = "DisruptionEventsDeterminingParty"
    exercise_notice_receiver_party_cancelable_provision = "ExerciseNoticeReceiverPartyCancelableProvision"
    exercise_notice_receiver_party_extendible_provision = "ExerciseNoticeReceiverPartyExtendibleProvision"
    exercise_notice_receiver_party_manual = "ExerciseNoticeReceiverPartyManual"
    exercise_notice_receiver_party_optional_early_termination = "ExerciseNoticeReceiverPartyOptionalEarlyTermination"
    extraordinary_dividends_party = "ExtraordinaryDividendsParty"
    predetermined_clearing_organization_party = "PredeterminedClearingOrganizationParty"
