# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-FxForceMajeureOrActOfSStateEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class FxForceMajeureOrActOfSStateEnum(StrEnum):
    to_be_treated_as_disruption_event = "ToBeTreatedAsDisruptionEvent"
    to_be_treated_as_force_majeure_or_act_of_s_state = "ToBeTreatedAsForceMajeureOrActOfSState"
