# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-AdjustableRelativeOrPeriodicDates.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_AdjustableDates_schema, cdm_base_datetime_PeriodicDates_schema, cdm_base_datetime_RelativeDates_schema


class AdjustableRelativeOrPeriodicDates(BaseModel):
    adjustable_dates: cdm_base_datetime_AdjustableDates_schema.AdjustableDates | None = Field(
        None,
        alias="adjustableDates",
        description="A series of dates that shall be subject to adjustment if they would otherwise fall on a day that is not a business day in the specified business centers, together with the convention for adjusting the date.",
    )
    relative_dates: cdm_base_datetime_RelativeDates_schema.RelativeDates | None = Field(
        None, alias="relativeDates", description="A series of dates specified as some offset to another series of dates (the anchor dates)."
    )
    periodic_dates: cdm_base_datetime_PeriodicDates_schema.PeriodicDates | None = Field(
        None, alias="periodicDates", description="A calculation period schedule."
    )
