# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyResolutionAlternative.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_LegacyResolutionAlternativeEnum_schema, cdm_observable_asset_Money_schema


class LegacyResolutionAlternative(BaseModel):
    resolution_alternative: cdm_legaldocumentation_csa_LegacyResolutionAlternativeEnum_schema.LegacyResolutionAlternativeEnum | None = (
        Field(None, alias="resolutionAlternative", description="Details of the alternative dispute resolution procedure (if any).")
    )
    amount: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        description="The maximum amount to which the difference between the calculations by the valuation agent and disputing party can be split, where Split the Difference is elected.",
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
