# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-calculatedrate-CalculationMethodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CalculationMethodEnum(StrEnum):
    AVERAGING = "Averaging"
    COMPOUNDED_INDEX = "CompoundedIndex"
    COMPOUNDING = "Compounding"
