# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-ObservationDate.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class ObservationDate(BaseModel):
    unadjusted_date: str | None = Field(None, alias="unadjustedDate", description="A date subject to adjustment.")
    adjusted_date: str | None = Field(
        None,
        alias="adjustedDate",
        description="The date once the adjustment has been performed. (Note that this date may change if the business center holidays change).",
    )
    weight: float | None = Field(None, description="Specifies the degree of importance of the observation.")
    observation_reference: str | None = Field(
        None,
        alias="observationReference",
        description="Specifies an identification key for the market observation. This attribute can be used as a reference to assign weights to a series of dates defined in a parametricSchedule.",
    )
