# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-FxSubstitutionProvisionTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class FxSubstitutionProvisionTypeEnum(StrEnum):
    LOCAL_ASSET_SUBSTITUTE_GROSS = "LocalAssetSubstituteGross"
    LOCAL_ASSET_SUBSTITUTE_NET = "LocalAssetSubstituteNet"
    LOCAL_CURRENCY_SUBSTITUTE = "LocalCurrencySubstitute"
