# generated by datamodel-codegen:
#   filename:  cdm-observable-event-FailureToPay.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_Money_schema, cdm_observable_event_GracePeriodExtension_schema


class FailureToPay(BaseModel):
    applicable: bool = Field(..., description="Indicates whether the failure to pay provision is applicable.")
    grace_period_extension: cdm_observable_event_GracePeriodExtension_schema.GracePeriodExtension | None = Field(
        None,
        alias="gracePeriodExtension",
        description="If this element is specified, indicates whether or not a grace period extension is applicable. ISDA 2003 Term: Grace Period Extension Applicable.",
    )
    payment_requirement: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        alias="paymentRequirement",
        description="Specifies a threshold for the failure to pay credit event. Market standard is USD 1,000,000 (JPY 100,000,000 for Japanese Yen trades) or its equivalent in the relevant obligation currency. This is applied on an aggregate basis across all Obligations of the Reference Entity. Intended to prevent technical/operational errors from triggering credit events. ISDA 2003 Term: Payment Requirement",
    )
