# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-RatingPriorityResolutionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class RatingPriorityResolutionEnum(StrEnum):
    ASSET = "Asset"
    AVERAGE = "Average"
    HIGHEST = "Highest"
    ISSUER = "Issuer"
    LOWEST = "Lowest"
