# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-PrincipalPayments.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_product_common_settlement_PrincipalPaymentSchedule_schema


class PrincipalPayments(BaseModel):
    initial_payment: bool = Field(
        ...,
        alias="initialPayment",
        description="A true/false flag to indicate whether there is an initial exchange of principal on the effective date.",
    )
    final_payment: bool = Field(
        ...,
        alias="finalPayment",
        description="A true/false flag to indicate whether there is a final exchange of principal on the termination date.",
    )
    intermediate_payment: bool = Field(
        ...,
        alias="intermediatePayment",
        description="A true/false flag to indicate whether there are intermediate or interim exchanges of principal during the term of the swap.",
    )
    varying_leg_notional_currency: list[str] | None = Field(
        None,
        alias="varyingLegNotionalCurrency",
        description="Indicate the Payout legs which nominal amount may vary in regards of FX Fixing dates as determined in the product terms.",
        min_length=0,
    )
    principal_payment_schedule: cdm_product_common_settlement_PrincipalPaymentSchedule_schema.PrincipalPaymentSchedule | None = Field(
        None,
        alias="principalPaymentSchedule",
        description="Describe dates schedules for Principal Exchanges and related role of the parties when known.",
    )
