# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-AdditionalRepresentation.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_AdditionalRepresentationElection_schema


class AdditionalRepresentation(BaseModel):
    party_election: list[cdm_legaldocumentation_csa_AdditionalRepresentationElection_schema.AdditionalRepresentationElection] | None = (
        Field(
            None,
            alias="partyElection",
            description="A qualification as to whether the Additional Representation is applicable.",
            max_length=2,
            min_length=2,
        )
    )
    custom_election: str | None = Field(
        None,
        alias="customElection",
        description="A supplemental custom election that might be specified by the parties for the purpose of specifying the Additional Representation.",
    )
