# generated by datamodel-codegen:
#   filename:  cdm-product-template-PassThrough.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_template_PassThroughItem_schema


class PassThrough(BaseModel):
    pass_through_item: list[cdm_product_template_PassThroughItem_schema.PassThroughItem] | None = Field(
        None, alias="passThroughItem", description="One to many pass through payment items.", min_length=1
    )
