# generated by datamodel-codegen:
#   filename:  cdm-event-common-MarginCallInstructionType.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_CallTypeEnum_schema


class MarginCallInstructionType(BaseModel):
    call_type: cdm_event_common_CallTypeEnum_schema.CallTypeEnum = Field(
        ...,
        alias="callType",
        description="Indicates the status of the call message type, such as expected call, notification of a call or an actionable margin call.",
    )
    visibility_indicator: bool | None = Field(
        None,
        alias="visibilityIndicator",
        description="Indicates the choice if the call instruction is visible or not to the other party.",
    )
