# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-FxLinkedNotionalAmount.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class FxLinkedNotionalAmount(BaseModel):
    reset_date: str | None = Field(None, alias="resetDate", description="The reset date.")
    adjusted_fx_spot_fixing_date: str | None = Field(
        None,
        alias="adjustedFxSpotFixingDate",
        description="The date on which the FX spot rate is observed. This date should already be adjusted for any applicable business day convention.",
    )
    observed_fx_spot_rate: float | None = Field(
        None, alias="observedFxSpotRate", description="The actual observed FX spot rate."
    )
    notional_amount: float | None = Field(
        None, alias="notionalAmount", description="The calculation period notional amount."
    )
