# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-DateRelativeToValuationDates.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_metafields_ReferenceWithMetaPerformanceValuationDates_schema


class DateRelativeToValuationDates(BaseModel):
    valuation_dates_reference: (
        list[cdm_observable_asset_metafields_ReferenceWithMetaPerformanceValuationDates_schema.ReferenceWithMetaPerformanceValuationDates]
        | None
    ) = Field(
        None,
        alias="valuationDatesReference",
        description="A set of href pointers to valuation period dates defined somewhere else in the document.",
        min_length=1,
    )
