# generated by datamodel-codegen:
#   filename:  cdm-event-common-ScheduledTransfer.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_event_common_CorporateActionTypeEnum_schema,
    cdm_product_common_settlement_ScheduledTransferEnum_schema,
)


class ScheduledTransfer(BaseModel):
    transfer_type: cdm_product_common_settlement_ScheduledTransferEnum_schema.ScheduledTransferEnum = Field(
        ...,
        alias="transferType",
        description="Specifies a transfer created from a scheduled or contingent event on a contract, e.g. Exercise, Performance, Credit Event",
    )
    corporate_action_transfer_type: (
        cdm_event_common_CorporateActionTypeEnum_schema.CorporateActionTypeEnum | None
    ) = Field(None, alias="corporateActionTransferType")
