# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SinglePostingParty.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_CounterpartyRoleEnum_schema


class SinglePostingParty(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = Field(
        None, description="The party acting as the Single Posting Party."
    )
    other: str | None = Field(
        None, description="Utilised where the clause data structure is not able to capture a material aspect of the clause."
    )
