# generated by datamodel-codegen:
#   filename:  cdm-product-common-NotionalAdjustmentEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class NotionalAdjustmentEnum(StrEnum):
    EXECUTION = "Execution"
    PORTFOLIO_REBALANCING = "PortfolioRebalancing"
    STANDARD = "Standard"
