# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ProcessAgent.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_ProcessAgentElection_schema


class ProcessAgent(BaseModel):
    party_election: list[cdm_legaldocumentation_csa_ProcessAgentElection_schema.ProcessAgentElection] | None = Field(
        None, alias="partyElection", description="The parties' Process Agent election.", max_length=2, min_length=2
    )
