# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-FxAdditionalTerms.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_transaction_additionalterms_DeterminationRolesAndTerms_schema,
    cdm_legaldocumentation_transaction_additionalterms_FxDisruptionEvents_schema,
)


class FxAdditionalTerms(BaseModel):
    disruption_events: cdm_legaldocumentation_transaction_additionalterms_FxDisruptionEvents_schema.FxDisruptionEvents | None = Field(
        None, alias="disruptionEvents"
    )
    determination_terms: (
        cdm_legaldocumentation_transaction_additionalterms_DeterminationRolesAndTerms_schema.DeterminationRolesAndTerms | None
    ) = Field(None, alias="determinationTerms")
    no_fault_termination: bool | None = Field(None, alias="noFaultTermination")
