# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ControlAgreementElections.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_CounterpartyRoleEnum_schema


class ControlAgreementElections(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    control_agreement_as_csd: bool = Field(
        ...,
        alias="controlAgreementAsCsd",
        description="The identification of whether the Control Agreement is a Credit Support Document with respect to each party.",
    )
    consistency_with_control_agreement: bool | None = Field(
        None,
        alias="consistencyWithControlAgreement",
        description="Unless specified as inapplicable in the event of any inconsistency between this Deed and the Control Agreement, this Deed will prevail over the Control Agreement.",
    )
    relationship_with_control_agreement: bool | None = Field(
        None,
        alias="relationshipWithControlAgreement",
        description="Unless specified as inapplicable the parties recognise that the Control Agreement is a means by which the parties can perform their obligations.",
    )
