# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-NotificationTime.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_NotificationTimeElection_schema


class NotificationTime(BaseModel):
    party_elections: (
        list[cdm_legaldocumentation_csa_NotificationTimeElection_schema.NotificationTimeElection]
        | None
    ) = Field(
        None,
        alias="partyElections",
        description="The parties' Notification Time election.",
        max_length=2,
        min_length=2,
    )
    dispute_notification_reference: bool | None = Field(
        None,
        alias="disputeNotificationReference",
        description="The determination of whether reference is made to dispute resolution notification timing in the agreement.",
    )
    transfer_timing_proviso: bool | None = Field(
        None,
        alias="transferTimingProviso",
        description="The determination of whether transfer timing language is applicable or not.",
    )
