# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SecurityProviderRightsEventElection.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_CounterpartyRoleEnum_schema


class SecurityProviderRightsEventElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(..., description="The elective party.")
    rights_event: bool = Field(..., alias="rightsEvent", description="If True, the Rights Event language applies for the specified Party.")
