# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-FxInconvertibilityOrNonTransferability.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_transaction_additionalterms_GeneralInconvertibility_schema,
    cdm_legaldocumentation_transaction_additionalterms_GeneralNonTransferability_schema,
    cdm_legaldocumentation_transaction_additionalterms_SpecificInconvertibility_schema,
    cdm_legaldocumentation_transaction_additionalterms_SpecificNonTransferability_schema,
)


class FxInconvertibilityOrNonTransferability(BaseModel):
    general_inconvertibility: (
        cdm_legaldocumentation_transaction_additionalterms_GeneralInconvertibility_schema.GeneralInconvertibility
        | None
    ) = Field(None, alias="generalInconvertibility")
    general_non_transferability: (
        cdm_legaldocumentation_transaction_additionalterms_GeneralNonTransferability_schema.GeneralNonTransferability
        | None
    ) = Field(None, alias="generalNonTransferability")
    specific_inconvertibility: (
        cdm_legaldocumentation_transaction_additionalterms_SpecificInconvertibility_schema.SpecificInconvertibility
        | None
    ) = Field(None, alias="specificInconvertibility")
    specific_non_transferability: (
        cdm_legaldocumentation_transaction_additionalterms_SpecificNonTransferability_schema.SpecificNonTransferability
        | None
    ) = Field(None, alias="specificNonTransferability")
