# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RatingTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class RatingTypeEnum(StrEnum):
    long_term = "LongTerm"
    short_term = "ShortTerm"
