# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-FallbackReferencePrice.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_observable_asset_CalculationAgent_schema,
    cdm_observable_asset_ValuationPostponement_schema,
    cdm_observable_asset_metafields_FieldWithMetaSettlementRateOptionEnum_schema,
)


class FallbackReferencePrice(BaseModel):
    valuation_postponement: cdm_observable_asset_ValuationPostponement_schema.ValuationPostponement | None = Field(
        None,
        alias="valuationPostponement",
        description="Specifies how long to wait to get a quote from a settlement rate option upon a price source disruption.",
    )
    fall_back_settlement_rate_option: (
        list[
            cdm_observable_asset_metafields_FieldWithMetaSettlementRateOptionEnum_schema.FieldWithMetaSettlementRateOptionEnum
        ]
        | None
    ) = Field(
        None,
        alias="fallBackSettlementRateOption",
        description="This settlement rate option will be used in its place.",
        min_length=0,
    )
    fallback_survey_valuation_postponement: bool | None = Field(
        None,
        alias="fallbackSurveyValuationPostponement",
        description="Request rate quotes from the market. This element is set as type Empty in FpML. When present, the FpML synonym is mapped to a value True in the CDM.",
    )
    calculation_agent_determination: cdm_observable_asset_CalculationAgent_schema.CalculationAgent | None = Field(
        None, alias="calculationAgentDetermination", description="The calculation agent will decide the rate."
    )
