# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-ConcentrationLimitTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ConcentrationLimitTypeEnum(StrEnum):
    asset = "Asset"
    base_currency_equivalent = "BaseCurrencyEquivalent"
    industry_sector = "IndustrySector"
    issue_outstanding_amount = "IssueOutstandingAmount"
    issuer = "Issuer"
    market_capitalisation = "MarketCapitalisation"
    primary_exchange = "PrimaryExchange"
    ultimate_parent_institution = "UltimateParentInstitution"
