# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-MTAZeroEventEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class MTAZeroEventEnum(StrEnum):
    ADDITIONAL_TERMINATION_EVENT = "AdditionalTerminationEvent"
    EVENT_OF_DEFAULT = "EventOfDefault"
    OTHER = "Other"
    POTENTIAL_EVENT_OF_DEFAULT = "PotentialEventOfDefault"
    TERMINATION_EVENT = "TerminationEvent"
    A_TERMINATION_EVENT_IN_RESPECT_OF_WHICH_ALL_TRANSACTIONS_ARE_AFFECTED_TRANSACTIONS = (
        "A Termination Event in respect of which all Transactions are Affected Transactions"
    )
