# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CollateralTransferAgreementElections.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_csa_AdditionalRepresentations_schema,
    cdm_legaldocumentation_csa_BaseAndEligibleCurrency_schema,
    cdm_legaldocumentation_csa_CalculationAndTiming_schema,
    cdm_legaldocumentation_csa_ConditionsPrecedent_schema,
    cdm_legaldocumentation_csa_CreditSupportObligations_schema,
    cdm_legaldocumentation_csa_CustodyArrangements_schema,
    cdm_legaldocumentation_csa_DisputeResolution_schema,
    cdm_legaldocumentation_csa_FinalReturns_schema,
    cdm_legaldocumentation_csa_FxHaircutCurrency_schema,
    cdm_legaldocumentation_csa_GeneralSimmElections_schema,
    cdm_legaldocumentation_csa_JurisdictionRelatedTerms_schema,
    cdm_legaldocumentation_csa_MinimumTransferAmountAmendment_schema,
    cdm_legaldocumentation_csa_OneWayProvisions_schema,
    cdm_legaldocumentation_csa_PledgeeRepresentativeRider_schema,
    cdm_legaldocumentation_csa_PostingObligations_schema,
    cdm_legaldocumentation_csa_ProcessAgent_schema,
    cdm_legaldocumentation_csa_Regime_schema,
    cdm_legaldocumentation_csa_RightsEvents_schema,
    cdm_legaldocumentation_csa_SensitivityMethodologies_schema,
    cdm_legaldocumentation_csa_SubstitutedRegime_schema,
    cdm_legaldocumentation_csa_Substitution_schema,
    cdm_legaldocumentation_csa_TerminationCurrencyAmendment_schema,
    cdm_product_collateral_ContactElection_schema,
)


class CollateralTransferAgreementElections(BaseModel):
    regime: cdm_legaldocumentation_csa_Regime_schema.Regime = Field(
        ...,
        description="The Regime Table provision , which determines the regulatory regime(s) applicable to each of the parties to the agreement.",
    )
    one_way_provisions: cdm_legaldocumentation_csa_OneWayProvisions_schema.OneWayProvisions = Field(
        ...,
        alias="oneWayProvisions",
        description="The determination of whether the One Way Provisions are applicable (true) or not applicable (false).",
    )
    general_simm_elections: cdm_legaldocumentation_csa_GeneralSimmElections_schema.GeneralSimmElections = Field(
        ...,
        alias="generalSimmElections",
        description="The specification of the ISDA SIMM Method for all Covered Transactions with respect to all Regimes.",
    )
    identified_cross_currency_swap: bool | None = Field(
        None,
        alias="identifiedCrossCurrencySwap",
        description="The qualification of whether cross-currency swaps need to be identified in the Confirmation so that the obligations to exchange principal be disregarded for the purpose of determining the Delivery Amount or Return Amount.",
    )
    sensitivity_methodologies: cdm_legaldocumentation_csa_SensitivityMethodologies_schema.SensitivityMethodologies = Field(
        ...,
        alias="sensitivityMethodologies",
        description="The specification of methodologies to compute sensitivities specific to the agreement.",
    )
    fx_haircut_currency: cdm_legaldocumentation_csa_FxHaircutCurrency_schema.FxHaircutCurrency | None = Field(
        None,
        alias="fxHaircutCurrency",
        description="The reference currency for the purpose of specifying the FX Haircut relating to a posting obligation, as being either the Termination Currency or an FX Designated Currency.",
    )
    posting_obligations: cdm_legaldocumentation_csa_PostingObligations_schema.PostingObligations = Field(
        ..., alias="postingObligations", description="The security providers posting obligations."
    )
    substituted_regime: list[cdm_legaldocumentation_csa_SubstitutedRegime_schema.SubstitutedRegime] | None = Field(
        None,
        alias="substitutedRegime",
        description="The specification of Additional regimes for purposes of determining whether a Regulatory Event has occurred.",
        min_length=1,
    )
    base_and_eligible_currency: cdm_legaldocumentation_csa_BaseAndEligibleCurrency_schema.BaseAndEligibleCurrency = Field(
        ...,
        alias="baseAndEligibleCurrency",
        description="The base and eligible currency(ies) for the document as specified by the parties to the agreement.",
    )
    credit_support_obligations: cdm_legaldocumentation_csa_CreditSupportObligations_schema.CreditSupportObligations = Field(
        ..., alias="creditSupportObligations", description="The Credit Support Obligations applicable to the agreement."
    )
    calculation_and_timing: cdm_legaldocumentation_csa_CalculationAndTiming_schema.CalculationAndTiming = Field(
        ...,
        alias="calculationAndTiming",
        description="The set of elections for determining Valuation and Timing terms specific to the agreement.",
    )
    conditions_precedent: cdm_legaldocumentation_csa_ConditionsPrecedent_schema.ConditionsPrecedent = Field(
        ...,
        alias="conditionsPrecedent",
        description="The set of elections that may overwrite the default Condition Precedent provision, and the set of provisions that are deemed Access Condition.",
    )
    substitution: cdm_legaldocumentation_csa_Substitution_schema.Substitution | None = Field(
        None, description="The conditions under which the Security Provider can substitute posted collateral."
    )
    dispute_resolution: cdm_legaldocumentation_csa_DisputeResolution_schema.DisputeResolution = Field(
        ...,
        alias="disputeResolution",
        description="The election terms under which a party disputes (i) the Calculation Agents calculation of a Delivery Amount or a Return Amount, or (ii) the Value of any Transfer of Eligible Credit Support or Posted Credit Support.",
    )
    rights_events: cdm_legaldocumentation_csa_RightsEvents_schema.RightsEvents | None = Field(
        None,
        alias="rightsEvents",
        description="The bespoke provisions that might be specified by the parties to the agreement to specify the rights of Security Taker and/or Security Provider when an Early Termination or Access Condition event has occurred.",
    )
    custody_arrangements: cdm_legaldocumentation_csa_CustodyArrangements_schema.CustodyArrangements = Field(
        ...,
        alias="custodyArrangements",
        description="The Custodian and Segregated Account details in respect of each party to the agreement.",
    )
    additional_representations: cdm_legaldocumentation_csa_AdditionalRepresentations_schema.AdditionalRepresentations = Field(
        ...,
        alias="additionalRepresentations",
        description="The specification Additional Representations that may be applicable to the agreement.",
    )
    demands_and_notices: cdm_product_collateral_ContactElection_schema.ContactElection | None = Field(
        None,
        alias="demandsAndNotices",
        description="The optional specification of address where the demands, specifications and notices will be communicated to for each of the parties to the agreement.",
    )
    addresses_for_transfer: cdm_product_collateral_ContactElection_schema.ContactElection | None = Field(
        None,
        alias="addressesForTransfer",
        description="The optional specification of address for transfer as specified by the respective parties to the agreement.",
    )
    other_csa: str | None = Field(
        None, alias="otherCsa", description="The bespoke definition of Other CSA as specified by the parties to the agreement."
    )
    termination_currency_amendment: cdm_legaldocumentation_csa_TerminationCurrencyAmendment_schema.TerminationCurrencyAmendment = Field(
        ...,
        alias="terminationCurrencyAmendment",
        description="The bespoke provision that might be specified by the parties to the agreement applicable to Termination Currency.  Unless specified the definition of Termination Currency has the meaning specified in the Schedule to the ISDA Master Agreement.",
    )
    minimum_transfer_amount_amendment: (
        cdm_legaldocumentation_csa_MinimumTransferAmountAmendment_schema.MinimumTransferAmountAmendment | None
    ) = Field(
        None,
        alias="minimumTransferAmountAmendment",
        description="The bespoke provision that might be specified by the parties to the agreement applicable to Minimum Transfer Amount.  Unless specified the definition of Minimum Transfer Amount in any Other Regulatory CSA has the meaning specified in such Other Regulatory CSA.",
    )
    interpretation_terms: str | None = Field(
        None,
        alias="interpretationTerms",
        description="The bespoke provision that might be specified by the parties to the agreement applicable to Interpretations.",
    )
    process_agent: cdm_legaldocumentation_csa_ProcessAgent_schema.ProcessAgent | None = Field(
        None, alias="processAgent", description="The Process Agent that might be appointed by the parties to the agreement."
    )
    jurisdiction_related_terms: cdm_legaldocumentation_csa_JurisdictionRelatedTerms_schema.JurisdictionRelatedTerms | None = Field(
        None, alias="jurisdictionRelatedTerms", description="The jurisdiction specific terms relevant to the agreement."
    )
    additional_amendments: str | None = Field(
        None, alias="additionalAmendments", description="Any additional amendments that might be specified by the parties to the agreement."
    )
    additional_bespoke_terms: str | None = Field(
        None, alias="additionalBespokeTerms", description="Any additional terms that might be specified applicable."
    )
    pledgee_representative_rider: cdm_legaldocumentation_csa_PledgeeRepresentativeRider_schema.PledgeeRepresentativeRider | None = Field(
        None,
        alias="pledgeeRepresentativeRider",
        description="The terms of the Rider for the ISDA Euroclear 2019 Collateral Transfer Agreement with respect to the use of a Pledgee Representative attached to this Agreement.",
    )
    final_returns: cdm_legaldocumentation_csa_FinalReturns_schema.FinalReturns = Field(
        ...,
        alias="finalReturns",
        description="A clause providing that final return collateral is to be provided without consideration of any Minimum Transfer Amount and collateral haircut.",
    )
