# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-PeriodTimeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class PeriodTimeEnum(StrEnum):
    hour = "Hour"
    minute = "Minute"
    second = "Second"
