# generated by datamodel-codegen:
#   filename:  cdm-event-position-PortfolioState.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_Lineage_schema, cdm_event_position_Position_schema


class PortfolioState(BaseModel):
    positions: list[cdm_event_position_Position_schema.Position] | None = Field(
        None, description="The list of positions, each containing a Quantity and a Product.", min_length=0
    )
    lineage: cdm_event_common_Lineage_schema.Lineage = Field(
        ...,
        description="Pointer to the previous PortfolioState and new Event(s) leading to the current (new) state. Previous PortfolioState in the Lineage can be Null in case this is the start of the chain of Events.",
    )
