# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyDeliveryAmount.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_LegacyDeliveryReturnAmountEnum_schema


class LegacyDeliveryAmount(BaseModel):
    legacy_delivery_amount: cdm_legaldocumentation_csa_LegacyDeliveryReturnAmountEnum_schema.LegacyDeliveryReturnAmountEnum = Field(
        ...,
        alias="legacyDeliveryAmount",
        description="Specifies whether the meaning of Delivery Amount follows the pre-print definition or deviates from this (either based on a rating or some other methodology).",
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
