# generated by datamodel-codegen:
#   filename:  cdm-product-asset-ReturnTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ReturnTypeEnum(StrEnum):
    price = "Price"
    total = "Total"
