# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RecalculationOfValueElectionEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class RecalculationOfValueElectionEnum(StrEnum):
    consulation_procedure = "ConsulationProcedure"
    not_applicable = "NotApplicable"
    other_regulatory_csa_procedure = "OtherRegulatoryCSAProcedure"
    specified = "Specified"
