# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-AssetClassEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AssetClassEnum(StrEnum):
    COMMODITY = "Commodity"
    CREDIT = "Credit"
    EQUITY = "Equity"
    FOREIGN_EXCHANGE = "ForeignExchange"
    INTEREST_RATE = "InterestRate"
    MONEY_MARKET = "MoneyMarket"
