# generated by datamodel-codegen:
#   filename:  cdm-event-common-AssetTransferTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AssetTransferTypeEnum(StrEnum):
    FREE_OF_PAYMENT = "FreeOfPayment"
