# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-PriceOperandEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class PriceOperandEnum(StrEnum):
    accrued_interest = "AccruedInterest"
    commission = "Commission"
    forward_point = "ForwardPoint"
