# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-metafields-FieldWithMetaTimeZone.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_base_datetime_TimeZone_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaTimeZone(BaseModel):
    value: cdm_base_datetime_TimeZone_schema.TimeZone | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
