# generated by datamodel-codegen:
#   filename:  cdm-event-common-Transfer.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableOrAdjustedOrRelativeDate_schema,
    cdm_base_math_NonNegativeQuantity_schema,
    cdm_base_staticdata_asset_common_Asset_schema,
    cdm_base_staticdata_identifier_metafields_FieldWithMetaIdentifier_schema,
    cdm_base_staticdata_party_PartyReferencePayerReceiver_schema,
    cdm_event_common_Reset_schema,
    cdm_event_common_TransferExpression_schema,
    cdm_product_template_metafields_ReferenceWithMetaPayout_schema,
)


class Transfer(BaseModel):
    quantity: cdm_base_math_NonNegativeQuantity_schema.NonNegativeQuantity | None = Field(
        None,
        description="Represents the amount of the asset to be transferred. The cashflow amount is always a positive number, as the cashflow direction is implied by the payer/receiver attribute.",
    )
    asset: cdm_base_staticdata_asset_common_Asset_schema.Asset | None = Field(
        None, description="Represents the object that is subject to the transfer, it could be an asset or a reference."
    )
    settlement_date: cdm_base_datetime_AdjustableOrAdjustedOrRelativeDate_schema.AdjustableOrAdjustedOrRelativeDate | None = Field(
        None, alias="settlementDate", description="Represents the date on which the transfer to due."
    )
    identifier: list[cdm_base_staticdata_identifier_metafields_FieldWithMetaIdentifier_schema.FieldWithMetaIdentifier] | None = Field(
        None, description="Represents a unique reference to the transfer.", min_length=0
    )
    payer_receiver: cdm_base_staticdata_party_PartyReferencePayerReceiver_schema.PartyReferencePayerReceiver = Field(
        ..., alias="payerReceiver", description="Represents the parties to the transfer and their role."
    )
    settlement_origin: cdm_product_template_metafields_ReferenceWithMetaPayout_schema.ReferenceWithMetaPayout | None = Field(
        None,
        alias="settlementOrigin",
        description="Represents the origin to the transfer as a reference for lineage purposes, whether it originated from trade level settlement terms or from payment terms on an economic payout.",
    )
    reset_origin: cdm_event_common_Reset_schema.Reset | None = Field(
        None,
        alias="resetOrigin",
        description="Represents the reset and observation values that were used to determine the transfer amount.",
    )
    transfer_expression: cdm_event_common_TransferExpression_schema.TransferExpression = Field(
        ...,
        alias="transferExpression",
        description="Specifies a transfer expression (cash price, performance amount, scheduled payment amount, etc.) to define the nature of the transfer amount and its source.",
    )
