# generated by datamodel-codegen:
#   filename:  cdm-regulation-FinInstrmRptgTxRpt.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from ._internal_5 import Tx


class FinInstrmRptgTxRpt(BaseModel):
    tx: Tx
