# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-FeeTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class FeeTypeEnum(StrEnum):
    ASSIGNMENT = "Assignment"
    BROKERAGE_COMMISSION = "BrokerageCommission"
    CORPORATE_ACTION = "CorporateAction"
    CREDIT_EVENT = "CreditEvent"
    INCREASE = "Increase"
    NOVATION = "Novation"
    PARTIAL_TERMINATION = "PartialTermination"
    PREMIUM = "Premium"
    RENEGOTIATION = "Renegotiation"
    TERMINATION = "Termination"
    UPFRONT = "Upfront"
