# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-MultipleCreditNotations.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_math_QuantifierEnum_schema,
    cdm_observable_asset_CreditNotationMismatchResolutionEnum_schema,
    cdm_observable_asset_CreditRatingAgencyEnum_schema,
    cdm_observable_asset_metafields_FieldWithMetaCreditNotation_schema,
)


class MultipleCreditNotations(BaseModel):
    condition: cdm_base_math_QuantifierEnum_schema.QuantifierEnum = Field(
        ...,
        description="An enumerated element, to qualify whether All or Any credit notation applies.",
    )
    credit_notation: (
        list[
            cdm_observable_asset_metafields_FieldWithMetaCreditNotation_schema.FieldWithMetaCreditNotation
        ]
        | None
    ) = Field(
        None,
        alias="creditNotation",
        description="At least two credit notations much be specified.",
        min_length=2,
    )
    mismatch_resolution: (
        cdm_observable_asset_CreditNotationMismatchResolutionEnum_schema.CreditNotationMismatchResolutionEnum
        | None
    ) = Field(None, alias="mismatchResolution")
    reference_agency: (
        cdm_observable_asset_CreditRatingAgencyEnum_schema.CreditRatingAgencyEnum | None
    ) = Field(None, alias="referenceAgency")
