# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-AdditionalType.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_AdditionalTypeEnum_schema


class AdditionalType(BaseModel):
    standard_value: cdm_legaldocumentation_csa_AdditionalTypeEnum_schema.AdditionalTypeEnum = Field(
        ...,
        alias="standardValue",
        description="The qualification of the Additional Type of transaction that can require the collection or delivery of initial margin when specified as a standard value.",
    )
    custom_value: str | None = Field(
        None,
        alias="customValue",
        description="The qualification of the Additional Type of transaction that can require the collection or delivery of initial margin when specified as a custom value by the parties to the legal agreement.",
    )
