# generated by datamodel-codegen:
#   filename:  cdm-base-math-CompareOp.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CompareOp(StrEnum):
    equals = "Equals"
    greater_than = "GreaterThan"
    greater_than_or_equals = "GreaterThanOrEquals"
    less_than = "LessThan"
    less_than_or_equals = "LessThanOrEquals"
