# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-PostingObligationsElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_product_collateral_EligibleCollateralCriteria_schema,
)


class PostingObligationsElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    as_permitted: bool = Field(
        ...,
        alias="asPermitted",
        description="If set to True, the Control Agreement is a Credit Support Document with respect to the party(ies).",
    )
    eligible_collateral: (
        list[cdm_product_collateral_EligibleCollateralCriteria_schema.EligibleCollateralCriteria]
        | None
    ) = Field(
        None,
        alias="eligibleCollateral",
        description="The eligible collateral as specified in relation to the pledgor/chargor/obligor(s) posting obligation.",
        min_length=0,
    )
    excluded_collateral: str | None = Field(
        None,
        alias="excludedCollateral",
        description="The excluded collateral as specified in relation to the pledgor/chargor/obligor(s) posting obligation.",
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
