# generated by datamodel-codegen:
#   filename:  cdm-event-common-BillingRecordInstruction.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_metafields_ReferenceWithMetaTradeState_schema, cdm_observable_event_Observation_schema


class BillingRecordInstruction(BaseModel):
    trade_state: cdm_event_common_metafields_ReferenceWithMetaTradeState_schema.ReferenceWithMetaTradeState = Field(
        ..., alias="tradeState", description="The trade for the individual billing record."
    )
    observation: list[cdm_observable_event_Observation_schema.Observation] | None = Field(
        None, description="The observations used to calculate the billing amount.", min_length=1
    )
    record_start_date: str = Field(..., alias="recordStartDate", description="The starting date of the period described by this record")
    record_end_date: str = Field(..., alias="recordEndDate", description="The ending date of the period described by this record")
    settlement_date: str = Field(..., alias="settlementDate", description="The date for settlement of the transfer.")
