# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-metafields-FieldWithMetaAssetClassEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_base_staticdata_asset_common_AssetClassEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaAssetClassEnum(BaseModel):
    value: cdm_base_staticdata_asset_common_AssetClassEnum_schema.AssetClassEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
