# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-UnderlierSubstitutionProvision.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_legaldocumentation_transaction_Clause_schema,
    cdm_legaldocumentation_transaction_ExtraordinaryEvents_schema,
)


class UnderlierSubstitutionProvision(BaseModel):
    who_may_substitute: list[cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum] | None = Field(
        None,
        alias="whoMaySubstitute",
        description="Designates which Counterparty to the transaction who has the right to trigger a substitution or to provide related determination e.g. for instance to qualify the effectiveness of an Event which may be a trigger for substitution, determine the replacement Share to substitute, etc. ; cardinality of this object is 2, in case parties jointly have this role.",
        max_length=2,
        min_length=1,
    )
    substitution_be_spoke_terms: list[cdm_legaldocumentation_transaction_Clause_schema.Clause] | None = Field(
        None,
        alias="substitutionBeSpokeTerms",
        description="Where parties describe any substitution terms e.g. for instance the election criteria for an Asset to be eligible as the Substitute Asset to the prior Affected Asset in terms of sector of activity, currency, market capitalisation, liquidity, volatility, or any additional features that parties would agree to take into considerations, etc.",
        min_length=0,
    )
    substitution_trigger_events: (
        list[cdm_legaldocumentation_transaction_ExtraordinaryEvents_schema.ExtraordinaryEvents] | None
    ) = Field(
        None,
        alias="substitutionTriggerEvents",
        description="Where the parties may optionnally explictly specify the list of Events to be considered as a trigger for a Substitution.",
        min_length=0,
    )
    disputing_party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = Field(
        None,
        alias="disputingParty",
        description="Where the party who is not granted with the substitution role at least has a right to dispute the determination given by the counterparty with such role. As an example, a given PartyA is the unique Counterparty with the Role of WhoMaySubstitute, yet PartyB could be Disputing Party in regard of such Role.",
    )
