# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RecalculationOfValueElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_legaldocumentation_csa_RecalculationOfValueElectionEnum_schema,
)


class RecalculationOfValueElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    recalculation_of_value_election: cdm_legaldocumentation_csa_RecalculationOfValueElectionEnum_schema.RecalculationOfValueElectionEnum = Field(
        ..., alias="recalculationOfValueElection", description="The procedure for Recalculation of Value."
    )
    recalculation_of_value_terms: str | None = Field(
        None, alias="recalculationOfValueTerms", description="Additional Recalculation of Value terms when specified."
    )
