# generated by datamodel-codegen:
#   filename:  cdm-product-template-MandatoryEarlyTermination.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableDate_schema,
    cdm_observable_asset_CalculationAgent_schema,
    cdm_product_common_settlement_SettlementTerms_schema,
    cdm_product_template_MandatoryEarlyTerminationAdjustedDates_schema,
)


class MandatoryEarlyTermination(BaseModel):
    mandatory_early_termination_date: cdm_base_datetime_AdjustableDate_schema.AdjustableDate = Field(
        ...,
        alias="mandatoryEarlyTerminationDate",
        description="The early termination date associated with a mandatory early termination of a swap.",
    )
    calculation_agent: cdm_observable_asset_CalculationAgent_schema.CalculationAgent = Field(
        ...,
        alias="calculationAgent",
        description="The ISDA Calculation Agent responsible for performing duties associated with an optional early termination.",
    )
    cash_settlement: cdm_product_common_settlement_SettlementTerms_schema.SettlementTerms = Field(
        ...,
        alias="cashSettlement",
        description="If specified, this means that cash settlement is applicable to the transaction and defines the parameters associated with the cash settlement procedure. If not specified, then physical settlement is applicable.",
    )
    mandatory_early_termination_adjusted_dates: (
        cdm_product_template_MandatoryEarlyTerminationAdjustedDates_schema.MandatoryEarlyTerminationAdjustedDates | None
    ) = Field(
        None,
        alias="mandatoryEarlyTerminationAdjustedDates",
        description="The adjusted dates associated with a mandatory early termination provision. These dates have been adjusted for any applicable business day convention.",
    )
