# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-NotRatedByEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class NotRatedByEnum(StrEnum):
    ALL = "All"
    ONE = "One"
    TWO = "Two"
