# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-PremiumExpression.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_Money_schema, cdm_observable_asset_PremiumTypeEnum_schema


class PremiumExpression(BaseModel):
    premium_type: cdm_observable_asset_PremiumTypeEnum_schema.PremiumTypeEnum | None = Field(
        None, alias="premiumType", description="Forward start premium type"
    )
    price_per_option: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        alias="pricePerOption",
        description="The amount of premium to be paid expressed as a function of the number of options.",
    )
    percentage_of_notional: float | None = Field(
        None,
        alias="percentageOfNotional",
        description="The amount of premium to be paid expressed as a percentage of the notional value of the transaction. A percentage of 5% would be expressed as 0.05.",
    )
