# generated by datamodel-codegen:
#   filename:  cdm-product-asset-DividendPeriodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class DividendPeriodEnum(StrEnum):
    FIRST_PERIOD = "FirstPeriod"
    SECOND_PERIOD = "SecondPeriod"
