# generated by datamodel-codegen:
#   filename:  cdm-event-common-Lineage.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_event_common_metafields_ReferenceWithMetaTrade_schema,
    cdm_event_position_metafields_ReferenceWithMetaPortfolioState_schema,
    cdm_event_workflow_metafields_ReferenceWithMetaWorkflowStep_schema,
)


class Lineage(BaseModel):
    trade_reference: list[cdm_event_common_metafields_ReferenceWithMetaTrade_schema.ReferenceWithMetaTrade] | None = (
        Field(None, alias="tradeReference", min_length=0)
    )
    event_reference: (
        list[cdm_event_workflow_metafields_ReferenceWithMetaWorkflowStep_schema.ReferenceWithMetaWorkflowStep] | None
    ) = Field(
        None,
        alias="eventReference",
        description="The reference to the instantiation of an Event object, either through a globalKey or an xml-derived id/href mechanism. The definition associated to the Lineage class provides more details with respect to those referencing approaches, their expected usage and available implementation.",
        min_length=0,
    )
    portfolio_state_reference: (
        list[cdm_event_position_metafields_ReferenceWithMetaPortfolioState_schema.ReferenceWithMetaPortfolioState]
        | None
    ) = Field(
        None,
        alias="portfolioStateReference",
        description="The reference to the previous state of a Portfolio, in a chain of Events leading up to a build of that Portfolio as the holding of Product(s) in specific Quantity(ies). As part of the PortfolioState object, a pointer to the previous PortfolioState is provided through a Lineage object, together with pointer(s) to the Event or set of Events leading up to the current (new) state.",
        min_length=0,
    )
