# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-UmbrellaAgreement.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_common_UmbrellaAgreementEntity_schema


class UmbrellaAgreement(BaseModel):
    is_applicable: bool = Field(
        ...,
        alias="isApplicable",
        description="The determination of whether Umbrella Agreement terms are Applicable (True), or Not Applicable (False)",
    )
    language: str | None = Field(
        None,
        description="The language associated with the umbrella agreement, and which applies to all the parties to the umbrella agreement.",
    )
    parties: list[cdm_legaldocumentation_common_UmbrellaAgreementEntity_schema.UmbrellaAgreementEntity] | None = Field(
        None, description="Underlying principals to the umbrella agreement.", min_length=0
    )
