# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-ExecutionLocationEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ExecutionLocationEnum(StrEnum):
    executed_in_belgium = "ExecutedInBelgium"
    executed_outside_belgium = "ExecutedOutsideBelgium"
    other_location = "OtherLocation"
