# generated by datamodel-codegen:
#   filename:  cdm-product-template-CallingPartyEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CallingPartyEnum(StrEnum):
    AS_DEFINED_IN_MASTER_AGREEMENT = "AsDefinedInMasterAgreement"
    EITHER = "Either"
    INITIAL_BUYER = "InitialBuyer"
    INITIAL_SELLER = "InitialSeller"
