# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CustodianTerms.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_LegalEntity_schema,
    cdm_observable_asset_CreditNotation_schema,
    cdm_observable_asset_Money_schema,
)


class CustodianTerms(BaseModel):
    minimum_assets: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        alias="minimumAssets",
        description="The minimal level of assets requirement with respect to the custody agent.",
    )
    minimum_rating: cdm_observable_asset_CreditNotation_schema.CreditNotation | None = Field(
        None, alias="minimumRating", description="The minimal rating requirement with respect to the custody agent."
    )
    initial_designation: cdm_base_staticdata_party_LegalEntity_schema.LegalEntity | None = Field(
        None, alias="initialDesignation", description="Election to specify the initial custodian."
    )
