# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-calculatedrate-OffsetCalculation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class OffsetCalculation(BaseModel):
    offset_days: int | None = Field(None, alias="offsetDays", description="The number of business days offset.")
