# generated by datamodel-codegen:
#   filename:  cdm-product-asset-InterestRatePayout.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableDate_schema,
    cdm_base_datetime_daycount_metafields_FieldWithMetaDayCountFractionEnum_schema,
    cdm_base_staticdata_party_PayerReceiver_schema,
    cdm_product_asset_BondReference_schema,
    cdm_product_asset_CashflowRepresentation_schema,
    cdm_product_asset_CompoundingMethodEnum_schema,
    cdm_product_asset_DiscountingMethod_schema,
    cdm_product_asset_RateSpecification_schema,
    cdm_product_asset_SpreadCalculationMethodEnum_schema,
    cdm_product_common_schedule_CalculationPeriodDates_schema,
    cdm_product_common_schedule_PaymentDates_schema,
    cdm_product_common_schedule_ResetDates_schema,
    cdm_product_common_schedule_StubPeriod_schema,
    cdm_product_common_settlement_PrincipalPayments_schema,
    cdm_product_common_settlement_ResolvablePriceQuantity_schema,
    cdm_product_common_settlement_SettlementTerms_schema,
)


class InterestRatePayout(BaseModel):
    payer_receiver: cdm_base_staticdata_party_PayerReceiver_schema.PayerReceiver | None = Field(
        None,
        alias="payerReceiver",
        description="Canonical representation of the payer and receiver parties applicable to each payout leg.",
    )
    price_quantity: cdm_product_common_settlement_ResolvablePriceQuantity_schema.ResolvablePriceQuantity | None = Field(
        None,
        alias="priceQuantity",
        description="Each payout leg must implement the quantity concept as a 'resolvable' type, which allows for different payout legs to be linked to each other (e.g. in the case of cross-curreny products).",
    )
    principal_payment: cdm_product_common_settlement_PrincipalPayments_schema.PrincipalPayments | None = Field(
        None,
        alias="principalPayment",
        description="The specification of the principal exchange. Optional as only applicable in the case of cross-currency or zero-coupon swaps with a final payment.",
    )
    settlement_terms: cdm_product_common_settlement_SettlementTerms_schema.SettlementTerms | None = Field(
        None,
        alias="settlementTerms",
        description="Each payout leg must specifies its settlement terms, including the delivery type (i.e. cash vs physical, and their respective terms), the transfer type (DvP etc.) and settlement date, if any.",
    )
    rate_specification: cdm_product_asset_RateSpecification_schema.RateSpecification | None = Field(
        None,
        alias="rateSpecification",
        description="The specification of the rate value(s) applicable to the contract using either a floating rate calculation, a single fixed rate, a fixed rate schedule, or an inflation rate calculation.",
    )
    day_count_fraction: (
        cdm_base_datetime_daycount_metafields_FieldWithMetaDayCountFractionEnum_schema.FieldWithMetaDayCountFractionEnum
        | None
    ) = Field(
        None,
        alias="dayCountFraction",
        description="The day count fraction. The cardinality has been relaxed when compared with the FpML interest rate swap for the purpose of accommodating standardized credit default swaps which DCF is not explicitly stated as part of the economic terms. The data rule InterestRatePayout_dayCountFraction requires that the DCF be stated for interest rate products.",
    )
    calculation_period_dates: (
        cdm_product_common_schedule_CalculationPeriodDates_schema.CalculationPeriodDates | None
    ) = Field(
        None,
        alias="calculationPeriodDates",
        description="The parameters used to generate the calculation period dates schedule, including the specification of any initial or final stub calculation periods.",
    )
    payment_dates: cdm_product_common_schedule_PaymentDates_schema.PaymentDates | None = Field(
        None,
        alias="paymentDates",
        description="The payment date schedule, as defined by the parameters that are needed to specify it, either in a parametric way or by reference to another schedule of dates (e.g. the reset dates).",
    )
    payment_date: cdm_base_datetime_AdjustableDate_schema.AdjustableDate | None = Field(
        None,
        alias="paymentDate",
        description="The payment date, where only one date is specified, as for the FRA product.",
    )
    payment_delay: bool | None = Field(
        None,
        alias="paymentDelay",
        description="Applicable to CDS on MBS to specify whether payment delays are applicable to the fixed Amount. RMBS typically have a payment delay of 5 days between the coupon date of the reference obligation and the payment date of the synthetic swap. CMBS do not, on the other hand, with both payment dates being on the 25th of each month.",
    )
    reset_dates: cdm_product_common_schedule_ResetDates_schema.ResetDates | None = Field(
        None,
        alias="resetDates",
        description="The reset dates schedule, i.e. the dates on which the new observed index value is applied for each period and the interest rate hence begins to accrue.",
    )
    discounting_method: cdm_product_asset_DiscountingMethod_schema.DiscountingMethod | None = Field(
        None,
        alias="discountingMethod",
        description="The parameters specifying any discounting conventions that may apply. This element must only be included if discounting applies.",
    )
    compounding_method: cdm_product_asset_CompoundingMethodEnum_schema.CompoundingMethodEnum | None = Field(
        None,
        alias="compoundingMethod",
        description="If one or more calculation period contributes to a single payment amount this element specifies whether compounding is applicable and, if so, what compounding method is to be used. This element must only be included when more than one calculation period contributes to a single payment amount.",
    )
    cashflow_representation: cdm_product_asset_CashflowRepresentation_schema.CashflowRepresentation | None = Field(
        None, alias="cashflowRepresentation", description="The cashflow representation of the swap stream."
    )
    stub_period: cdm_product_common_schedule_StubPeriod_schema.StubPeriod | None = Field(
        None,
        alias="stubPeriod",
        description="The stub calculation period amount parameters. This element must only be included if there is an initial or final stub calculation period. Even then, it must only be included if either the stub references a different floating rate tenor to the regular calculation periods, or if the stub is calculated as a linear interpolation of two different floating rate tenors, or if a specific stub rate or stub amount has been negotiated.",
    )
    bond_reference: cdm_product_asset_BondReference_schema.BondReference | None = Field(
        None,
        alias="bondReference",
        description="Reference to a bond underlier to represent an asset swap or Condition Precedent Bond.",
    )
    fixed_amount: str | None = Field(None, alias="fixedAmount", description="Fixed Amount Calculation")
    floating_amount: str | None = Field(None, alias="floatingAmount", description="Floating Amount Calculation")
    spread_calculation_method: (
        cdm_product_asset_SpreadCalculationMethodEnum_schema.SpreadCalculationMethodEnum | None
    ) = Field(
        None,
        alias="spreadCalculationMethod",
        description="Method by which spread is calculated. For example on an asset swap: 'ParPar' or 'Proceeds' may be the method indicated.",
    )
