# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ControlAgreementNecEventElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_CounterpartyRoleEnum_schema


class ControlAgreementNecEventElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    nec_event: bool = Field(
        ...,
        alias="necEvent",
        description="Indicates Control Agreement language related to delivery of a Notice of Exclusive Control.",
    )
