# generated by datamodel-codegen:
#   filename:  cdm-product-asset-FloatingAmountEvents.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_product_asset_AdditionalFixedPayments_schema,
    cdm_product_asset_FloatingAmountProvisions_schema,
    cdm_product_asset_InterestShortFall_schema,
)


class FloatingAmountEvents(BaseModel):
    failure_to_pay_principal: bool | None = Field(
        None,
        alias="failureToPayPrincipal",
        description="A floating rate payment event. Corresponds to the failure by the Reference Entity to pay an expected principal amount or the payment of an actual principal amount that is less than the expected principal amount. ISDA 2003 Term: Failure to Pay Principal.",
    )
    interest_shortfall: cdm_product_asset_InterestShortFall_schema.InterestShortFall | None = Field(
        None,
        alias="interestShortfall",
        description="A floating rate payment event. With respect to any Reference Obligation Payment Date, either (a) the non-payment of an Expected Interest Amount or (b) the payment of an Actual Interest Amount that is less than the Expected Interest Amount. ISDA 2003 Term: Interest Shortfall.",
    )
    writedown: bool | None = Field(
        None,
        description="A floating rate payment event. Results from the fact that the underlier writes down its outstanding principal amount. ISDA 2003 Term: Writedown.",
    )
    implied_writedown: bool | None = Field(
        None,
        alias="impliedWritedown",
        description="A floating rate payment event. Results from the fact that losses occur to the underlying instruments that do not result in reductions of the outstanding principal of the reference obligation.",
    )
    floating_amount_provisions: (
        cdm_product_asset_FloatingAmountProvisions_schema.FloatingAmountProvisions | None
    ) = Field(
        None,
        alias="floatingAmountProvisions",
        description="Specifies the floating amount provisions associated with the floatingAmountEvents.",
    )
    additional_fixed_payments: (
        cdm_product_asset_AdditionalFixedPayments_schema.AdditionalFixedPayments | None
    ) = Field(
        None,
        alias="additionalFixedPayments",
        description="Specifies the events that will give rise to the payment additional fixed payments.",
    )
