# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-AdjustableOrAdjustedOrRelativeDate.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_BusinessDayAdjustments_schema,
    cdm_base_datetime_RelativeDateOffset_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class AdjustableOrAdjustedOrRelativeDate(BaseModel):
    unadjusted_date: str | None = Field(None, alias="unadjustedDate", description="A date subject to adjustment.")
    date_adjustments: cdm_base_datetime_BusinessDayAdjustments_schema.BusinessDayAdjustments | None = Field(
        None,
        alias="dateAdjustments",
        description="The business day convention and financial business centers used for adjusting the date if it would otherwise fall on a day that is not a business date in the specified business centers.",
    )
    adjusted_date: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None = Field(
        None,
        alias="adjustedDate",
        description="The date once the adjustment has been performed. (Note that this date may change if the business center holidays change).",
    )
    relative_date: cdm_base_datetime_RelativeDateOffset_schema.RelativeDateOffset | None = Field(
        None, alias="relativeDate", description="A date specified as some offset to another date (the anchor date)."
    )
