# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-PartyDeterminationEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class PartyDeterminationEnum(StrEnum):
    AS_SPECIFIED_IN_MASTER_AGREEMENT = "AsSpecifiedInMasterAgreement"
    AS_SPECIFIED_IN_STANDARD_TERMS_SUPPLEMENT = "AsSpecifiedInStandardTermsSupplement"
    BOTH = "Both"
    EXERCISING_PARTY = "ExercisingParty"
    NON_EXERCISING_PARTY = "NonExercisingParty"
