# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-ListingSector.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import com_rosetta_model_metafields_FieldWithMetaString_schema


class ListingSector(BaseModel):
    sector: list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None = Field(
        None,
        description="Represents a filter based on an industry sector defined under a system for classifying industry types such as Global Industry Classification Standard (GICS) and North American Industry Classification System (NAICS)",
        min_length=1,
    )
