# generated by datamodel-codegen:
#   filename:  cdm-event-workflow-Workflow.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_event_workflow_WorkflowStep_schema


class Workflow(BaseModel):
    steps: list[cdm_event_workflow_WorkflowStep_schema.WorkflowStep] | None = Field(None, min_length=1)
