# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CollateralValuationAgentElection.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_CounterpartyRoleEnum_schema


class CollateralValuationAgentElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(..., description="The elective party.")
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
