# generated by datamodel-codegen:
#   filename:  cdm-product-asset-ProtectionTerms.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_credit_Obligations_schema,
    cdm_observable_event_CreditEvents_schema,
    cdm_product_asset_FloatingAmountEvents_schema,
)


class ProtectionTerms(BaseModel):
    credit_events: cdm_observable_event_CreditEvents_schema.CreditEvents | None = Field(
        None,
        alias="creditEvents",
        description="Specifies the applicable Credit Events that would trigger a settlement, as specified in the related Confirmation and defined in the ISDA 2014 Credit Definition article IV section 4.1.",
    )
    obligations: cdm_base_staticdata_asset_credit_Obligations_schema.Obligations | None = Field(
        None,
        description="The underlying obligations of the reference entity on which you are buying or selling protection. The credit events Failure to Pay, Obligation Acceleration, Obligation Default, Restructuring, Repudiation/Moratorium are defined with respect to these obligations.",
    )
    floating_amount_events: (
        cdm_product_asset_FloatingAmountEvents_schema.FloatingAmountEvents | None
    ) = Field(
        None,
        alias="floatingAmountEvents",
        description="This element contains the ISDA terms relating to the floating rate payment events and the implied additional fixed payments, applicable to the credit derivatives transactions on mortgage-backed securities with pay-as-you-go or physical settlement.",
    )
