# generated by datamodel-codegen:
#   filename:  cdm-event-common-ExecutionTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ExecutionTypeEnum(StrEnum):
    ELECTRONIC = "Electronic"
    OFF_FACILITY = "OffFacility"
    ON_VENUE = "OnVenue"
