# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-PriceOperandEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class PriceOperandEnum(StrEnum):
    ACCRUED_INTEREST = "AccruedInterest"
    COMMISSION = "Commission"
    FORWARD_POINT = "ForwardPoint"
