# generated by datamodel-codegen:
#   filename:  cdm-product-template-Barrier.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_event_TriggerEvent_schema


class Barrier(BaseModel):
    barrier_cap: list[cdm_observable_event_TriggerEvent_schema.TriggerEvent] | None = Field(
        None, alias="barrierCap", description="A trigger level approached from beneath.", min_length=0
    )
    barrier_floor: list[cdm_observable_event_TriggerEvent_schema.TriggerEvent] | None = Field(
        None, alias="barrierFloor", description="A trigger level approached from above.", min_length=0
    )
