# generated by datamodel-codegen:
#   filename:  cdm-product-template-Asian.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_common_schedule_AveragingPeriod_schema, cdm_product_template_AveragingInOutEnum_schema


class Asian(BaseModel):
    averaging_in_out: cdm_product_template_AveragingInOutEnum_schema.AveragingInOutEnum = Field(
        ..., alias="averagingInOut"
    )
    strike_factor: float | None = Field(None, alias="strikeFactor", description="The factor of strike.")
    averaging_period_in: cdm_product_common_schedule_AveragingPeriod_schema.AveragingPeriod | None = Field(
        None, alias="averagingPeriodIn", description="The averaging in period."
    )
    averaging_period_out: cdm_product_common_schedule_AveragingPeriod_schema.AveragingPeriod | None = Field(
        None, alias="averagingPeriodOut", description="The averaging out period."
    )
