# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SimmExceptionApplicableEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class SimmExceptionApplicableEnum(StrEnum):
    fall_back_to_mandatory_method = "FallBackToMandatoryMethod"
    mandatory_method = "MandatoryMethod"
    other_method = "OtherMethod"
