# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-AssetTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AssetTypeEnum(StrEnum):
    CASH = "Cash"
    COMMODITY = "Commodity"
    OTHER = "Other"
    SECURITY = "Security"
