# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-ContactInformation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_Address_schema,
    cdm_base_staticdata_party_TelephoneNumber_schema,
)


class ContactInformation(BaseModel):
    telephone: list[cdm_base_staticdata_party_TelephoneNumber_schema.TelephoneNumber] | None = (
        Field(None, description="The telephone number.", min_length=0)
    )
    address: list[cdm_base_staticdata_party_Address_schema.Address] | None = Field(
        None, description="The street/postal address.", min_length=0
    )
    email: list[str] | None = Field(None, description="The email address.", min_length=0)
    web_page: list[str] | None = Field(
        None,
        alias="webPage",
        description="The web page. This attribute is not specified as part of the FpML ContactInformation complex type.",
        min_length=0,
    )
