# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-DateRelativeToPaymentDates.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_product_common_schedule_metafields_ReferenceWithMetaPaymentDates_schema


class DateRelativeToPaymentDates(BaseModel):
    payment_dates_reference: (
        list[cdm_product_common_schedule_metafields_ReferenceWithMetaPaymentDates_schema.ReferenceWithMetaPaymentDates] | None
    ) = Field(
        None,
        alias="paymentDatesReference",
        description="A set of href pointers to payment dates defined somewhere else in the document.",
        min_length=1,
    )
