# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-ValuationSource.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_AncillaryEntity_schema,
    cdm_base_staticdata_party_ReferenceBanks_schema,
    cdm_observable_asset_FxSpotRateSource_schema,
    cdm_observable_asset_SettlementRateOption_schema,
    cdm_observable_asset_metafields_ReferenceWithMetaQuotedCurrencyPair_schema,
)


class ValuationSource(BaseModel):
    quoted_currency_pair: (
        cdm_observable_asset_metafields_ReferenceWithMetaQuotedCurrencyPair_schema.ReferenceWithMetaQuotedCurrencyPair
        | None
    ) = Field(
        None,
        alias="quotedCurrencyPair",
        description="Defines the two currencies for an FX trade and the quotation relationship between the two currencies.  This attribute was formerly part of 'fxSettlementTerms', which is now being harmonised into a common 'CashSettlementTerms' that includes a 'ValuationDate'.",
    )
    information_source: cdm_observable_asset_FxSpotRateSource_schema.FxSpotRateSource | None = (
        Field(
            None,
            alias="informationSource",
            description="The information source where a published or displayed market rate will be obtained, e.g. Telerate Page 3750.",
        )
    )
    settlement_rate_option: (
        cdm_observable_asset_SettlementRateOption_schema.SettlementRateOption | None
    ) = Field(
        None,
        alias="settlementRateOption",
        description="The rate option to use for the fixing. Currently only applicable to foreign exchange fixing in case of cross-currency settlement.",
    )
    reference_banks: cdm_base_staticdata_party_ReferenceBanks_schema.ReferenceBanks | None = Field(
        None,
        alias="referenceBanks",
        description="A container for a set of reference institutions that may be called upon to provide rate quotations as part of the method to determine the applicable cash settlement amount. If institutions are not specified, it is assumed that reference institutions will be agreed between the parties on the exercise date, or in the case of swap transaction to which mandatory early termination is applicable, the cash settlement valuation date.",
    )
    dealer_or_ccp: cdm_base_staticdata_party_AncillaryEntity_schema.AncillaryEntity | None = Field(
        None,
        alias="dealerOrCCP",
        description="Holds an identifier for the reference entity that is agreed by both parties as a basis for cash settlement calculations. This could be a dealer from whom quotations are obtained by the calculation agent on the reference obligation for purposes of cash settlement in a credit event. ISDA 2003 Term: Dealer. This could be the clearing organization (CCP, DCO) to which the trade should be cleared, as applicable for cash-settled swaptions.",
    )
