# generated by datamodel-codegen:
#   filename:  cdm-product-template-ExtensionEvent.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field


class ExtensionEvent(BaseModel):
    adjusted_exercise_date: str = Field(
        ...,
        alias="adjustedExerciseDate",
        description="The date on which option exercise takes place. This date should already be adjusted for any applicable business day convention.",
    )
    adjusted_extended_termination_date: str = Field(
        ...,
        alias="adjustedExtendedTerminationDate",
        description="The termination date if an extendible provision is exercised. This date should already be adjusted for any applicable business day convention.",
    )
