# generated by datamodel-codegen:
#   filename:  cdm-regulation-FinInstrm.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_regulation_Othr_schema


class FinInstrm(BaseModel):
    othr: cdm_regulation_Othr_schema.Othr
