# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-daycount-metafields-FieldWithMetaDayCountFractionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_base_datetime_daycount_DayCountFractionEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaDayCountFractionEnum(BaseModel):
    value: cdm_base_datetime_daycount_DayCountFractionEnum_schema.DayCountFractionEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
