# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-master-NationalizationOrInsolvencyOrDelistingEventEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class NationalizationOrInsolvencyOrDelistingEventEnum(StrEnum):
    cancellation_and_payment = "CancellationAndPayment"
    negotiated_closeout = "NegotiatedCloseout"
