# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-QuoteBasisEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class QuoteBasisEnum(StrEnum):
    currency1_per_currency2 = "Currency1PerCurrency2"
    currency2_per_currency1 = "Currency2PerCurrency1"
