# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-PrincipalPayment.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableDate_schema,
    cdm_base_staticdata_party_PayerReceiver_schema,
    cdm_observable_asset_Money_schema,
)


class PrincipalPayment(BaseModel):
    principal_payment_date: cdm_base_datetime_AdjustableDate_schema.AdjustableDate | None = Field(
        None, alias="principalPaymentDate", description="The date where the PrincipalPayment shall be settled."
    )
    payer_receiver: cdm_base_staticdata_party_PayerReceiver_schema.PayerReceiver | None = Field(
        None,
        alias="payerReceiver",
        description="Specifies the parties responsible for making and receiving payments defined by this structure.",
    )
    principal_amount: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        alias="principalAmount",
        description="When known at the time the transaction is made, the cash amount to be paid.",
    )
    discount_factor: float | None = Field(
        None,
        alias="discountFactor",
        description="The value representing the discount factor used to calculate the present value of the principal payment amount.",
    )
    present_value_principal_amount: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        alias="presentValuePrincipalAmount",
        description="The amount representing the present value of the principal payment.",
    )
