# generated by datamodel-codegen:
#   filename:  cdm-event-common-CorporateAction.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_CorporateActionTypeEnum_schema
from ._internal_3 import Underlier


class CorporateAction(BaseModel):
    corporate_action_type: cdm_event_common_CorporateActionTypeEnum_schema.CorporateActionTypeEnum = Field(
        ..., alias="corporateActionType", description="The type of corporate action taking place."
    )
    ex_date: str = Field(
        ...,
        alias="exDate",
        description="The date on which the corporate action is known to have taken place.",
    )
    pay_date: str = Field(
        ...,
        alias="payDate",
        description="The date on which resulting from the corporate action are delivered.",
    )
    underlier: Underlier = Field(..., description="The underlier impacted by the corporate action.")
