# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ThresholdRatedPartyEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ThresholdRatedPartyEnum(StrEnum):
    all_affiliates_to_the_party = "All Affiliates to the Party"
    credit_support_provider = "CreditSupportProvider"
    named_affiliate = "NamedAffiliate"
    named_entity = "NamedEntity"
    party = "Party"
    party_or_credit_support_provider = "PartyOrCreditSupportProvider"
