# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-SovereignAgencyRating.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_collateral_AgencyRatingCriteria_schema


class SovereignAgencyRating(BaseModel):
    sovereign_agency_rating: cdm_product_collateral_AgencyRatingCriteria_schema.AgencyRatingCriteria = Field(
        ...,
        alias="sovereignAgencyRating",
        description="Represents an agency rating based on default risk of the country of the issuer.",
    )
