# generated by datamodel-codegen:
#   filename:  cdm-event-common-CreditEvent.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_event_common_CreditEventTypeEnum_schema,
    cdm_legaldocumentation_common_Resource_schema,
    cdm_observable_asset_Price_schema,
    cdm_product_asset_ReferenceInformation_schema,
)


class CreditEvent(BaseModel):
    credit_event_type: cdm_event_common_CreditEventTypeEnum_schema.CreditEventTypeEnum = Field(
        ..., alias="creditEventType", description="The type of credit event taking place."
    )
    event_determination_date: str = Field(
        ...,
        alias="eventDeterminationDate",
        description="The date in which the credit event is determined by the Credit Derivatives Determinations Comitee.",
    )
    auction_date: str | None = Field(
        None, alias="auctionDate", description="The date on which the auction is scheduled to occur."
    )
    final_price: cdm_observable_asset_Price_schema.Price | None = Field(
        None, alias="finalPrice", description="The final price resulting from the auction."
    )
    recovery_percent: float | None = Field(
        None,
        alias="recoveryPercent",
        description="The percentage of the original value of the asset affected by the credit event that can be recovered.",
    )
    publicly_available_information: list[cdm_legaldocumentation_common_Resource_schema.Resource] | None = Field(
        None,
        alias="publiclyAvailableInformation",
        description="A public information source, e.g. a particular newspaper or electronic news service, that may publish relevant information used in the determination of whether or not a credit event has occurred.",
        min_length=0,
    )
    reference_information: cdm_product_asset_ReferenceInformation_schema.ReferenceInformation = Field(
        ...,
        alias="referenceInformation",
        description="The reference entity, part of a credit basket, impacted by the credit event.",
    )
