# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-EU_EMIR_EligibleCollateralEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class EUEMIREligibleCollateralEnum(StrEnum):
    EU_EMIR_TYPE_A = "EU_EMIRTypeA"
    EU_EMIR_TYPE_B = "EU_EMIRTypeB"
    EU_EMIR_TYPE_C = "EU_EMIRTypeC"
    EU_EMIR_TYPE_D = "EU_EMIRTypeD"
    EU_EMIR_TYPE_E = "EU_EMIRTypeE"
    EU_EMIR_TYPE_F = "EU_EMIRTypeF"
    EU_EMIR_TYPE_G = "EU_EMIRTypeG"
    EU_EMIR_TYPE_H = "EU_EMIRTypeH"
    EU_EMIR_TYPE_I = "EU_EMIRTypeI"
    EU_EMIR_TYPE_J = "EU_EMIRTypeJ"
    EU_EMIR_TYPE_K = "EU_EMIRTypeK"
    EU_EMIR_TYPE_L = "EU_EMIRTypeL"
    EU_EMIR_TYPE_M = "EU_EMIRTypeM"
    EU_EMIR_TYPE_N = "EU_EMIRTypeN"
    EU_EMIR_TYPE_O = "EU_EMIRTypeO"
    EU_EMIR_TYPE_P = "EU_EMIRTypeP"
    EU_EMIR_TYPE_Q = "EU_EMIRTypeQ"
    EU_EMIR_TYPE_R = "EU_EMIRTypeR"
