# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-master-NationalizationOrInsolvencyOrDelistingEventEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class NationalizationOrInsolvencyOrDelistingEventEnum(StrEnum):
    CANCELLATION_AND_PAYMENT = "CancellationAndPayment"
    NEGOTIATED_CLOSEOUT = "NegotiatedCloseout"
