# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-ValuationDates.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_PerformanceValuationDates_schema


class ValuationDates(BaseModel):
    initial_valuation_date: cdm_observable_asset_PerformanceValuationDates_schema.PerformanceValuationDates | None = (
        Field(None, alias="initialValuationDate", description="Specifies the initial valuation dates of the underlyer.")
    )
    interim_valuation_date: cdm_observable_asset_PerformanceValuationDates_schema.PerformanceValuationDates | None = (
        Field(None, alias="interimValuationDate", description="Specifies the interim valuation dates of the underlyer.")
    )
    final_valuation_date: cdm_observable_asset_PerformanceValuationDates_schema.PerformanceValuationDates = Field(
        ..., alias="finalValuationDate", description="Specifies the final valuation dates of the underlyer."
    )
