# generated by datamodel-codegen:
#   filename:  cdm-observable-event-metafields-FieldWithMetaRestructuringEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import (
    cdm_observable_event_RestructuringEnum_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class FieldWithMetaRestructuringEnum(BaseModel):
    value: cdm_observable_event_RestructuringEnum_schema.RestructuringEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
