# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-PaymentDetail.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableOrRelativeDate_schema,
    cdm_observable_asset_Money_schema,
    cdm_product_common_settlement_PaymentRule_schema,
)


class PaymentDetail(BaseModel):
    payment_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None, alias="paymentDate"
    )
    payment_rule: cdm_product_common_settlement_PaymentRule_schema.PaymentRule = Field(
        ..., alias="paymentRule", description="The calculation rule."
    )
    payment_amount: cdm_observable_asset_Money_schema.Money | None = Field(
        None, alias="paymentAmount", description="A fixed payment amount."
    )
