# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-FeeTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class FeeTypeEnum(StrEnum):
    assignment = "Assignment"
    brokerage_commission = "BrokerageCommission"
    corporate_action = "CorporateAction"
    credit_event = "CreditEvent"
    increase = "Increase"
    novation = "Novation"
    partial_termination = "PartialTermination"
    premium = "Premium"
    renegotiation = "Renegotiation"
    termination = "Termination"
    upfront = "Upfront"
