# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-ProductIdTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ProductIdTypeEnum(StrEnum):
    BBGID = "BBGID"
    BBGTICKER = "BBGTICKER"
    CUSIP = "CUSIP"
    FIGI = "FIGI"
    ISDACRP = "ISDACRP"
    ISIN = "ISIN"
    NAME = "Name"
    OTHER = "Other"
    REDID = "REDID"
    RIC = "RIC"
    SEDOL = "SEDOL"
    SICOVAM = "Sicovam"
    UPI = "UPI"
    VALOREN = "Valoren"
    WERTPAPIER = "Wertpapier"
