# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-BespokeCalculationTime.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field


class BespokeCalculationTime(BaseModel):
    as_calculation_agent: bool = Field(
        ...,
        alias="asCalculationAgent",
        description="If set to True, the Calculation Time for Initial Margin is the time as of which the Calculation Agent (IM) computes its end of day valuations of derivatives transactions.",
    )
    bespoke_calculation_time_terms: str | None = Field(
        None, alias="bespokeCalculationTimeTerms", description="Additional Terms applicable to Calculation Time for Initial Margin."
    )
