# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CreditSupportObligations.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_csa_BespokeTransferTiming_schema,
    cdm_legaldocumentation_csa_CSAMinimumTransferAmount_schema,
    cdm_legaldocumentation_csa_CSAThreshold_schema,
    cdm_legaldocumentation_csa_CollateralRounding_schema,
    cdm_legaldocumentation_csa_CollateralTransferTiming_schema,
    cdm_legaldocumentation_csa_CreditSupportAmount_schema,
    cdm_legaldocumentation_csa_CreditSupportObligationsVariationMargin_schema,
    cdm_legaldocumentation_csa_LegacyDeliveryAmount_schema,
    cdm_legaldocumentation_csa_LegacyReturnAmount_schema,
    cdm_legaldocumentation_csa_MarginApproach_schema,
    cdm_legaldocumentation_csa_MinimumTransferAmount_schema,
    cdm_legaldocumentation_csa_Threshold_schema,
)


class CreditSupportObligations(BaseModel):
    delivery_amount: str | None = Field(
        None,
        alias="deliveryAmount",
        description="Delivery Amount (VM) has the meaning specified in Paragraph 3(a), unless otherwise specified here.",
    )
    return_amount: str | None = Field(
        None,
        alias="returnAmount",
        description="Return Amount (VM) has the meaning specified in Paragraph 3(a), unless otherwise specified here.",
    )
    margin_approach: cdm_legaldocumentation_csa_MarginApproach_schema.MarginApproach | None = Field(
        None, alias="marginApproach", description="The selection of Margin Approach applicable to the agreement."
    )
    other_eligible_support: str | None = Field(
        None,
        alias="otherEligibleSupport",
        description="The Other Eligible Support election. If not specified, this election is deemed as not applicable.",
    )
    threshold: cdm_legaldocumentation_csa_Threshold_schema.Threshold = Field(
        ...,
        description="The amount of net exposure that a party is willing to bear in relation to the other party before it requires asking for collateral.",
    )
    minimum_transfer_amount: cdm_legaldocumentation_csa_MinimumTransferAmount_schema.MinimumTransferAmount = Field(
        ..., alias="minimumTransferAmount", description="The net amount of exposure reached before collateral has to be posted or returned."
    )
    rounding: cdm_legaldocumentation_csa_CollateralRounding_schema.CollateralRounding | None = Field(
        None,
        description="The rounding methodology applicable to the Delivery Amount and the Return Amount in terms of nearest integral multiple of Base Currency units.",
    )
    bespoke_transfer_timing: cdm_legaldocumentation_csa_BespokeTransferTiming_schema.BespokeTransferTiming | None = Field(
        None,
        alias="bespokeTransferTiming",
        description="The time by which the transfer of collateral must take place when different from the Regular Settlement Day as a result of parties' election.",
    )
    credit_support_obligations_variation_margin: (
        cdm_legaldocumentation_csa_CreditSupportObligationsVariationMargin_schema.CreditSupportObligationsVariationMargin | None
    ) = Field(
        None,
        alias="creditSupportObligationsVariationMargin",
        description="The specification of Credit Support Obligations applicable to Variation Margin agreements.",
    )
    legacy_threshold: list[cdm_legaldocumentation_csa_CSAThreshold_schema.CSAThreshold] | None = Field(
        None, alias="legacyThreshold", max_length=2, min_length=0
    )
    legacy_minimum_transfer_amount: list[cdm_legaldocumentation_csa_CSAMinimumTransferAmount_schema.CSAMinimumTransferAmount] | None = (
        Field(None, alias="legacyMinimumTransferAmount", max_length=2, min_length=0)
    )
    legacy_delivery_amount: cdm_legaldocumentation_csa_LegacyDeliveryAmount_schema.LegacyDeliveryAmount = Field(
        ...,
        alias="legacyDeliveryAmount",
        description="In respect of a Valuation Date, the amount of collateral which a party is entitled to demand to be transferred to it as a Delivery Amount.",
    )
    legacy_return_amount: cdm_legaldocumentation_csa_LegacyReturnAmount_schema.LegacyReturnAmount = Field(
        ...,
        alias="legacyReturnAmount",
        description="In respect of a Valuation Date, the amount of collateral which a party is entitled to demand to be recalled to it as a Return Amount.",
    )
    credit_support_amount: cdm_legaldocumentation_csa_CreditSupportAmount_schema.CreditSupportAmount = Field(
        ...,
        alias="creditSupportAmount",
        description="The total amount one counterparty must deliver to the other at any time: the combination of the Exposure to that party and the net Independent Amounts it must post, minus any agreed Threshold.",
    )
    collateral_transfer_timing: cdm_legaldocumentation_csa_CollateralTransferTiming_schema.CollateralTransferTiming | None = Field(
        None,
        alias="collateralTransferTiming",
        description="Specification of transfer / settlement timing for cash and securities collateral assuming that the notice is provided before the Notification Time (and with a 1LBD lag introduced if the notice is delivered after the Notification Time), and that securities allow for a further Local Business Day for transfer / settlement.",
    )
