# generated by datamodel-codegen:
#   filename:  cdm-product-template-OptionExerciseStyleEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class OptionExerciseStyleEnum(StrEnum):
    AMERICAN = "American"
    BERMUDA = "Bermuda"
    EUROPEAN = "European"
