# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-TerminationCurrencyElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class TerminationCurrencyElection(BaseModel):
    party: (
        list[cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum] | None
    ) = Field(None, description="The elective party.", max_length=2, min_length=1)
    is_specified: bool = Field(
        ...,
        alias="isSpecified",
        description="The qualification of whether the Termination Currency is specified in this document (True) or in an Eligible Support Credit Support (IM) Schedule (False).",
    )
    currency: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None = (
        Field(
            None,
            description="The Termination Currency associated with the party that referenced as part of this class. The list of valid currencies is not presently positioned as an enumeration as part of the CDM because that scope is limited to the values specified by ISDA and FpML. As a result, implementers have to make reference to the relevant standard, such as the ISO 4217 standard for currency codes.",
        )
    )
