# generated by datamodel-codegen:
#   filename:  cdm-event-common-CorporateActionTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CorporateActionTypeEnum(StrEnum):
    bonus_issue = "BonusIssue"
    cash_dividend = "CashDividend"
    class_action = "ClassAction"
    delisting = "Delisting"
    early_redemption = "EarlyRedemption"
    liquidation = "Liquidation"
    merger = "Merger"
    reverse_stock_split = "ReverseStockSplit"
    rights_issue = "RightsIssue"
    spin_off = "SpinOff"
    stock_dividend = "StockDividend"
    stock_identifier_change = "StockIdentifierChange"
    stock_name_change = "StockNameChange"
    stock_reclassification = "StockReclassification"
    stock_split = "StockSplit"
    takeover = "Takeover"
