# generated by datamodel-codegen:
#   filename:  cdm-regulation-Indx.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_regulation_Nm_schema


class Indx(BaseModel):
    nm: cdm_regulation_Nm_schema.Nm
