# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CalculationDateLocation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_CalculationDateLocationElection_schema


class CalculationDateLocation(BaseModel):
    party_election: (
        list[
            cdm_legaldocumentation_csa_CalculationDateLocationElection_schema.CalculationDateLocationElection
        ]
        | None
    ) = Field(
        None,
        alias="partyElection",
        description="The parties' calculation date location election.",
        max_length=2,
        min_length=2,
    )
