# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyVMCustodianEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class LegacyVMCustodianEnum(StrEnum):
    AS_ADVISED_BY_PARTY_1_TO_PARTY_2 = "As advised by Party 1 to Party 2"
    AS_ADVISED_BY_PARTY_2_TO_PARTY_1 = "As advised by Party 2 to Party 1"
    NAMED_ENTITY = "NamedEntity"
    NOT_APPLICABLE = "NotApplicable"
    PARTY_1_WILL_NOTIFY_PARTY_2 = "Party 1 will notify Party 2"
    PARTY_2_WILL_NOTIFY_PARTY_1 = "Party 2 will notify Party 1"
