# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-Loan.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_AssetIdentifier_schema,
    cdm_base_staticdata_asset_common_InstrumentTypeEnum_schema,
    cdm_base_staticdata_asset_common_Taxonomy_schema,
    cdm_base_staticdata_party_LegalEntity_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class Loan(BaseModel):
    identifier: (
        list[cdm_base_staticdata_asset_common_AssetIdentifier_schema.AssetIdentifier] | None
    ) = Field(
        None,
        description="Asset Identifiers are used to uniquely identify an Asset, using a specified Asset Identifier Type.",
        min_length=1,
    )
    taxonomy: list[cdm_base_staticdata_asset_common_Taxonomy_schema.Taxonomy] | None = Field(
        None,
        description="Defines the taxonomy of an object by combining a taxonomy source (i.e. the rules to classify the object) and a value (i.e. the output of those rules on the object.",
        min_length=0,
    )
    is_exchange_listed: bool | None = Field(
        None,
        alias="isExchangeListed",
        description="Defines whether the Asset is listed on a public exchange.",
    )
    exchange: cdm_base_staticdata_party_LegalEntity_schema.LegalEntity | None = Field(
        None, description="If the Asset is listed, defines the public exchange of the listing."
    )
    related_exchange: list[cdm_base_staticdata_party_LegalEntity_schema.LegalEntity] | None = Field(
        None,
        alias="relatedExchange",
        description="Provides the related Exchanges, if applicable.",
        min_length=0,
    )
    instrument_type: (
        cdm_base_staticdata_asset_common_InstrumentTypeEnum_schema.InstrumentTypeEnum | None
    ) = Field(
        None,
        alias="instrumentType",
        description="Identifies the type of an instrument using an enumerated list.",
    )
    borrower: list[cdm_base_staticdata_party_LegalEntity_schema.LegalEntity] | None = Field(
        None,
        description="Specifies the borrower. There can be more than one borrower. It is meant to be used in the event that there is no Bloomberg Id or the Secured List isn't applicable.",
        min_length=0,
    )
    lien: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None = (
        Field(None, description="Specifies the seniority level of the lien.")
    )
    facility_type: (
        com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None
    ) = Field(
        None,
        alias="facilityType",
        description="Specifies the type of loan facility (letter of credit, revolving, ...).",
    )
    credit_agreement_date: str | None = Field(
        None,
        alias="creditAgreementDate",
        description="Specifies the credit agreement date is the closing date (the date where the agreement has been signed) for the loans in the credit agreement. Funding of the facilities occurs on (or sometimes a little after) the Credit Agreement date. This underlier attribute is used to help identify which of the company's outstanding loans are being referenced by knowing to which credit agreement it belongs. ISDA Standards Terms Supplement term: Date of Original Credit Agreement.",
    )
    tranche: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None = (
        Field(
            None,
            description="Denotes the loan tranche that is subject to the derivative transaction. It will typically be referenced as the Bloomberg tranche number. ISDA Standards Terms Supplement term: Bloomberg Tranche Number.",
        )
    )
