# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-DateList.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class DateList(BaseModel):
    date: list[str] | None = Field(None, min_length=1)
