# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-AssetType.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_AssetTypeEnum_schema,
    cdm_base_staticdata_asset_common_DebtType_schema,
    cdm_base_staticdata_asset_common_EquityTypeEnum_schema,
    cdm_base_staticdata_asset_common_FundProductTypeEnum_schema,
    cdm_base_staticdata_asset_common_InstrumentTypeEnum_schema,
)


class AssetType(BaseModel):
    asset_type: cdm_base_staticdata_asset_common_AssetTypeEnum_schema.AssetTypeEnum = Field(
        ...,
        alias="assetType",
        description="Represents a filter based on the type of collateral asset.",
    )
    security_type: (
        cdm_base_staticdata_asset_common_InstrumentTypeEnum_schema.InstrumentTypeEnum | None
    ) = Field(
        None, alias="securityType", description="Represents a filter based on the type of security."
    )
    debt_type: cdm_base_staticdata_asset_common_DebtType_schema.DebtType | None = Field(
        None, alias="debtType", description="Represents a filter based on the type of bond."
    )
    equity_type: cdm_base_staticdata_asset_common_EquityTypeEnum_schema.EquityTypeEnum | None = (
        Field(
            None, alias="equityType", description="Represents a filter based on the type of equity."
        )
    )
    fund_type: (
        cdm_base_staticdata_asset_common_FundProductTypeEnum_schema.FundProductTypeEnum | None
    ) = Field(None, alias="fundType", description="Represents a filter based on the type of fund.")
    other_asset_type: list[str] | None = Field(
        None,
        alias="otherAssetType",
        description="Specifies the eligible asset type when not enumerated.",
        min_length=0,
    )
