# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-InformationProviderEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class InformationProviderEnum(StrEnum):
    assoc_banks_singapore = "AssocBanksSingapore"
    banco_central_chile = "BancoCentralChile"
    bank_of_canada = "BankOfCanada"
    bank_of_england = "BankOfEngland"
    bank_of_japan = "BankOfJapan"
    bloomberg = "Bloomberg"
    euro_central_bank = "EuroCentralBank"
    fhlbsf = "FHLBSF"
    federal_reserve = "FederalReserve"
    iceswap = "ICESWAP"
    isda = "ISDA"
    refinitiv = "Refinitiv"
    reserve_bank_australia = "ReserveBankAustralia"
    reserve_bank_new_zealand = "ReserveBankNewZealand"
    reuters = "Reuters"
    safex = "SAFEX"
    tokyoswap = "TOKYOSWAP"
    telerate = "Telerate"
