# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-CashSettlementMethodEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CashSettlementMethodEnum(StrEnum):
    cash_price_alternate_method = "CashPriceAlternateMethod"
    cash_price_method = "CashPriceMethod"
    collateralized_cash_price_method = "CollateralizedCashPriceMethod"
    cross_currency_method = "CrossCurrencyMethod"
    mid_market_calculation_agent_determination = "MidMarketCalculationAgentDetermination"
    mid_market_indicative_quotations = "MidMarketIndicativeQuotations"
    mid_market_indicative_quotations_alternate = "MidMarketIndicativeQuotationsAlternate"
    par_yield_curve_adjusted_method = "ParYieldCurveAdjustedMethod"
    par_yield_curve_unadjusted_method = "ParYieldCurveUnadjustedMethod"
    replacement_value_calculation_agent_determination = "ReplacementValueCalculationAgentDetermination"
    replacement_value_firm_quotations = "ReplacementValueFirmQuotations"
    zero_coupon_yield_adjusted_method = "ZeroCouponYieldAdjustedMethod"
