# generated by datamodel-codegen:
#   filename:  cdm-product-asset-VolatilityCapFloor.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class VolatilityCapFloor(BaseModel):
    applicable: bool = Field(
        ...,
        description="Indicates whether the volatility cap is applicable in accordance with the ISDA 2011 Equity Derivatives Definitions. Setting the element 'applicable' to 'False' - means No Volatility Cap and no 'totalVolatilityCap' or 'volatilityCapFactor' should be provided. Setting the element 'applicable' to 'True' - means Volatility Cap election, then 'totalVolatilityCap' or 'volatilityCapFactor' should be provided, otherwise it defaults to volatilityCapFactor=2.5.",
    )
    total_volatility_cap: float | None = Field(
        None,
        alias="totalVolatilityCap",
        description="Volatility Cap Amount in accordance with the ISDA 2011 Equity Derivatives Definitions. This means the Volatility Cap Amount election is a number.",
    )
    volatility_cap_factor: float | None = Field(
        None,
        alias="volatilityCapFactor",
        description="Volatility Cap Amount in accordance with the ISDA 2011 Equity Derivatives Definitions. The Calculated VolCapAmt can be optionally provided.",
    )
