# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-ReferenceBanks.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_ReferenceBank_schema


class ReferenceBanks(BaseModel):
    reference_bank: list[cdm_base_staticdata_party_ReferenceBank_schema.ReferenceBank] | None = Field(
        None,
        alias="referenceBank",
        description="An institution (party) identified by means of a coding scheme and an optional name.",
        min_length=1,
    )
