# generated by datamodel-codegen:
#   filename:  cdm-event-common-BusinessEvent.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_identifier_IdentifiedList_schema,
    cdm_event_common_CorporateActionTypeEnum_schema,
    cdm_event_common_EventIntentEnum_schema,
    cdm_event_common_Instruction_schema,
    cdm_event_common_TradeState_schema,
)


class BusinessEvent(BaseModel):
    intent: cdm_event_common_EventIntentEnum_schema.EventIntentEnum | None = Field(
        None,
        description="The intent attribute is meant to be specified when the event qualification cannot be programmatically inferred from the event features. As a result it is only associated with those primitives that can give way to such ambiguity, the quantityChange being one of those. An example of such is a reduction in the trade notional, which could be interpreted as either a trade correction (unless a maximum period of time post-event is specified as part of the qualification), a partial termination or a portfolio rebalancing in the case of an equity swap. On the other hand, an event such as the exercise is not expected to have an associated intent as there should not be ambiguity.",
    )
    corporate_action_intent: (
        cdm_event_common_CorporateActionTypeEnum_schema.CorporateActionTypeEnum | None
    ) = Field(None, alias="corporateActionIntent")
    event_date: str | None = Field(
        None,
        alias="eventDate",
        description="Specifies the date on which the event is taking place. This date is equal to the trade date in the case of a simple execution.  However it can be different from the trade date, for example in the case of a partial termination.",
    )
    effective_date: str | None = Field(
        None,
        alias="effectiveDate",
        description="The date on which the event contractually takes effect, when different from the event date.",
    )
    package_information: (
        cdm_base_staticdata_identifier_IdentifiedList_schema.IdentifiedList | None
    ) = Field(
        None,
        alias="packageInformation",
        description="Specifies the package information in case the business event represents several trades executed as a package (hence this attribute is optional). The package information is only instantiated once at the business event level to preserve referential integrity, whereas individual trades make reference to it to identify that they are part of a package.",
    )
    instruction: list[cdm_event_common_Instruction_schema.Instruction] | None = Field(
        None, description="Specifies the instructions to create the Business Event.", min_length=0
    )
    event_qualifier: str | None = Field(
        None,
        alias="eventQualifier",
        description="The CDM event qualifier, which corresponds to the outcome of the isEvent qualification logic which qualifies the lifecycle event as a function of its features (e.g. PartialTermination, ClearingSubmission, Novation, ...).",
    )
    after: list[cdm_event_common_TradeState_schema.TradeState] | None = Field(
        None, description="Specifies the after trade state(s) created.", min_length=0
    )
