# generated by datamodel-codegen:
#   filename:  cdm-product-asset-DividendAmountTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class DividendAmountTypeEnum(StrEnum):
    AS_SPECIFIED_IN_MASTER_CONFIRMATION = "AsSpecifiedInMasterConfirmation"
    EX_AMOUNT = "ExAmount"
    PAID_AMOUNT = "PaidAmount"
    RECORD_AMOUNT = "RecordAmount"
