# generated by datamodel-codegen:
#   filename:  cdm-observable-event-TriggerTimeTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class TriggerTimeTypeEnum(StrEnum):
    ANYTIME = "Anytime"
    CLOSING = "Closing"
