# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-FxRate.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_QuotedCurrencyPair_schema


class FxRate(BaseModel):
    quoted_currency_pair: cdm_observable_asset_QuotedCurrencyPair_schema.QuotedCurrencyPair = Field(
        ...,
        alias="quotedCurrencyPair",
        description="Defines the two currencies for an FX trade and the quotation relationship between the two currencies.",
    )
    rate: float | None = Field(
        None, description="The rate of exchange between the two currencies of the leg of a deal. Must be specified with a quote basis."
    )
