# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-CollateralTaxonomy.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_CollateralTaxonomyValue_schema,
    cdm_base_staticdata_asset_common_TaxonomySourceEnum_schema,
)


class CollateralTaxonomy(BaseModel):
    taxonomy_value: cdm_base_staticdata_asset_common_CollateralTaxonomyValue_schema.CollateralTaxonomyValue = Field(
        ..., alias="taxonomyValue", description="Specifies the taxonomy value."
    )
    taxonomy_source: cdm_base_staticdata_asset_common_TaxonomySourceEnum_schema.TaxonomySourceEnum = Field(
        ..., alias="taxonomySource", description="Specifies the taxonomy source."
    )
