# generated by datamodel-codegen:
#   filename:  cdm-product-template-ExercisePeriod.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_Period_schema


class ExercisePeriod(BaseModel):
    earliest_exercise_date_tenor: cdm_base_datetime_Period_schema.Period = Field(
        ...,
        alias="earliestExerciseDateTenor",
        description="The time interval to the first (and possibly only) exercise date in the exercise period.",
    )
    exercise_frequency: cdm_base_datetime_Period_schema.Period | None = Field(
        None,
        alias="exerciseFrequency",
        description="The frequency of subsequent exercise dates in the exercise period following the earliest exercise date. An interval of 1 day should be used to indicate an American style exercise period.",
    )
