# generated by datamodel-codegen:
#   filename:  cdm-product-asset-SettledEntityMatrix.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_product_asset_metafields_FieldWithMetaSettledEntityMatrixSourceEnum_schema


class SettledEntityMatrix(BaseModel):
    matrix_source: cdm_product_asset_metafields_FieldWithMetaSettledEntityMatrixSourceEnum_schema.FieldWithMetaSettledEntityMatrixSourceEnum = Field(
        ..., alias="matrixSource", description="Relevant settled entity matrix source."
    )
    publication_date: str | None = Field(
        None,
        alias="publicationDate",
        description="Specifies the publication date of the applicable version of the matrix. When this element is omitted, the Standard Terms Supplement defines rules for which version of the matrix is applicable.",
    )
