# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-ResetRelativeToEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ResetRelativeToEnum(StrEnum):
    calculation_period_end_date = "CalculationPeriodEndDate"
    calculation_period_start_date = "CalculationPeriodStartDate"
