# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-CustomisableOffset.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_Offset_schema


class CustomisableOffset(BaseModel):
    offset: cdm_base_datetime_Offset_schema.Offset | None = None
    custom_provision: str | None = Field(None, alias="customProvision")
