# generated by datamodel-codegen:
#   filename:  cdm-event-common-Valuation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_event_common_PriceTimingEnum_schema,
    cdm_event_common_ValuationSourceEnum_schema,
    cdm_event_common_ValuationTypeEnum_schema,
    cdm_observable_asset_Money_schema,
    cdm_observable_asset_Price_schema,
)


class Valuation(BaseModel):
    amount: cdm_observable_asset_Money_schema.Money = Field(
        ..., description="Current value of the outstanding contract"
    )
    timestamp: str = Field(
        ...,
        description="Date and time of the last valuation marked to market, provided by the central counterparty (CCP) or calculated using the current or last available market price of the inputs.",
    )
    method: cdm_event_common_ValuationTypeEnum_schema.ValuationTypeEnum | None = Field(
        None, description="Method used for the valuation of the transaction by the valuation party."
    )
    source: cdm_event_common_ValuationSourceEnum_schema.ValuationSourceEnum | None = Field(
        None, description="Source of the valuation of the transaction by the valuation party."
    )
    delta: float | None = Field(
        None,
        description="The ratio of the change in the price of a derivative transaction to the change in the price of the underlying. This field is applicable only to options and swaptions.",
    )
    valuation_timing: cdm_event_common_PriceTimingEnum_schema.PriceTimingEnum | None = Field(
        None,
        alias="valuationTiming",
        description="Denotes when the valuation was sourced during a business day.",
    )
    price_component: cdm_observable_asset_Price_schema.Price | None = Field(
        None, alias="priceComponent", description="Denotes the price used to compute the valuation."
    )
