# generated by datamodel-codegen:
#   filename:  cdm-product-template-ExerciseFee.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_RelativeDateOffset_schema,
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_observable_asset_metafields_ReferenceWithMetaMoney_schema,
)


class ExerciseFee(BaseModel):
    payer: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = (
        Field(
            None,
            description="Specifies the counterparty responsible for making the payments defined by this structure.  The party is one of the two principal parties to the transaction.",
        )
    )
    receiver: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = (
        Field(
            None,
            description="Specifies the party that receives the payments corresponding to this structure.  The party is one of the two counterparties to the transaction.",
        )
    )
    notional_reference: cdm_observable_asset_metafields_ReferenceWithMetaMoney_schema.ReferenceWithMetaMoney = Field(
        ...,
        alias="notionalReference",
        description="A pointer style reference to the associated notional schedule defined elsewhere in the document.",
    )
    fee_amount: float | None = Field(
        None,
        alias="feeAmount",
        description="The amount of fee to be paid on exercise. The fee currency is that of the referenced notional.",
    )
    fee_rate: float | None = Field(
        None,
        alias="feeRate",
        description="A fee represented as a percentage of some referenced notional. A percentage of 5% would be represented as 0.05.",
    )
    fee_payment_date: cdm_base_datetime_RelativeDateOffset_schema.RelativeDateOffset = Field(
        ...,
        alias="feePaymentDate",
        description="The date on which exercise fee(s) will be paid. It is specified as a relative date.",
    )
