# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-InitialFixingDate.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_RelativeDateOffset_schema


class InitialFixingDate(BaseModel):
    relative_date_offset: cdm_base_datetime_RelativeDateOffset_schema.RelativeDateOffset | None = Field(
        None, alias="relativeDateOffset"
    )
    initial_fixing_date: str | None = Field(None, alias="initialFixingDate")
