# generated by datamodel-codegen:
#   filename:  cdm-event-position-PositionStatusEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class PositionStatusEnum(StrEnum):
    CANCELLED = "Cancelled"
    CLOSED = "Closed"
    EXECUTED = "Executed"
    FORMED = "Formed"
    SETTLED = "Settled"
