# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-NaturalPerson.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_ContactInformation_schema, cdm_base_staticdata_party_metafields_FieldWithMetaPersonIdentifier_schema


class NaturalPerson(BaseModel):
    person_id: list[cdm_base_staticdata_party_metafields_FieldWithMetaPersonIdentifier_schema.FieldWithMetaPersonIdentifier] | None = Field(
        None, alias="personId", description="The identifier associated with a person, e.g. the internal identification code.", min_length=0
    )
    honorific: str | None = Field(None, description="An honorific title, such as Mr., Ms., Dr. etc.")
    first_name: str | None = Field(None, alias="firstName", description="The natural person's first name. It is optional in FpML.")
    middle_name: list[str] | None = Field(
        None,
        alias="middleName",
        description="The natural person's middle name(s). If a middle name is provided then an initial should be absent.",
        min_length=0,
    )
    initial: list[str] | None = Field(
        None,
        description="The natural person's middle initial(s). If a middle initial is provided then a name should be absent.",
        min_length=0,
    )
    surname: str | None = Field(None, description="The natural person's surname.")
    suffix: str | None = Field(None, description="Name suffix, such as Jr., III, etc.")
    date_of_birth: str | None = Field(None, alias="dateOfBirth", description="The natural person's date of birth.")
    contact_information: cdm_base_staticdata_party_ContactInformation_schema.ContactInformation | None = Field(
        None,
        alias="contactInformation",
        description="The contact information for such person, when different from the contact information associated with the party.",
    )
