# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-QuoteBasisEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class QuoteBasisEnum(StrEnum):
    CURRENCY1_PER_CURRENCY2 = "Currency1PerCurrency2"
    CURRENCY2_PER_CURRENCY1 = "Currency2PerCurrency1"
