# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ExceptionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ExceptionEnum(StrEnum):
    APPLICABLE = "Applicable"
    NOT_APPLICABLE = "NotApplicable"
    OTHER = "Other"
