# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-EU_EMIR_EligibleCollateralEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class EUEMIREligibleCollateralEnum(StrEnum):
    eu_emir_type_a = "EU_EMIRTypeA"
    eu_emir_type_b = "EU_EMIRTypeB"
    eu_emir_type_c = "EU_EMIRTypeC"
    eu_emir_type_d = "EU_EMIRTypeD"
    eu_emir_type_e = "EU_EMIRTypeE"
    eu_emir_type_f = "EU_EMIRTypeF"
    eu_emir_type_g = "EU_EMIRTypeG"
    eu_emir_type_h = "EU_EMIRTypeH"
    eu_emir_type_i = "EU_EMIRTypeI"
    eu_emir_type_j = "EU_EMIRTypeJ"
    eu_emir_type_k = "EU_EMIRTypeK"
    eu_emir_type_l = "EU_EMIRTypeL"
    eu_emir_type_m = "EU_EMIRTypeM"
    eu_emir_type_n = "EU_EMIRTypeN"
    eu_emir_type_o = "EU_EMIRTypeO"
    eu_emir_type_p = "EU_EMIRTypeP"
    eu_emir_type_q = "EU_EMIRTypeQ"
    eu_emir_type_r = "EU_EMIRTypeR"
