# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-AdditionalTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AdditionalTypeEnum(StrEnum):
    equity_option_or_index_option = "EquityOptionOrIndexOption"
    not_applicable = "NotApplicable"
    other = "Other"
