# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-ProductTaxonomy.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_TaxonomySourceEnum_schema,
    cdm_base_staticdata_asset_common_TaxonomyValue_schema,
    cdm_base_staticdata_asset_common_metafields_FieldWithMetaAssetClassEnum_schema,
)


class ProductTaxonomy(BaseModel):
    source: cdm_base_staticdata_asset_common_TaxonomySourceEnum_schema.TaxonomySourceEnum | None = Field(
        None,
        description="The source of the taxonomy that defines the rules for classifying the object. The taxonomy source is taken from a enumerated list of taxonomy names. Optional as the taxonomy source may not be provided.",
    )
    value: cdm_base_staticdata_asset_common_TaxonomyValue_schema.TaxonomyValue | None = Field(
        None,
        description="The value according to that taxonomy. Optional as it may not be possible to classify the object in that taxonomy.",
    )
    primary_asset_class: (
        cdm_base_staticdata_asset_common_metafields_FieldWithMetaAssetClassEnum_schema.FieldWithMetaAssetClassEnum | None
    ) = Field(None, alias="primaryAssetClass", description="Classifies the most important risk class of the trade.")
    secondary_asset_class: (
        list[cdm_base_staticdata_asset_common_metafields_FieldWithMetaAssetClassEnum_schema.FieldWithMetaAssetClassEnum] | None
    ) = Field(None, alias="secondaryAssetClass", description=" Classifies additional risk classes of the trade, if any.", min_length=0)
    product_qualifier: str | None = Field(
        None,
        alias="productQualifier",
        description="Derived from the product payout features using a CDM product qualification function that determines the product type based on the product payout features.",
    )
