# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-metafields-FieldWithMetaCommodityReferencePriceEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_observable_asset_CommodityReferencePriceEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaCommodityReferencePriceEnum(BaseModel):
    value: cdm_observable_asset_CommodityReferencePriceEnum_schema.CommodityReferencePriceEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
