# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CSAMinimumTransferAmount.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_MTAType_schema


class CSAMinimumTransferAmount(BaseModel):
    mta_type: cdm_legaldocumentation_csa_MTAType_schema.MTAType = Field(
        ..., alias="mtaType", description="Details whether the Minimum Transfer Amount (MTA) is rating based, a fixed amount, or infinity."
    )
