# generated by datamodel-codegen:
#   filename:  cdm-event-common-CalculateTransferInstruction.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_math_Quantity_schema,
    cdm_base_staticdata_party_PayerReceiver_schema,
    cdm_event_common_Reset_schema,
    cdm_event_common_TradeState_schema,
    cdm_product_template_metafields_ReferenceWithMetaPayout_schema,
)


class CalculateTransferInstruction(BaseModel):
    trade_state: cdm_event_common_TradeState_schema.TradeState = Field(..., alias="tradeState")
    payout: cdm_product_template_metafields_ReferenceWithMetaPayout_schema.ReferenceWithMetaPayout
    resets: list[cdm_event_common_Reset_schema.Reset] | None = Field(None, min_length=0)
    payer_receiver: cdm_base_staticdata_party_PayerReceiver_schema.PayerReceiver | None = Field(
        None, alias="payerReceiver"
    )
    quantity: cdm_base_math_Quantity_schema.Quantity | None = Field(
        None,
        description="Specifies quantity amount returned if not the full amount from the TradeState, e.g. partial return",
    )
    date: str | None = None
