# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-AssetTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AssetTypeEnum(StrEnum):
    cash = "Cash"
    commodity = "Commodity"
    other = "Other"
    security = "Security"
