# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValueCashEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ValueCashEnum(StrEnum):
    CASH___AMOUNT_THEREOF = "Cash - Amount Thereof"
    CASH___AMOUNT_THEREOF_MULTIPLIED_BY_VALUATION_PERCENTAGE = (
        "Cash - Amount Thereof multiplied by Valuation Percentage"
    )
    CASH___AMOUNT_THEREOF_MULTIPLIED_BY__VALUATION_PERCENTAGE___FX_HAIRCUT_ = (
        "Cash - Amount Thereof multiplied by (Valuation Percentage - FX Haircut)"
    )
    OTHER = "Other"
