# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-IndependentAmountEligibilityEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class IndependentAmountEligibilityEnum(StrEnum):
    NONE = "None"
    NONE_UNLESS_SPECIFIED_IN_CONFIRMATION = "NoneUnlessSpecifiedInConfirmation"
