# generated by datamodel-codegen:
#   filename:  cdm-product-asset-CreditSeniorityEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CreditSeniorityEnum(StrEnum):
    OTHER = "Other"
    SENIOR_LOSS_ABSORBING_CAPACITY = "SeniorLossAbsorbingCapacity"
    SENIOR_SEC = "SeniorSec"
    SENIOR_UN_SEC = "SeniorUnSec"
    SUB_LOWER_TIER2 = "SubLowerTier2"
    SUB_TIER1 = "SubTier1"
    SUB_TIER3 = "SubTier3"
    SUB_UPPER_TIER2 = "SubUpperTier2"
