# generated by datamodel-codegen:
#   filename:  cdm-event-common-CorporateActionTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CorporateActionTypeEnum(StrEnum):
    BONUS_ISSUE = "BonusIssue"
    CASH_DIVIDEND = "CashDividend"
    CLASS_ACTION = "ClassAction"
    DELISTING = "Delisting"
    EARLY_REDEMPTION = "EarlyRedemption"
    LIQUIDATION = "Liquidation"
    MERGER = "Merger"
    REVERSE_STOCK_SPLIT = "ReverseStockSplit"
    RIGHTS_ISSUE = "RightsIssue"
    SPIN_OFF = "SpinOff"
    STOCK_DIVIDEND = "StockDividend"
    STOCK_IDENTIFIER_CHANGE = "StockIdentifierChange"
    STOCK_NAME_CHANGE = "StockNameChange"
    STOCK_RECLASSIFICATION = "StockReclassification"
    STOCK_SPLIT = "StockSplit"
    TAKEOVER = "Takeover"
