# generated by datamodel-codegen:
#   filename:  cdm-base-math-metafields-FieldWithMetaNonNegativeQuantitySchedule.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import (
    cdm_base_math_NonNegativeQuantitySchedule_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class FieldWithMetaNonNegativeQuantitySchedule(BaseModel):
    value: cdm_base_math_NonNegativeQuantitySchedule_schema.NonNegativeQuantitySchedule | None = (
        None
    )
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
