# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyValuationDate.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_csa_ValuationDateDateEnum_schema,
    cdm_legaldocumentation_csa_ValuationDateDayEnum_schema,
    cdm_legaldocumentation_csa_ValuationDateFrequencyEnum_schema,
)


class LegacyValuationDate(BaseModel):
    date: cdm_legaldocumentation_csa_ValuationDateDateEnum_schema.ValuationDateDateEnum | None = Field(
        None,
        description="Defines whether a date is defined by a certain day of the week or a particular date in the month. If not specified here, then additional language must be used.",
    )
    day: cdm_legaldocumentation_csa_ValuationDateDayEnum_schema.ValuationDateDayEnum | None = Field(
        None, description="Specific day(s) or day of the week, if any, specified for Valuation Time."
    )
    calendar_day: float | None = Field(
        None, alias="calendarDay", description="Defines the day of the calendar if this is specified for in the ValuationDateDateEnum."
    )
    frequency: cdm_legaldocumentation_csa_ValuationDateFrequencyEnum_schema.ValuationDateFrequencyEnum | None = Field(
        None, description="Defines the regularity of the date specified for the Valuation Date."
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
