# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-ListingExchange.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import com_rosetta_model_metafields_FieldWithMetaString_schema


class ListingExchange(BaseModel):
    exchange: (
        list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None
    ) = Field(
        None,
        description="Represents a filter based on the Primary Stock Exchange facilitating the listing of companies, exchange of Stocks, Exchange traded Derivatives, Bonds, and other Securities expressed in ISO standard 10383.",
        min_length=1,
    )
