# generated by datamodel-codegen:
#   filename:  cdm-product-asset-FinalPrincipalExchangeCalculationEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class FinalPrincipalExchangeCalculationEnum(StrEnum):
    FLOORED = "Floored"
    NON_FLOORED = "NonFloored"
