# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SecurityInterestForObligations.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_legaldocumentation_csa_SecurityInterestObligationsEnum_schema,
    cdm_legaldocumentation_csa_SecurityInterestObligeeEnum_schema,
)


class SecurityInterestForObligations(BaseModel):
    party: list[cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum] | None = Field(
        None,
        description="The elective party to which the Security Interest for Obligations is applicable.",
        max_length=2,
        min_length=2,
    )
    obligations: cdm_legaldocumentation_csa_SecurityInterestObligationsEnum_schema.SecurityInterestObligationsEnum = (
        Field(
            ..., description="A description of any additional obligations secured by the credit support arrangements."
        )
    )
    obligee: cdm_legaldocumentation_csa_SecurityInterestObligeeEnum_schema.SecurityInterestObligeeEnum = Field(
        ...,
        description="The party to whom obligations under the Master Agreement are owed and secured by the credit support arrangements.",
    )
    other: str | None = Field(None, description="Exception value.")
