# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-MultipleValuationDates.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class MultipleValuationDates(BaseModel):
    business_days: int | None = Field(
        None,
        alias="businessDays",
        description="A number of business days. Its precise meaning is dependant on the context in which this element is used. ISDA 2003 Term: Business Day.",
    )
    business_days_thereafter: int | None = Field(
        None,
        alias="businessDaysThereafter",
        description="The number of business days between successive valuation dates when multiple valuation dates are applicable for cash settlement. ISDA 2003 Term: Business Days thereafter.",
    )
    number_valuation_dates: int | None = Field(
        None,
        alias="numberValuationDates",
        description="Where multiple valuation dates are specified as being applicable for cash settlement, this element specifies (a) the number of applicable valuation dates, and (b) the number of business days after satisfaction of all conditions to settlement when the first such valuation date occurs, and (c) the number of business days thereafter of each successive valuation date. ISDA 2003 Term: Multiple Valuation Dates.",
    )
