# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-PostingObligations.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_PostingObligationsElection_schema


class PostingObligations(BaseModel):
    security_provider: str = Field(
        ...,
        alias="securityProvider",
        description="The security provider party(ies) to which the posting obligations apply to, which can be either one of the parties to the legal agreement, or both of those.",
    )
    party_election: (
        list[cdm_legaldocumentation_csa_PostingObligationsElection_schema.PostingObligationsElection] | None
    ) = Field(
        None,
        alias="partyElection",
        description="The specification of the collateral posting obligations for the security provider party(ies).",
        max_length=2,
        min_length=1,
    )
