# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SecurityProviderRightsEvent.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_SecurityProviderRightsEventElection_schema


class SecurityProviderRightsEvent(BaseModel):
    party_election: (
        list[
            cdm_legaldocumentation_csa_SecurityProviderRightsEventElection_schema.SecurityProviderRightsEventElection
        ]
        | None
    ) = Field(None, alias="partyElection", max_length=2, min_length=0)
    include_cooling_off_language: bool = Field(
        ...,
        alias="includeCoolingOffLanguage",
        description="The Pledgor/Obligor/Chargor Rights Event election includes cooling off language when the attribute is set of True.",
    )
    full_discharge: bool | None = Field(
        None,
        alias="fullDischarge",
        description="If specified as applicable here, a Pledgor/Obligor/Chargor Rights Event will not occur unless the Pledgor/Obligor/Chargor (A) has provided a statement to the Secured Party in respect of such Early Termination Date.",
    )
    automatic_set_off: bool | None = Field(
        None,
        alias="automaticSetOff",
        description="The Automatic Set-Off provision applies when the value is set to True.",
    )
    custom_election: str | None = Field(
        None,
        alias="customElection",
        description="A custom Pledgor/Obligor/Chargor Rights Event election might be specified by the parties.",
    )
