# generated by datamodel-codegen:
#   filename:  cdm-product-asset-ReturnTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ReturnTypeEnum(StrEnum):
    PRICE = "Price"
    TOTAL = "Total"
