# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-CollateralMarginTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CollateralMarginTypeEnum(StrEnum):
    INITIAL_MARGIN = "InitialMargin"
    VARIATION_MARGIN = "VariationMargin"
