# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-fro-FloatingRateIndexCategoryEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class FloatingRateIndexCategoryEnum(StrEnum):
    CALCULATED_RATE = "Calculated Rate"
    REFERENCE_BANKS_RATE = "Reference Banks Rate"
    SCREEN_RATE = "Screen Rate"
