# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-HoldingPostedCollateralEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class HoldingPostedCollateralEnum(StrEnum):
    ACCEPTABLE_CUSTODIAN = "AcceptableCustodian"
