# generated by datamodel-codegen:
#   filename:  cdm-event-common-InstructionFunctionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class InstructionFunctionEnum(StrEnum):
    COMPRESSION = "Compression"
    CONTRACT_FORMATION = "ContractFormation"
    EXECUTION = "Execution"
    QUANTITY_CHANGE = "QuantityChange"
    RENEGOTIATION = "Renegotiation"
