# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-master-isda-AutomaticEarlyTerminationElection.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_Party_schema


class AutomaticEarlyTerminationElection(BaseModel):
    party: cdm_base_staticdata_party_Party_schema.Party = Field(
        ..., description="The party for which the Automatic Early Termination provisions are being specified."
    )
    is_applicable: bool = Field(
        ...,
        alias="isApplicable",
        description="A boolean election to specify whether the Automatic Early Termination provisions of Section 6(a) are applicable (True) or not applicable (False).",
    )
