# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-MaterialChangeInCircumstance.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_transaction_additionalterms_EscrowArrangement_schema, cdm_observable_asset_ValuationPostponement_schema


class MaterialChangeInCircumstance(BaseModel):
    material_change_in_circumstance_is_applicable: bool = Field(..., alias="materialChangeInCircumstanceIsApplicable")
    escrow_arrangement: cdm_legaldocumentation_transaction_additionalterms_EscrowArrangement_schema.EscrowArrangement | None = Field(
        None, alias="escrowArrangement"
    )
    maximum_days_of_disruption: cdm_observable_asset_ValuationPostponement_schema.ValuationPostponement | None = Field(
        None, alias="maximumDaysOfDisruption"
    )
