# generated by datamodel-codegen:
#   filename:  cdm-base-math-AveragingWeightingMethodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AveragingWeightingMethodEnum(StrEnum):
    UNWEIGHTED = "Unweighted"
    WEIGHTED = "Weighted"
