# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-AveragingPeriod.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AveragingSchedule_schema,
    cdm_base_datetime_DateTimeList_schema,
    cdm_observable_event_metafields_FieldWithMetaMarketDisruptionEnum_schema,
    cdm_product_common_schedule_AveragingObservationList_schema,
)


class AveragingPeriod(BaseModel):
    schedule: list[cdm_base_datetime_AveragingSchedule_schema.AveragingSchedule] | None = Field(
        None, description="A schedule for generating averaging observation dates.", min_length=0
    )
    averaging_date_times: cdm_base_datetime_DateTimeList_schema.DateTimeList | None = Field(
        None,
        alias="averagingDateTimes",
        description="An unweighted list of averaging observation date and times.",
    )
    averaging_observations: (
        cdm_product_common_schedule_AveragingObservationList_schema.AveragingObservationList | None
    ) = Field(
        None,
        alias="averagingObservations",
        description="A weighted list of averaging observation date and times.",
    )
    market_disruption: (
        cdm_observable_event_metafields_FieldWithMetaMarketDisruptionEnum_schema.FieldWithMetaMarketDisruptionEnum
        | None
    ) = Field(
        None,
        alias="marketDisruption",
        description="The market disruption event as defined by ISDA 2002 Definitions.",
    )
