# generated by datamodel-codegen:
#   filename:  cdm-regulation-AddtlAttrbts.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class AddtlAttrbts(BaseModel):
    rsk_rdcg_tx: str = Field(..., alias="rskRdcgTx")
    scties_fincg_tx_ind: str = Field(..., alias="sctiesFincgTxInd")
