# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CalculationDateLocationElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_metafields_FieldWithMetaBusinessCenterEnum_schema,
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
)


class CalculationDateLocationElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    business_center: (
        cdm_base_datetime_metafields_FieldWithMetaBusinessCenterEnum_schema.FieldWithMetaBusinessCenterEnum | None
    ) = Field(
        None,
        alias="businessCenter",
        description="The Calculation Date Location when specified as a business center which corresponds to the FpML list of business centers or can be mapped to it.",
    )
    custom_location: str | None = Field(
        None,
        alias="customLocation",
        description="The Calculation Date Location when specified a location which doesn't correspond to the FpML list of business centers or cannot be mapped to it.",
    )
