# generated by datamodel-codegen:
#   filename:  cdm-product-template-AveragingInOutEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AveragingInOutEnum(StrEnum):
    both = "Both"
    in_ = "In"
    out = "Out"
