# generated by datamodel-codegen:
#   filename:  cdm-event-common-InstructionFunctionEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class InstructionFunctionEnum(StrEnum):
    compression = "Compression"
    contract_formation = "ContractFormation"
    execution = "Execution"
    quantity_change = "QuantityChange"
    renegotiation = "Renegotiation"
