# generated by datamodel-codegen:
#   filename:  cdm-product-asset-DayDistributionEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DayDistributionEnum(StrEnum):
    all = "All"
    first = "First"
    last = "Last"
    penultimate = "Penultimate"
