# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RecalculationOfValue.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_RecalculationOfValueElection_schema


class RecalculationOfValue(BaseModel):
    party_election: list[cdm_legaldocumentation_csa_RecalculationOfValueElection_schema.RecalculationOfValueElection] | None = Field(
        None, alias="partyElection", description="The parties' Recalculation of Value terms.", max_length=2, min_length=2
    )
