# generated by datamodel-codegen:
#   filename:  cdm-event-common-State.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_ClosedState_schema, cdm_event_position_PositionStatusEnum_schema


class State(BaseModel):
    closed_state: cdm_event_common_ClosedState_schema.ClosedState | None = Field(
        None,
        alias="closedState",
        description="Represents the qualification of what led to the trade's closure alongside the dates on which this closure took effect.",
    )
    position_state: cdm_event_position_PositionStatusEnum_schema.PositionStatusEnum | None = Field(
        None,
        alias="positionState",
        description="Identifies the state of the position, to distinguish if just executed, formed, already settled, closed, etc.",
    )
