# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-WeeklyRollConventionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class WeeklyRollConventionEnum(StrEnum):
    FRI = "FRI"
    MON = "MON"
    SAT = "SAT"
    SUN = "SUN"
    TBILL = "TBILL"
    THU = "THU"
    TUE = "TUE"
    WED = "WED"
