# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-TerminationCurrencyConditionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class TerminationCurrencyConditionEnum(StrEnum):
    FREELY_AVAILABLE = "FreelyAvailable"
    PAYMENTS_DUE = "PaymentsDue"
    PAYMENTS_DUE_AND_FREELY_AVAILABLE = "PaymentsDueAndFreelyAvailable"
    SPECIFIED = "Specified"
