# generated by datamodel-codegen:
#   filename:  cdm-product-asset-CompoundingMethodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CompoundingMethodEnum(StrEnum):
    FLAT = "Flat"
    NONE = "None"
    SPREAD_EXCLUSIVE = "SpreadExclusive"
    STRAIGHT = "Straight"
