# generated by datamodel-codegen:
#   filename:  cdm-observable-common-DeterminationMethodEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DeterminationMethodEnum(StrEnum):
    agreed_initial_price = "AgreedInitialPrice"
    as_specified_in_master_confirmation = "AsSpecifiedInMasterConfirmation"
    calculation_agent = "CalculationAgent"
    closing_price = "ClosingPrice"
    dividend_currency = "DividendCurrency"
    expiring_contract_level = "ExpiringContractLevel"
    hedge_execution = "HedgeExecution"
    issuer_payment_currency = "IssuerPaymentCurrency"
    nav = "NAV"
    osp_price = "OSPPrice"
    open_price = "OpenPrice"
    settlement_currency = "SettlementCurrency"
    strike_date_determination = "StrikeDateDetermination"
    twap_price = "TWAPPrice"
    twapve = "TWAPVE"
    twapve_excluding_close = "TWAPVEExcludingClose"
    vwap_price = "VWAPPrice"
    vwapve = "VWAPVE"
    vwapve_excluding_close = "VWAPVEExcludingClose"
    valuation_time = "ValuationTime"
