# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-CheckEligibilityResult.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_product_collateral_EligibilityQuery_schema,
    cdm_product_collateral_EligibleCollateralCriteria_schema,
    cdm_product_collateral_EligibleCollateralSpecification_schema,
)


class CheckEligibilityResult(BaseModel):
    is_eligible: bool = Field(
        ...,
        alias="isEligible",
        description="a simple boolean which is set to true if the asset described in the EligibilityQuery input is eligible",
    )
    matching_eligible_criteria: (
        list[cdm_product_collateral_EligibleCollateralCriteria_schema.EligibleCollateralCriteria]
        | None
    ) = Field(
        None,
        alias="matchingEligibleCriteria",
        description="if there was a match, this will be the one or more criteria that were supplied in the EligbilityCollateralSpecification which matched with the query input",
        min_length=0,
    )
    eligibility_query: cdm_product_collateral_EligibilityQuery_schema.EligibilityQuery = Field(
        ...,
        alias="eligibilityQuery",
        description="a copy of the input query that was checked against the eligible collateral specification",
    )
    specification: cdm_product_collateral_EligibleCollateralSpecification_schema.EligibleCollateralSpecification = Field(
        ...,
        description="a copy of the input EligbilityCollateralSpecification that was checked against the query",
    )
