# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyConsentEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class LegacyConsentEnum(StrEnum):
    consent_required = "ConsentRequired"
    consent_required_no_delay = "ConsentRequiredNoDelay"
    costs_apportioned = "CostsApportioned"
    no_consent = "NoConsent"
    notice_conditions = "NoticeConditions"
    times_adjusted = "TimesAdjusted"
