# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValuationTimeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ValuationTimeEnum(StrEnum):
    as_selected = "AsSelected"
    close_of_business = "CloseOfBusiness"
    specific_time = "SpecificTime"
