# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-ContractualTermsSupplement.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_common_metafields_FieldWithMetaContractualSupplementTypeEnum_schema,
)


class ContractualTermsSupplement(BaseModel):
    contractual_terms_supplement_type: cdm_legaldocumentation_common_metafields_FieldWithMetaContractualSupplementTypeEnum_schema.FieldWithMetaContractualSupplementTypeEnum = Field(
        ...,
        alias="contractualTermsSupplementType",
        description="Identifies the form of applicable contractual supplement.",
    )
    publication_date: str | None = Field(
        None,
        alias="publicationDate",
        description="Specifies the publication date of the applicable version of the contractual supplement.",
    )
