# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ExposureScopeProductEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ExposureScopeProductEnum(StrEnum):
    CURRENCY_OPTION_TRANSACTIONS = "Currency Option Transactions"
    FX_TRANSACTION_WITH_SETTLEMENT_DATE = "FX Transaction with Settlement Date"
    FX_TRANSACTIONS = "FX Transactions"
