# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-SettlementCentreEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class SettlementCentreEnum(StrEnum):
    clearstream_banking_luxembourg = "ClearstreamBankingLuxembourg"
    euroclear_bank = "EuroclearBank"
