# generated by datamodel-codegen:
#   filename:  cdm-product-template-AssetPayoutTradeTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AssetPayoutTradeTypeEnum(StrEnum):
    buy_sell_back = "Buy/Sell-Back"
    repo = "Repo"
