# generated by datamodel-codegen:
#   filename:  cdm-event-common-EventIntentEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class EventIntentEnum(StrEnum):
    ALLOCATION = "Allocation"
    CASH_FLOW = "CashFlow"
    CLEARING = "Clearing"
    COMPRESSION = "Compression"
    CONTRACT_FORMATION = "ContractFormation"
    CONTRACT_TERMS_AMENDMENT = "ContractTermsAmendment"
    CORPORATE_ACTION_ADJUSTMENT = "CorporateActionAdjustment"
    CREDIT_EVENT = "CreditEvent"
    DECREASE = "Decrease"
    EARLY_TERMINATION_PROVISION = "EarlyTerminationProvision"
    INCREASE = "Increase"
    INDEX_TRANSITION = "IndexTransition"
    NOTIONAL_RESET = "NotionalReset"
    NOTIONAL_STEP = "NotionalStep"
    NOVATION = "Novation"
    OBSERVATION_RECORD = "ObservationRecord"
    OPTION_EXERCISE = "OptionExercise"
    OPTIONAL_CANCELLATION = "OptionalCancellation"
    OPTIONAL_EXTENSION = "OptionalExtension"
    PORTFOLIO_REBALANCING = "PortfolioRebalancing"
    PRINCIPAL_EXCHANGE = "PrincipalExchange"
    REALLOCATION = "Reallocation"
    REPURCHASE = "Repurchase"
