# generated by datamodel-codegen:
#   filename:  cdm-product-template-ExerciseNoticeGiverEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ExerciseNoticeGiverEnum(StrEnum):
    as_specified_in_master_agreement = "AsSpecifiedInMasterAgreement"
    both = "Both"
    buyer = "Buyer"
    seller = "Seller"
