# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RightsEvents.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_csa_AdditionalRightsEvent_schema,
    cdm_legaldocumentation_csa_ControlAgreementNecEvent_schema,
    cdm_legaldocumentation_csa_SecuredPartyRightsEvent_schema,
    cdm_legaldocumentation_csa_SecurityProviderRightsEvent_schema,
)


class RightsEvents(BaseModel):
    security_taker_rights_event: cdm_legaldocumentation_csa_SecuredPartyRightsEvent_schema.SecuredPartyRightsEvent = Field(
        ...,
        alias="securityTakerRightsEvent",
        description="The bespoke provisions that might be specified by the parties to the agreement applicable to a Security Taker Rights Event.",
    )
    control_agreement_nec_event: (
        cdm_legaldocumentation_csa_ControlAgreementNecEvent_schema.ControlAgreementNecEvent | None
    ) = Field(
        None,
        alias="controlAgreementNecEvent",
        description="The bespoke provisions that might be specified by the parties to the agreement applicable to a Notice of Exclusive Control Event.",
    )
    security_provider_rights_event: cdm_legaldocumentation_csa_SecurityProviderRightsEvent_schema.SecurityProviderRightsEvent = Field(
        ...,
        alias="securityProviderRightsEvent",
        description="The bespoke provisions that might be specified by the parties to the agreement applicable to a Security Provider Rights Event.",
    )
    delivery_in_lieu_right: bool | None = Field(
        None,
        alias="deliveryInLieuRight",
        description="The specification of whether Delivery In Lieu language is applicable to the agreement (true) or not (false).",
    )
    additional_rights_event: (
        cdm_legaldocumentation_csa_AdditionalRightsEvent_schema.AdditionalRightsEvent | None
    ) = Field(
        None, alias="additionalRightsEvent", description="The Additional Rights Event election."
    )
