# generated by datamodel-codegen:
#   filename:  cdm-event-common-RecordAmountTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class RecordAmountTypeEnum(StrEnum):
    account_total = "AccountTotal"
    grand_total = "GrandTotal"
    parent_total = "ParentTotal"
