# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-AccountTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class AccountTypeEnum(StrEnum):
    aggregate_client = "AggregateClient"
    client = "Client"
    house = "House"
