# generated by datamodel-codegen:
#   filename:  cdm-product-asset-FloatingRateDefinition.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_RateObservation_schema, cdm_product_template_Strike_schema


class FloatingRateDefinition(BaseModel):
    calculated_rate: float | None = Field(
        None,
        alias="calculatedRate",
        description="The final calculated rate for a calculation period after any required averaging of rates A calculated rate of 5% would be represented as 0.05.",
    )
    rate_observation: list[cdm_observable_asset_RateObservation_schema.RateObservation] | None = (
        Field(
            None,
            alias="rateObservation",
            description="The details of a particular rate observation, including the fixing date and observed rate. A list of rate observation elements may be ordered in the document by ascending adjusted fixing date. An FpML document containing an unordered list of rate observations is still regarded as a conformant document.",
            min_length=0,
        )
    )
    floating_rate_multiplier: float | None = Field(
        None,
        alias="floatingRateMultiplier",
        description="A rate multiplier to apply to the floating rate. The multiplier can be a positive or negative decimal. This element should only be included if the multiplier is not equal to 1 (one).",
    )
    spread: float | None = Field(
        None,
        description="The ISDA Spread, if any, which applies for the calculation period. The spread is a per annum rate, expressed as a decimal. For purposes of determining a calculation period amount, if positive the spread will be added to the floating rate and if negative the spread will be subtracted from the floating rate. A positive 10 basis point (0.1%) spread would be represented as 0.001.",
    )
    cap_rate: list[cdm_product_template_Strike_schema.Strike] | None = Field(
        None,
        alias="capRate",
        description="The cap rate, if any, which applies to the floating rate for the calculation period. The cap rate (strike) is only required where the floating rate on a swap stream is capped at a certain strike level. The cap rate is assumed to be exclusive of any spread and is a per annum rate, expressed as a decimal. A cap rate of 5% would be represented as 0.05.",
        min_length=0,
    )
    floor_rate: list[cdm_product_template_Strike_schema.Strike] | None = Field(
        None,
        alias="floorRate",
        description="The floor rate, if any, which applies to the floating rate for the calculation period. The floor rate (strike) is only required where the floating rate on a swap stream is floored at a certain strike level. The floor rate is assumed to be exclusive of any spread and is a per annum rate, expressed as a decimal. The floor rate of 5% would be represented as 0.05.",
        min_length=0,
    )
