# generated by datamodel-codegen:
#   filename:  cdm-event-position-PositionStatusEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class PositionStatusEnum(StrEnum):
    cancelled = "Cancelled"
    closed = "Closed"
    executed = "Executed"
    formed = "Formed"
    settled = "Settled"
