# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-metafields-FieldWithMetaNaturalPersonRoleEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_base_staticdata_party_NaturalPersonRoleEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaNaturalPersonRoleEnum(BaseModel):
    value: cdm_base_staticdata_party_NaturalPersonRoleEnum_schema.NaturalPersonRoleEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
