# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-CalculationPeriodDates.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableOrRelativeDate_schema,
    cdm_base_datetime_BusinessDayAdjustments_schema,
    cdm_base_datetime_CalculationPeriodFrequency_schema,
    cdm_product_common_schedule_StubPeriodTypeEnum_schema,
)


class CalculationPeriodDates(BaseModel):
    effective_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None,
        alias="effectiveDate",
        description="The first day of the terms of the trade. This day may be subject to adjustment in accordance with a business day convention.",
    )
    termination_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None,
        alias="terminationDate",
        description="The last day of the terms of the trade. This date may be subject to adjustments in accordance with the business day convention. It can also be specified in relation to another scheduled date (e.g. the last payment date).",
    )
    calculation_period_dates_adjustments: (
        cdm_base_datetime_BusinessDayAdjustments_schema.BusinessDayAdjustments | None
    ) = Field(
        None,
        alias="calculationPeriodDatesAdjustments",
        description="The specification of the business day convention and financial business centers used for adjusting any calculation period date if it would otherwise fall on a day that is not a business day in the specified business center.",
    )
    first_period_start_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None,
        alias="firstPeriodStartDate",
        description="The start date of the calculation period. FpML specifies that for interest rate swaps this date must only be specified if it is not equal to the effective date. It is always specified in the case of equity swaps and credit default swaps with periodic payments. This date may be subject to adjustment in accordance with a business day convention.",
    )
    first_regular_period_start_date: str | None = Field(
        None,
        alias="firstRegularPeriodStartDate",
        description="The start date of the regular part of the calculation period schedule. It must only be specified if there is an initial stub calculation period. This day may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments.",
    )
    first_compounding_period_end_date: str | None = Field(
        None,
        alias="firstCompoundingPeriodEndDate",
        description="The end date of the initial compounding period when compounding is applicable. It must only be specified when the compoundingMethod element is present and not equal to a value of None. This date may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments.",
    )
    last_regular_period_end_date: str | None = Field(
        None,
        alias="lastRegularPeriodEndDate",
        description="The end date of the regular part of the calculation period schedule. It must only be specified if there is a final stub calculation period. This day may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments.",
    )
    stub_period_type: cdm_product_common_schedule_StubPeriodTypeEnum_schema.StubPeriodTypeEnum | None = Field(
        None,
        alias="stubPeriodType",
        description="Method to allocate any irregular period remaining after regular periods have been allocated between the effective and termination date.",
    )
    calculation_period_frequency: (
        cdm_base_datetime_CalculationPeriodFrequency_schema.CalculationPeriodFrequency | None
    ) = Field(
        None,
        alias="calculationPeriodFrequency",
        description="The frequency at which calculation period end dates occur with the regular part of the calculation period schedule and their roll date convention.",
    )
