# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-CollateralInterestHandlingParameters.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_BusinessCenterEnum_schema,
    cdm_base_math_NumberBound_schema,
    cdm_product_collateral_AlternativeToInterestAmountEnum_schema,
    cdm_product_collateral_CollateralInterestHandlingEnum_schema,
    cdm_product_collateral_CollateralInterestNotification_schema,
    cdm_product_collateral_InterestAmountApplication_schema,
)


class CollateralInterestHandlingParameters(BaseModel):
    interest_payment_handling: cdm_product_collateral_CollateralInterestHandlingEnum_schema.CollateralInterestHandlingEnum = Field(
        ..., alias="interestPaymentHandling", description="Specifies how the collateral interest is to be handled."
    )
    payment_business_center: list[cdm_base_datetime_BusinessCenterEnum_schema.BusinessCenterEnum] | None = Field(
        None,
        alias="paymentBusinessCenter",
        description="Specifies applicable business centers for payments.",
        min_length=0,
    )
    net_posted_and_held_interest: bool = Field(
        ...,
        alias="netPostedAndHeldInterest",
        description="Indicates whether to net Held and Posted Interest Payments (i.e. whether interest payable for a period can be netted with interest receivable).",
    )
    net_interest_with_margin_calls: bool = Field(
        ...,
        alias="netInterestWithMarginCalls",
        description="Indicates whether the interest amount may be offset against any margin call deliver or return amounts?   (aka 'net payments' indicator).",
    )
    include_accrual_in_margin_calc: bool = Field(
        ...,
        alias="includeAccrualInMarginCalc",
        description="Indicates whether or not to include the open interest accrual in the margin calculation.",
    )
    accrue_interest_on_unsettled_interest: bool | None = Field(
        None,
        alias="accrueInterestOnUnsettledInterest",
        description="Indicates whether interest accruing on unsettled interest amount is included (continues to be accrued) in the following period.",
    )
    on_full_return: bool = Field(
        ...,
        alias="onFullReturn",
        description="Indicates the option that accrued interest should be calculated and distributed when a full return of collateral occurs.",
    )
    on_partial_return: bool = Field(
        ...,
        alias="onPartialReturn",
        description="Indicates the option that accrued interest should be calculated and distributed when a partial return collateral occurs.",
    )
    interest_amount_application: (
        cdm_product_collateral_InterestAmountApplication_schema.InterestAmountApplication | None
    ) = Field(
        None,
        alias="interestAmountApplication",
        description="The application of Interest Amount with respect to the Delivery Amount and the Return Amount.",
    )
    interest_rollover_limit: cdm_base_math_NumberBound_schema.NumberBound | None = Field(
        None,
        alias="interestRolloverLimit",
        description="Specifies the level below which the interest will be rolled over.",
    )
    writeoff_limit: cdm_base_math_NumberBound_schema.NumberBound | None = Field(
        None,
        alias="writeoffLimit",
        description="Specifies the level below which the interest will be written off; if omitted write-off is not applicable.",
    )
    alternative_to_interest_amount: (
        cdm_product_collateral_AlternativeToInterestAmountEnum_schema.AlternativeToInterestAmountEnum | None
    ) = Field(None, alias="alternativeToInterestAmount", description="Specifies the alternative to interest amounts.")
    alternative_provision: str | None = Field(
        None,
        alias="alternativeProvision",
        description="Specifies an alternative to interest amount, when the alternative provision clause is specified.",
    )
    cutoff_time: str | None = Field(
        None, alias="cutoffTime", description="Specifies the time of day that interest needs to be confirmed by."
    )
    notification: cdm_product_collateral_CollateralInterestNotification_schema.CollateralInterestNotification | None = (
        Field(None, description="Specifies the terms describing notification requirements.")
    )
