# generated by datamodel-codegen:
#   filename:  cdm-product-template-ManualExercise.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_template_ExerciseNotice_schema


class ManualExercise(BaseModel):
    exercise_notice: cdm_product_template_ExerciseNotice_schema.ExerciseNotice | None = Field(
        None,
        alias="exerciseNotice",
        description="Definition of the party to whom notice of exercise should be given.",
    )
    fallback_exercise: bool | None = Field(
        None,
        alias="fallbackExercise",
        description="If fallback exercise is specified then the notional amount of the underlying swap, not previously exercised under the swaption, will be automatically exercised at the expiration time on the expiration date if at such time the buyer is in-the-money, provided that the difference between the settlement rate and the fixed rate under the relevant underlying swap is not less than one tenth of a percentage point (0.10% or 0.001). The term in-the-money is assumed to have the meaning defined in the 2000 ISDA Definitions, Section 17.4. In-the-money.",
    )
