# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-metafields-FieldWithMetaMatrixTermEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_legaldocumentation_common_MatrixTermEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaMatrixTermEnum(BaseModel):
    value: cdm_legaldocumentation_common_MatrixTermEnum_schema.MatrixTermEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
