# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-CompoundingTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CompoundingTypeEnum(StrEnum):
    business = "Business"
    calendar = "Calendar"
    none = "None"
