# generated by datamodel-codegen:
#   filename:  cdm-product-asset-ReferenceObligation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_Loan_schema,
    cdm_base_staticdata_asset_common_Security_schema,
    cdm_base_staticdata_party_LegalEntity_schema,
    cdm_base_staticdata_party_metafields_ReferenceWithMetaLegalEntity_schema,
)


class ReferenceObligation(BaseModel):
    security: cdm_base_staticdata_asset_common_Security_schema.Security | None = Field(
        None,
        description="Identifies the underlying asset when it is a security, such as a bond or convertible bond. The security data type requires one or more productIdentifiers, specificaiton of the security type (e.g. debt), and includes optional attributes to specify a debt class, such as asset-backed, as well as seniority.",
    )
    loan: cdm_base_staticdata_asset_common_Loan_schema.Loan | None = Field(
        None, description="Identifies the underlying asset when it is a loan."
    )
    primary_obligor: cdm_base_staticdata_party_LegalEntity_schema.LegalEntity | None = Field(
        None,
        alias="primaryObligor",
        description="The entity primarily responsible for repaying debt to a creditor as a result of borrowing or issuing bonds. ISDA 2003 Term: Primary Obligor.",
    )
    primary_obligor_reference: (
        cdm_base_staticdata_party_metafields_ReferenceWithMetaLegalEntity_schema.ReferenceWithMetaLegalEntity | None
    ) = Field(
        None,
        alias="primaryObligorReference",
        description="A pointer style reference to a reference entity defined elsewhere in the document. Used when the reference entity is the primary obligor.",
    )
    guarantor: cdm_base_staticdata_party_LegalEntity_schema.LegalEntity | None = Field(
        None,
        description="The party that guarantees by way of a contractual arrangement to pay the debts of an obligor if the obligor is unable to make the required payments itself. ISDA 2003 Term: Guarantor.",
    )
    guarantor_reference: str | None = Field(
        None,
        alias="guarantorReference",
        description="A pointer style reference to a reference entity defined elsewhere in the document. Used when the reference entity is the guarantor.",
    )
    standard_reference_obligation: bool | None = Field(
        None,
        alias="standardReferenceObligation",
        description="Indicates if the reference obligation is a Standard Reference Obligation. ISDA 2014 Term: Standard Reference Obligation.",
    )
