# generated by datamodel-codegen:
#   filename:  cdm-event-common-ReturnInstruction.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_math_Quantity_schema


class ReturnInstruction(BaseModel):
    quantity: list[cdm_base_math_Quantity_schema.Quantity] | None = Field(
        None, description="Specifies the quantity of shares and cash to be returned in a partial return event.", min_length=1
    )
