# generated by datamodel-codegen:
#   filename:  cdm-product-template-OptionTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class OptionTypeEnum(StrEnum):
    call = "Call"
    payer = "Payer"
    put = "Put"
    receiver = "Receiver"
    straddle = "Straddle"
