# generated by datamodel-codegen:
#   filename:  cdm-event-common-TransferStatusEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class TransferStatusEnum(StrEnum):
    DISPUTED = "Disputed"
    INSTRUCTED = "Instructed"
    NETTED = "Netted"
    PENDING = "Pending"
    SETTLED = "Settled"
