# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-ContractualMatrix.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_common_metafields_FieldWithMetaMatrixTermEnum_schema,
    cdm_legaldocumentation_common_metafields_FieldWithMetaMatrixTypeEnum_schema,
)


class ContractualMatrix(BaseModel):
    matrix_type: cdm_legaldocumentation_common_metafields_FieldWithMetaMatrixTypeEnum_schema.FieldWithMetaMatrixTypeEnum = Field(
        ..., alias="matrixType", description="Identifies the form of applicable matrix."
    )
    matrix_term: cdm_legaldocumentation_common_metafields_FieldWithMetaMatrixTermEnum_schema.FieldWithMetaMatrixTermEnum | None = Field(
        None,
        alias="matrixTerm",
        description="Defines any applicable key into the relevant matrix. For example, the Transaction Type would be the single term required for the Credit Derivatives Physical Settlement Matrix. This element should be omitted in the case of the 2000 ISDA Definitions Settlement Matrix for Early Termination and Swaptions.",
    )
