# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-AdjustableDates.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_BusinessDayAdjustments_schema, com_rosetta_model_metafields_FieldWithMetaString_schema


class AdjustableDates(BaseModel):
    unadjusted_date: list[str] | None = Field(None, alias="unadjustedDate", description="A date subject to adjustment.", min_length=0)
    date_adjustments: cdm_base_datetime_BusinessDayAdjustments_schema.BusinessDayAdjustments | None = Field(
        None,
        alias="dateAdjustments",
        description="The business day convention and financial business centers used for adjusting the date if it would otherwise fall on a day that is not a business date in the specified business centers.",
    )
    adjusted_date: list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None = Field(
        None,
        alias="adjustedDate",
        description="The date(s) once the adjustment has been performed. (Note that this date may change if the business center holidays change).",
        min_length=0,
    )
