# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-AppropriatedCollateralValuation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class AppropriatedCollateralValuation(BaseModel):
    is_specified: bool = Field(
        ...,
        alias="isSpecified",
        description="The qualification of whether the Valuation of Appropriate Collateral provision is applicable (True) or not applicable (False).",
    )
    election: str | None = Field(
        None,
        description="The parties' election that qualify the Valuation of Appropriate Collateral in the case where it is deemed applicable.",
    )
