# generated by datamodel-codegen:
#   filename:  cdm-event-position-Portfolio.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_event_position_AggregationParameters_schema,
    cdm_event_position_PortfolioState_schema,
)


class Portfolio(BaseModel):
    aggregation_parameters: cdm_event_position_AggregationParameters_schema.AggregationParameters = Field(
        ...,
        alias="aggregationParameters",
        description="Describes the portfolio by describing how to aggregate all its relevant Events.",
    )
    portfolio_state: cdm_event_position_PortfolioState_schema.PortfolioState = Field(
        ...,
        alias="portfolioState",
        description="Describes the state of the Portfolio as a list of Positions resulting from the aggregation.",
    )
