# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-Instrument.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_ListedDerivative_schema,
    cdm_base_staticdata_asset_common_Loan_schema,
    cdm_base_staticdata_asset_common_Security_schema,
)


class Instrument(BaseModel):
    listed_derivative: (
        cdm_base_staticdata_asset_common_ListedDerivative_schema.ListedDerivative | None
    ) = Field(
        None,
        alias="ListedDerivative",
        description="A securitized derivative on another asset that is created by an exchange.",
    )
    loan: cdm_base_staticdata_asset_common_Loan_schema.Loan | None = Field(
        None, alias="Loan", description="An Asset that represents a loan or borrow obligation."
    )
    security: cdm_base_staticdata_asset_common_Security_schema.Security | None = Field(
        None,
        alias="Security",
        description="An Asset that is issued by a party to be held by or transferred to others.",
    )
