# generated by datamodel-codegen:
#   filename:  cdm-event-workflow-metafields-FieldWithMetaCreditLimitTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_event_workflow_CreditLimitTypeEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaCreditLimitTypeEnum(BaseModel):
    value: cdm_event_workflow_CreditLimitTypeEnum_schema.CreditLimitTypeEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
