# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SecurityInterestObligeeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class SecurityInterestObligeeEnum(StrEnum):
    other = "Other"
    party_a = "PartyA"
    party_a_or_any_affiliate_of_party_a = "Party A or any Affiliate of Party A"
    party_b = "PartyB"
    party_b_or_any_affiliate_of_party_b = "Party B or any Affiliate of Party B"
