# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-fro-ContractualDefinition.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_identifier_Identifier_schema, cdm_observable_asset_fro_ContractualDefinitionIdentifier_schema


class ContractualDefinition(BaseModel):
    identifier: cdm_base_staticdata_identifier_Identifier_schema.Identifier | None = Field(
        None, description="Corresponds to the unique identifier of the Contractual Definition in which the code is published"
    )
    contractual_definition_identifier: (
        cdm_observable_asset_fro_ContractualDefinitionIdentifier_schema.ContractualDefinitionIdentifier | None
    ) = Field(
        None,
        alias="contractualDefinitionIdentifier",
        description="Contractual Definition Identifier in which the code is published. Includes Document Type and Document Version",
    )
    publication_date: str | None = Field(None, alias="publicationDate", description="2021-06-11")
