# generated by datamodel-codegen:
#   filename:  cdm-product-asset-RateTreatmentEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class RateTreatmentEnum(StrEnum):
    BOND_EQUIVALENT_YIELD = "BondEquivalentYield"
    MONEY_MARKET_YIELD = "MoneyMarketYield"
