# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-PeriodRange.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_PeriodBound_schema


class PeriodRange(BaseModel):
    lower_bound: cdm_base_datetime_PeriodBound_schema.PeriodBound | None = Field(
        None,
        alias="lowerBound",
        description="Specifies the lower bound of a period range, e.g. greater than or equal to 5Y.",
    )
    upper_bound: cdm_base_datetime_PeriodBound_schema.PeriodBound | None = Field(
        None,
        alias="upperBound",
        description="Specifies the upper bound of a period range, e.g. less than to 10Y.",
    )
