# generated by datamodel-codegen:
#   filename:  cdm-regulation-SwpIn.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_regulation_Sngl_schema


class SwpIn(BaseModel):
    sngl: cdm_regulation_Sngl_schema.Sngl
