# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-DeterminationRoleEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DeterminationRoleEnum(StrEnum):
    calculation_agent = "CalculationAgent"
    determining_party = "DeterminingParty"
    hedging_party = "HedgingParty"
