# generated by datamodel-codegen:
#   filename:  cdm-product-template-AssetPayoutTradeTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AssetPayoutTradeTypeEnum(StrEnum):
    BUY_SELL_BACK = "Buy/Sell-Back"
    REPO = "Repo"
