# generated by datamodel-codegen:
#   filename:  cdm-base-math-NonNegativeStep.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field


class NonNegativeStep(BaseModel):
    step_date: str = Field(
        ...,
        alias="stepDate",
        description="The date on which the associated stepValue becomes effective. This day may be subject to adjustment in accordance with a business day convention.",
    )
    step_value: float = Field(
        ...,
        alias="stepValue",
        description="The non-negative rate or amount which becomes effective on the associated stepDate. A rate of 5% would be represented as 0.05.",
    )
