# generated by datamodel-codegen:
#   filename:  cdm-product-template-CancelableProvision.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableOrRelativeDate_schema,
    cdm_base_datetime_AdjustableOrRelativeDates_schema,
    cdm_base_datetime_BusinessCenterTime_schema,
    cdm_base_datetime_Period_schema,
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_event_common_Transfer_schema,
    cdm_product_common_schedule_FinalCalculationPeriodDateAdjustment_schema,
    cdm_product_template_CallingPartyEnum_schema,
    cdm_product_template_CancelableProvisionAdjustedDates_schema,
    cdm_product_template_ExerciseNotice_schema,
    cdm_product_template_ExerciseTerms_schema,
)


class CancelableProvision(BaseModel):
    buyer: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = Field(
        None,
        description="Buyer party that can be resolved as one of the two principal parties to the transaction. The party that buys this instrument, i.e. pays for this instrument and receives the rights defined by it. ISDA 2002 Equity Definitions section 1.18: `Buyer` means the party specified as such in the related Confirmation. | ISDA 2006 Definitions article 12.1 (b)(i) relating to a Swaption: 'Buyer' means the party that will, on each Premium Payment Date, pay to Seller the Premium | ISDA 2006 Definitions article 12.1 (b)(ii) relating to Swap Transactions with applicable Early Termination: the party specified as such in the related Confirmation, or the Exercising Party if neither party is specified | ISDA 2006 Definitions article 12.1 (b)(iii) relating to any other Option Transaction: the party specified as such in the related Confirmation. | ISDA 2014 Credit Definition article 1.4: `Buyer` means the Fixed Rate Payer.",
    )
    seller: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = Field(
        None,
        description="Seller party that can be resolved as one of the two principal parties to the transaction. The party that sells ('writes') this instrument, i.e. that grants the rights defined by this instrument and in return receives a payment for it. ISDA 2002 Equity Definitions section 1.19: `Seller` means the party specified as such in the related Confirmation. | ISDA 2006 Definitions article 12.1 (a)(i) relating to a Swaption: 'Seller' means the party the party specified as such or as writer in the related Confirmation | ISDA 2006 Definitions article 12.1 (a)(ii) relating to Swap Transactions with applicable Early Termination: the party specified as such or as writer in the related Confirmation or, if neither party is specified as such, the Non-exercising Party | ISDA 2006 Definitions article 12.1 (a)(iii) relating to any other Option Transaction: the party specified as such in the related Confirmation. | ISDA 2014 Credit Definition article 1.4: `Seller` means the Floating Rate Payer.",
    )
    exercise_notice: cdm_product_template_ExerciseNotice_schema.ExerciseNotice | None = Field(
        None, alias="exerciseNotice", description="Definition of the party to whom notice of exercise should be given."
    )
    follow_up_confirmation: bool = Field(
        ...,
        alias="followUpConfirmation",
        description="A flag to indicate whether follow-up confirmation of exercise (written or electronic) is required following telephonic notice by the buyer to the seller or seller's agent.",
    )
    cancelable_provision_adjusted_dates: (
        cdm_product_template_CancelableProvisionAdjustedDates_schema.CancelableProvisionAdjustedDates | None
    ) = Field(
        None,
        alias="cancelableProvisionAdjustedDates",
        description="The adjusted dates associated with a cancelable provision. These dates have been adjusted for any applicable business day convention.",
    )
    final_calculation_period_date_adjustment: (
        list[cdm_product_common_schedule_FinalCalculationPeriodDateAdjustment_schema.FinalCalculationPeriodDateAdjustment] | None
    ) = Field(
        None,
        alias="finalCalculationPeriodDateAdjustment",
        description="Business date convention adjustment to final payment period per leg (swapStream) upon exercise event. The adjustments can be made in-line with leg level BDC's or they can be specified separately.",
        min_length=0,
    )
    initial_fee: cdm_event_common_Transfer_schema.Transfer | None = Field(
        None, alias="initialFee", description="An initial fee for the cancelable option."
    )
    calling_party: cdm_product_template_CallingPartyEnum_schema.CallingPartyEnum | None = Field(
        None, alias="callingParty", description="The party with right to exercise a cancellation. Allows for buyer, seller or either."
    )
    earliest_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None,
        alias="earliestDate",
        description="The first day when cancelation is permitted to take effect. A party may give notice prior to this date and taken together with the effective period would be necessary to cancel on this date.",
    )
    expiration_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None, alias="expirationDate", description="The last day within the term of the contract that cancelation is allowed."
    )
    effective_date: cdm_base_datetime_AdjustableOrRelativeDates_schema.AdjustableOrRelativeDates | None = Field(
        None,
        alias="effectiveDate",
        description="The effective date if cancelation is invoked otherwise the cancellation period defines the cancellation date.",
    )
    effective_period: cdm_base_datetime_Period_schema.Period | None = Field(
        None,
        alias="effectivePeriod",
        description="Effective period for cancelation when notice is given. This is the period after notice is given that cancellation becomes effecticve.",
    )
    earliest_cancellation_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None, alias="earliestCancellationTime", description="The earliest time in a business day that notice of cancelation can be given."
    )
    latest_cancelation_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None, alias="latestCancelationTime", description="The latest time at which notice of cancelation can be given."
    )
    exercise_terms: cdm_product_template_ExerciseTerms_schema.ExerciseTerms = Field(
        ...,
        alias="exerciseTerms",
        description="The exercise terms associated with the cancelable provision, including details such as exercise style, exercise fees, and any other relevant conditions or terms governing the cancellation of the swap transaction.",
    )
