# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-GeneralNonTransferability.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_transaction_additionalterms_EscrowArrangement_schema,
    cdm_legaldocumentation_transaction_additionalterms_FxSubstitutionProvisionTypeEnum_schema,
    cdm_legaldocumentation_transaction_additionalterms_NonDeliverableSubstitute_schema,
    cdm_observable_asset_ValuationPostponement_schema,
)


class GeneralNonTransferability(BaseModel):
    general_non_transferability_is_applicable: bool = Field(..., alias="generalNonTransferabilityIsApplicable")
    local_substitute_provision_type: (
        cdm_legaldocumentation_transaction_additionalterms_FxSubstitutionProvisionTypeEnum_schema.FxSubstitutionProvisionTypeEnum
        | None
    ) = Field(None, alias="localSubstituteProvisionType")
    maximum_days_of_disruption: cdm_observable_asset_ValuationPostponement_schema.ValuationPostponement | None = Field(
        None,
        alias="maximumDaysOfDisruption",
        description="Specifies how long to wait to get a quote from a settlement rate option upon a price source disruption.",
    )
    non_deliverable_substitute: (
        cdm_legaldocumentation_transaction_additionalterms_NonDeliverableSubstitute_schema.NonDeliverableSubstitute
        | None
    ) = Field(None, alias="nonDeliverableSubstitute")
    escrow_arrangement: (
        cdm_legaldocumentation_transaction_additionalterms_EscrowArrangement_schema.EscrowArrangement | None
    ) = Field(
        None,
        alias="escrowArrangement",
        description="Refers to the segregation deposit procedure parties may want to commmit into during the time a Disruption Event is effective",
    )
