# generated by datamodel-codegen:
#   filename:  cdm-product-asset-FloatingRate.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_observable_asset_calculatedrate_FallbackRateParameters_schema,
    cdm_observable_asset_calculatedrate_FloatingRateCalculationParameters_schema,
    cdm_observable_asset_metafields_ReferenceWithMetaInterestRateIndex_schema,
    cdm_product_asset_RateTreatmentEnum_schema,
    cdm_product_asset_SpreadSchedule_schema,
    cdm_product_common_schedule_RateSchedule_schema,
    cdm_product_template_StrikeSchedule_schema,
)


class FloatingRate(BaseModel):
    rate_option: (
        cdm_observable_asset_metafields_ReferenceWithMetaInterestRateIndex_schema.ReferenceWithMetaInterestRateIndex
        | None
    ) = Field(None, alias="rateOption")
    spread_schedule: cdm_product_asset_SpreadSchedule_schema.SpreadSchedule | None = Field(
        None,
        alias="spreadSchedule",
        description="The ISDA Spread or a Spread schedule expressed as explicit spreads and dates. In the case of a schedule, the step dates may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments. The spread is a per annum rate, expressed as a decimal. For purposes of determining a calculation period amount, if positive the spread will be added to the floating rate and if negative the spread will be subtracted from the floating rate. A positive 10 basis point (0.1%) spread would be represented as 0.001.",
    )
    cap_rate_schedule: cdm_product_template_StrikeSchedule_schema.StrikeSchedule | None = Field(
        None,
        alias="capRateSchedule",
        description="The cap rate or cap rate schedule, if any, which applies to the floating rate. The cap rate (strike) is only required where the floating rate on a swap stream is capped at a certain level. A cap rate schedule is expressed as explicit cap rates and dates and the step dates may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments. The cap rate is assumed to be exclusive of any spread and is a per annum rate, expressed as a decimal. A cap rate of 5% would be represented as 0.05.",
    )
    floor_rate_schedule: cdm_product_template_StrikeSchedule_schema.StrikeSchedule | None = Field(
        None,
        alias="floorRateSchedule",
        description="The floor rate or floor rate schedule, if any, which applies to the floating rate. The floor rate (strike) is only required where the floating rate on a swap stream is floored at a certain strike level. A floor rate schedule is expressed as explicit floor rates and dates and the step dates may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments. The floor rate is assumed to be exclusive of any spread and is a per annum rate, expressed as a decimal. A floor rate of 5% would be represented as 0.05.",
    )
    floating_rate_multiplier_schedule: cdm_product_common_schedule_RateSchedule_schema.RateSchedule | None = Field(
        None,
        alias="floatingRateMultiplierSchedule",
        description="A rate multiplier or multiplier schedule to apply to the floating rate. A multiplier schedule is expressed as explicit multipliers and dates. In the case of a schedule, the step dates may be subject to adjustment in accordance with any adjustments specified in the calculationPeriodDatesAdjustments. The multiplier can be a positive or negative decimal. This element should only be included if the multiplier is not equal to 1 (one) for the term of the stream.",
    )
    rate_treatment: cdm_product_asset_RateTreatmentEnum_schema.RateTreatmentEnum | None = Field(
        None,
        alias="rateTreatment",
        description="The specification of any rate conversion which needs to be applied to the observed rate before being used in any calculations. The two common conversions are for securities quoted on a bank discount basis which will need to be converted to either a Money Market Yield or Bond Equivalent Yield. See the Annex to the 2000 ISDA Definitions, Section 7.3. Certain General Definitions Relating to Floating Rate Options, paragraphs (g) and (h) for definitions of these terms.",
    )
    calculation_parameters: (
        cdm_observable_asset_calculatedrate_FloatingRateCalculationParameters_schema.FloatingRateCalculationParameters
        | None
    ) = Field(
        None,
        alias="calculationParameters",
        description="Support for modular calculated rates, such such as lockout compound calculations.",
    )
    fallback_rate: cdm_observable_asset_calculatedrate_FallbackRateParameters_schema.FallbackRateParameters | None = (
        Field(None, alias="fallbackRate", description="Definition of any fallback rate that may be applicable.")
    )
