# generated by datamodel-codegen:
#   filename:  cdm-event-workflow-LimitLevelEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class LimitLevelEnum(StrEnum):
    account = "Account"
    customer = "Customer"
    house = "House"
