# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-ReferenceBank.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import com_rosetta_model_metafields_FieldWithMetaString_schema


class ReferenceBank(BaseModel):
    reference_bank_id: com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString = Field(
        ...,
        alias="referenceBankId",
        description="An institution (party) identifier, e.g. a bank identifier code (BIC). FpML specifies a referenceBankIdScheme.",
    )
    reference_bank_name: str | None = Field(
        None,
        alias="referenceBankName",
        description="The name of the institution (party). A free format string. FpML does not define usage rules for the element.",
    )
