# generated by datamodel-codegen:
#   filename:  cdm-regulation-Prsn.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_regulation_Othr_schema


class Prsn(BaseModel):
    ctry_of_brnch: str = Field(..., alias="ctryOfBrnch")
    othr: cdm_regulation_Othr_schema.Othr
