# generated by datamodel-codegen:
#   filename:  cdm-event-position-InventoryRecord.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_asset_common_Security_schema, cdm_base_staticdata_identifier_AssignedIdentifier_schema


class InventoryRecord(BaseModel):
    identifer: cdm_base_staticdata_identifier_AssignedIdentifier_schema.AssignedIdentifier = Field(
        ..., description="Unique identifier for this record. This can be used to uniquely identify a specific piece of inventory."
    )
    security: cdm_base_staticdata_asset_common_Security_schema.Security = Field(..., description="The security details.")
