# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-SimmException.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_csa_ExceptionEnum_schema,
    cdm_legaldocumentation_csa_SimmExceptionApplicableEnum_schema,
)


class SimmException(BaseModel):
    standardised_exception: cdm_legaldocumentation_csa_ExceptionEnum_schema.ExceptionEnum | None = Field(
        None,
        alias="standardisedException",
        description="The Standard Initial Margin Model exception when specified by the party according to one of the enumerated values.",
    )
    simm_exception_applicable: (
        cdm_legaldocumentation_csa_SimmExceptionApplicableEnum_schema.SimmExceptionApplicableEnum | None
    ) = Field(
        None,
        alias="simmExceptionApplicable",
        description="The Standard Initial Margin model exception approach applicable when specified by the party according to one of the enumerated values.",
    )
    as_specified: str | None = Field(
        None,
        alias="asSpecified",
        description="The Standard Initial Margin Model exception when specified as a customized approach by the party.",
    )
