# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ExposureScope.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_LegacyExposureScopeElection_schema


class ExposureScope(BaseModel):
    party_election: list[cdm_legaldocumentation_csa_LegacyExposureScopeElection_schema.LegacyExposureScopeElection] | None = Field(
        None, alias="partyElection", description="Defines the electice scope for a specific party.", max_length=2, min_length=0
    )
