# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-PremiumTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class PremiumTypeEnum(StrEnum):
    fixed = "Fixed"
    post_paid = "PostPaid"
    pre_paid = "PrePaid"
    variable = "Variable"
