# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-SwapCurveValuation.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_Period_schema,
    cdm_base_staticdata_asset_rates_FloatingRateIndexEnum_schema,
    cdm_observable_asset_QuotationSideEnum_schema,
)


class SwapCurveValuation(BaseModel):
    floating_rate_index: cdm_base_staticdata_asset_rates_FloatingRateIndexEnum_schema.FloatingRateIndexEnum = Field(
        ..., alias="floatingRateIndex"
    )
    index_tenor: cdm_base_datetime_Period_schema.Period | None = Field(
        None, alias="indexTenor", description="The ISDA Designated Maturity, i.e. the tenor of the floating rate."
    )
    spread: float = Field(..., description="Spread in basis points over the floating rate index.")
    side: cdm_observable_asset_QuotationSideEnum_schema.QuotationSideEnum | None = Field(
        None, description="The side (bid/mid/ask) of the measure."
    )
