# generated by datamodel-codegen:
#   filename:  cdm-event-workflow-CreditLimitUtilisationPosition.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class CreditLimitUtilisationPosition(BaseModel):
    short_position: float | None = Field(
        None, alias="shortPosition", description="Credit limit utilisation attributable to short positions."
    )
    long_position: float | None = Field(
        None, alias="longPosition", description="Credit limit utilisation attributable to long positions."
    )
    global_: float | None = Field(
        None,
        alias="global",
        description="Global credit limit utilisation amount, agnostic of long/short position direction.",
    )
