# generated by datamodel-codegen:
#   filename:  cdm-product-asset-BasketReferenceInformation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_product_asset_ReferencePool_schema,
    cdm_product_asset_Tranche_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class BasketReferenceInformation(BaseModel):
    basket_name: (
        com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString | None
    ) = Field(
        None,
        alias="basketName",
        description="The name of the basket expressed as a free format string. FpML does not define usage rules for this element.",
    )
    basket_id: (
        list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None
    ) = Field(None, alias="basketId", description="A CDS basket identifier.", min_length=0)
    reference_pool: cdm_product_asset_ReferencePool_schema.ReferencePool = Field(
        ...,
        alias="referencePool",
        description="This element contains all the reference pool items to define the reference entity and reference obligation(s) in the basket.",
    )
    nth_to_default: int | None = Field(
        None,
        alias="nthToDefault",
        description="N th reference obligation to default triggers payout.",
    )
    mth_to_default: int | None = Field(
        None,
        alias="mthToDefault",
        description="M th reference obligation to default to allow representation of N th to M th defaults.",
    )
    tranche: cdm_product_asset_Tranche_schema.Tranche | None = Field(
        None, description="This element contains CDS tranche terms."
    )
