# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-DeliveryMethodEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DeliveryMethodEnum(StrEnum):
    delivery_versus_payment = "DeliveryVersusPayment"
    free_of_payment = "FreeOfPayment"
    pre_delivery = "PreDelivery"
    pre_payment = "PrePayment"
