# generated by datamodel-codegen:
#   filename:  cdm-regulation-Term.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel


class Term(BaseModel):
    unit: str
    val: str
