# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-AdditionalObligations.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_CounterpartyRoleEnum_schema


class AdditionalObligations(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The party that the additional obligations apply to."
    )
    additional_obligations: str = Field(
        ...,
        alias="additionalObligations",
        description="The party specific additional obligations applicable to the agreement.",
    )
