# generated by datamodel-codegen:
#   filename:  cdm-product-asset-ReferencePool.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_product_asset_ReferencePoolItem_schema


class ReferencePool(BaseModel):
    reference_pool_item: list[cdm_product_asset_ReferencePoolItem_schema.ReferencePoolItem] | None = Field(
        None,
        alias="referencePoolItem",
        description="This type contains all the constituent weight and reference information.",
        min_length=1,
    )
