# generated by datamodel-codegen:
#   filename:  cdm-event-common-ObservationInstruction.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_ObservationEvent_schema


class ObservationInstruction(BaseModel):
    observation_event: cdm_event_common_ObservationEvent_schema.ObservationEvent = Field(
        ..., alias="observationEvent", description="Contains all information related to an observation."
    )
