# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-metafields-FieldWithMetaPersonIdentifier.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import (
    cdm_base_staticdata_party_PersonIdentifier_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class FieldWithMetaPersonIdentifier(BaseModel):
    value: cdm_base_staticdata_party_PersonIdentifier_schema.PersonIdentifier | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
