# generated by datamodel-codegen:
#   filename:  cdm-event-common-RegMarginTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class RegMarginTypeEnum(StrEnum):
    NON_REG_IM = "NonRegIM"
    REG_IM = "RegIM"
    VM = "VM"
