# generated by datamodel-codegen:
#   filename:  cdm-product-template-StrikeSpread.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_product_template_OptionStrike_schema


class StrikeSpread(BaseModel):
    upper_strike: cdm_product_template_OptionStrike_schema.OptionStrike = Field(
        ..., alias="upperStrike", description="Upper strike in a strike spread."
    )
    upper_strike_number_of_options: float = Field(
        ..., alias="upperStrikeNumberOfOptions", description="Number of options at the upper strike price in a strike spread."
    )
