# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-party-AncillaryParty.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_AncillaryRoleEnum_schema,
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_base_staticdata_party_metafields_ReferenceWithMetaParty_schema,
)


class AncillaryParty(BaseModel):
    role: cdm_base_staticdata_party_AncillaryRoleEnum_schema.AncillaryRoleEnum = Field(
        ...,
        description="Specifies the AncillaryRoleEnum that is associated to the party reference. An ancillary party is any involved party that is not one of the two principal parties to the transaction.",
    )
    party_reference: list[cdm_base_staticdata_party_metafields_ReferenceWithMetaParty_schema.ReferenceWithMetaParty] | None = Field(
        None, alias="partyReference", description="Specifies the party, or parties, associated to the ancillary role.", min_length=1
    )
    on_behalf_of: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum | None = Field(
        None, alias="onBehalfOf", description="Optionally specifies the counterparty that the ancillary party is acting on behalf of."
    )
