# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-CalculationPeriodBase.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class CalculationPeriodBase(BaseModel):
    adjusted_start_date: str | None = Field(
        None,
        alias="adjustedStartDate",
        description="The calculation period start date, adjusted according to any relevant business day convention.",
    )
    adjusted_end_date: str | None = Field(
        None,
        alias="adjustedEndDate",
        description="The calculation period end date, adjusted according to any relevant business day convention.",
    )
