# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-CreditSupportProviderTermsEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class CreditSupportProviderTermsEnum(StrEnum):
    ANY = "Any"
    NONE = "None"
    SPECIFIED = "Specified"
