# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-InterpolationMethodEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class InterpolationMethodEnum(StrEnum):
    linear = "Linear"
    linear_zero_yield = "LinearZeroYield"
    none = "None"
