# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-calculatedrate-ObservationParameters.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field


class ObservationParameters(BaseModel):
    observation_cap_rate: float | None = Field(None, alias="observationCapRate", description="A daily observation cap rate.")
    observation_floor_rate: float | None = Field(None, alias="observationFloorRate", description="A daily observation floor rate.")
