# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-CreditSupportAmountEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CreditSupportAmountEnum(StrEnum):
    non_standard___ia_floor__less_giver_ia_ = "Non-Standard - IA Floor (Less GiverIA)"
    non_standard___ia_floor__less_giver_ia_and_taker_ia_ = "Non-Standard - IA Floor (Less GiverIA and TakerIA)"
    non_standard___other = "Non-Standard - Other"
    non_standard___ratings = "Non-Standard - Ratings"
    standard = "Standard"
