# generated by datamodel-codegen:
#   filename:  cdm-observable-event-TriggerTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class TriggerTypeEnum(StrEnum):
    equal = "Equal"
    equal_or_greater = "EqualOrGreater"
    equal_or_less = "EqualOrLess"
    greater = "Greater"
    less = "Less"
