# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-metafields-FieldWithMetaResourceTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_legaldocumentation_common_ResourceTypeEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaResourceTypeEnum(BaseModel):
    value: cdm_legaldocumentation_common_ResourceTypeEnum_schema.ResourceTypeEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
