# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-HoldingPostedCollateralEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class HoldingPostedCollateralEnum(StrEnum):
    acceptable_custodian = "AcceptableCustodian"
