# generated by datamodel-codegen:
#   filename:  cdm-product-asset-ReferencePair.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_LegalEntity_schema,
    cdm_base_staticdata_party_metafields_FieldWithMetaEntityTypeEnum_schema,
    cdm_product_asset_ReferenceObligation_schema,
)


class ReferencePair(BaseModel):
    reference_entity: cdm_base_staticdata_party_LegalEntity_schema.LegalEntity = Field(
        ...,
        alias="referenceEntity",
        description="The corporate or sovereign entity on which you are buying or selling protection and any successor that assumes all or substantially all of its contractual and other obligations. It is vital to use the correct legal name of the entity and to be careful not to choose a subsidiary if you really want to trade protection on a parent company. Please note, Reference Entities cannot be senior or subordinated. It is the obligations of the Reference Entities that can be senior or subordinated. ISDA 2003 Term: Reference Entity.",
    )
    reference_obligation: cdm_product_asset_ReferenceObligation_schema.ReferenceObligation | None = Field(
        None,
        alias="referenceObligation",
        description="The Reference Obligation is a financial instrument that is either issued or guaranteed by the reference entity. It serves to clarify the precise reference entity protection is being offered upon, and its legal position with regard to other related firms (parents/subsidiaries). Furthermore the Reference Obligation is ALWAYS deliverable and establishes the Pari Passu ranking (as the deliverable bonds must rank equal to the reference obligation). ISDA 2003 Term: Reference Obligation.",
    )
    no_reference_obligation: bool | None = Field(
        None,
        alias="noReferenceObligation",
        description="Used to indicate that there is no Reference Obligation associated with this Credit Default Swap and that there will never be one.",
    )
    entity_type: cdm_base_staticdata_party_metafields_FieldWithMetaEntityTypeEnum_schema.FieldWithMetaEntityTypeEnum = Field(
        ...,
        alias="entityType",
        description="Defines the reference entity types corresponding to a list of types in the ISDA First to Default documentation.",
    )
