# generated by datamodel-codegen:
#   filename:  cdm-regulation-Document.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_regulation_FinInstrmRptgTxRpt_schema


class Document(BaseModel):
    fin_instrm_rptg_tx_rpt: cdm_regulation_FinInstrmRptgTxRpt_schema.FinInstrmRptgTxRpt = Field(
        ..., alias="finInstrmRptgTxRpt"
    )
