# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ElectiveAmountElection.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_party_CounterpartyRoleEnum_schema,
    cdm_legaldocumentation_csa_ElectiveAmountEnum_schema,
    cdm_observable_asset_Money_schema,
)


class ElectiveAmountElection(BaseModel):
    party: cdm_base_staticdata_party_CounterpartyRoleEnum_schema.CounterpartyRoleEnum = Field(
        ..., description="The elective party."
    )
    elective_amount: cdm_legaldocumentation_csa_ElectiveAmountEnum_schema.ElectiveAmountEnum | None = Field(
        None, alias="electiveAmount", description="Specifies an enumerated election to express the elective amount."
    )
    amount: cdm_observable_asset_Money_schema.Money | None = Field(
        None,
        description="The elective amount when expressed as a currency amount. The associated PartyElectiveAmount_amount data rule enforces that the currency amount is actually greater than 0.",
    )
    custom_election: str | None = Field(
        None,
        alias="customElection",
        description="The elective amount when expressed as a custom election by the party.",
    )
