# generated by datamodel-codegen:
#   filename:  cdm-margin-schedule-StandardizedScheduleAssetClassEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class StandardizedScheduleAssetClassEnum(StrEnum):
    COMMODITY = "Commodity"
    CREDIT = "Credit"
    EQUITY = "Equity"
    FOREIGN_EXCHANGE = "ForeignExchange"
    INTEREST_RATES = "InterestRates"
