# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-CollateralTaxonomyValue.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_EU_EMIR_EligibleCollateralEnum_schema,
    cdm_base_staticdata_asset_common_UK_EMIR_EligibleCollateralEnum_schema,
    cdm_base_staticdata_asset_common_US_CFTC_PR_EligibleCollateralEnum_schema,
    com_rosetta_model_metafields_FieldWithMetaString_schema,
)


class CollateralTaxonomyValue(BaseModel):
    eu_emir_eligible_collateral: (
        list[
            cdm_base_staticdata_asset_common_EU_EMIR_EligibleCollateralEnum_schema.EUEMIREligibleCollateralEnum
        ]
        | None
    ) = Field(
        None,
        alias="eu_EMIR_EligibleCollateral",
        description="Identifies European Union Eligible Collateral Assets classification categories based on EMIR Uncleared Margin Rules. Eligible Collateral asset classes for both initial margin (IM) and variation margin (VM) posted and collected between specified entities. Please note: EMIR regulation will detail which eligible collateral assets classes apply to each type of entity pairing (counterparty) and which apply to posting of IM and VM",
        min_length=0,
    )
    uk_emir_eligible_collateral: (
        list[
            cdm_base_staticdata_asset_common_UK_EMIR_EligibleCollateralEnum_schema.UKEMIREligibleCollateralEnum
        ]
        | None
    ) = Field(
        None,
        alias="uk_EMIR_EligibleCollateral",
        description="Identifies United Kingdom Eligible Collateral Assets classification categories based on UK Onshored EMIR Uncleared Margin Rules Eligible Collateral asset classes for both initial margin (IM) and variation margin (VM) posted and collected between specified entities. Please note: UK EMIR regulation will detail which eligible collateral assets classes apply to each type of entity pairing (counterparty) and which apply to posting of IM and VM.",
        min_length=0,
    )
    us_cftc_pr_eligible_collateral: (
        list[
            cdm_base_staticdata_asset_common_US_CFTC_PR_EligibleCollateralEnum_schema.USCFTCPREligibleCollateralEnum
        ]
        | None
    ) = Field(
        None,
        alias="us_CFTC_PR_EligibleCollateral",
        description="Identifies US Eligible Collateral Assets classification categories based on Uncleared Margin Rules published by the CFTC and the US Prudential Regulator. Note: While the same basic categories exist in the CFTC and US Prudential Regulators’ margin rules, the precise definitions or application of those rules could differ between the two rules.",
        min_length=0,
    )
    non_enumerated_taxonomy_value: (
        list[com_rosetta_model_metafields_FieldWithMetaString_schema.FieldWithMetaString] | None
    ) = Field(
        None,
        alias="nonEnumeratedTaxonomyValue",
        description="Identifies the taxonomy value when not specified as an enumeration.",
        min_length=0,
    )
