# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-BespokeCalculationDate.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field


class BespokeCalculationDate(BaseModel):
    is_applicable: bool = Field(
        ..., alias="isApplicable", description="Additional Calculation Date terms are applicable when True and not applicable when False."
    )
    calculation_date_im_terms: str | None = Field(
        None, alias="calculationDateImTerms", description="The Additional Calculation Date terms for the purposes of Initial Margin."
    )
