# generated by datamodel-codegen:
#   filename:  cdm-product-template-ExerciseTerms.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AdjustableOrRelativeDate_schema,
    cdm_base_datetime_AdjustableOrRelativeDates_schema,
    cdm_base_datetime_BusinessCenterTime_schema,
    cdm_product_template_ExerciseFeeSchedule_schema,
    cdm_product_template_ExerciseFee_schema,
    cdm_product_template_ExerciseProcedure_schema,
    cdm_product_template_ExpirationTimeTypeEnum_schema,
    cdm_product_template_MultipleExercise_schema,
    cdm_product_template_OptionExerciseStyleEnum_schema,
    cdm_product_template_PartialExercise_schema,
)


class ExerciseTerms(BaseModel):
    style: cdm_product_template_OptionExerciseStyleEnum_schema.OptionExerciseStyleEnum | None = Field(
        None,
        description="Whether the option has a single exercise (european), multiple exercise dates (bermuda), or a continuous range of exercise (american).",
    )
    commencement_date: cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate | None = Field(
        None, alias="commencementDate", description="The first day of the exercise period for an American style option."
    )
    exercise_dates: cdm_base_datetime_AdjustableOrRelativeDates_schema.AdjustableOrRelativeDates | None = Field(
        None,
        alias="exerciseDates",
        description="The dates that define the Bermuda option exercise dates and the expiration date. The last specified date is assumed to be the expiration date. The dates can either be specified as a series of explicit dates and associated adjustments or as a series of dates defined relative to another schedule of dates, for example, the calculation period start dates. Where a relative series of dates are defined the first and last possible exercise dates can be separately specified.",
    )
    expiration_date: list[cdm_base_datetime_AdjustableOrRelativeDate_schema.AdjustableOrRelativeDate] | None = Field(
        None,
        alias="expirationDate",
        description="The last day within an exercise period for an American style option. For a European style option it is the only day within the exercise period.",
        min_length=0,
    )
    relevant_underlying_date: cdm_base_datetime_AdjustableOrRelativeDates_schema.AdjustableOrRelativeDates | None = Field(
        None,
        alias="relevantUnderlyingDate",
        description="The effective date on the underlying product if the option is exercised.  For example, for a swaption it is the swap effective date, for an option on an FX spot or forward it is the value date for settlement, and in an extendible/cancelable provision it is the swap termination date, which is the date on which the termination is effective.'",
    )
    earliest_exercise_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None,
        alias="earliestExerciseTime",
        description="The earliest time at which notice of exercise can be given by the buyer to the seller (or seller's agent) to, and including, the expiration date.",
    )
    latest_exercise_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None,
        alias="latestExerciseTime",
        description="For a Bermuda or American style option, the latest time on an exercise business day (excluding the expiration date) within the exercise period that notice can be given by the buyer to the seller or seller's agent. Notice of exercise given after this time will be deemed to have been given on the next exercise business day.",
    )
    expiration_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None,
        alias="expirationTime",
        description="The latest time for exercise on expirationDate. It is made mandatory given that for all option styles, this field is required.",
    )
    expiration_time_type: cdm_product_template_ExpirationTimeTypeEnum_schema.ExpirationTimeTypeEnum = Field(
        ...,
        alias="expirationTimeType",
        description="The time of day at which the equity option expires, for example the official closing time of the exchange.",
    )
    multiple_exercise: cdm_product_template_MultipleExercise_schema.MultipleExercise | None = Field(
        None,
        alias="multipleExercise",
        description="As defined in the 2000 ISDA Definitions, Section 12.4. Multiple Exercise, the buyer of the option has the right to exercise all or less than all the unexercised notional amount of the underlying swap on one or more days in the exercise period, but on any such day may not exercise less than the minimum notional amount or more that the maximum notional amount, and if an integral multiple amount is specified, the notional amount exercised must be equal to, or be an integral multiple of, the integral multiple amount.",
    )
    exercise_fee_schedule: cdm_product_template_ExerciseFeeSchedule_schema.ExerciseFeeSchedule | None = Field(
        None,
        alias="exerciseFeeSchedule",
        description="The fees associated with an exercise date. The fees are conditional on the exercise occurring. The fees can be specified as actual currency amounts or as percentages of the notional amount being exercised.",
    )
    exercise_procedure: cdm_product_template_ExerciseProcedure_schema.ExerciseProcedure | None = Field(
        None,
        alias="exerciseProcedure",
        description="The set of parameters defining the procedure associated with the exercise, e.g. manual exercise.",
    )
    exercise_fee: cdm_product_template_ExerciseFee_schema.ExerciseFee | None = Field(
        None,
        alias="exerciseFee",
        description="A fee to be paid on exercise. This could be represented as an amount or a rate and notional reference on which to apply the rate.",
    )
    partial_exercise: cdm_product_template_PartialExercise_schema.PartialExercise | None = Field(
        None,
        alias="partialExercise",
        description="As defined in the 2000 ISDA Definitions, Section 12.3. Partial Exercise, the buyer of the option has the right to exercise all or less than all the notional amount of the underlying swap on the expiration date, but may not exercise less than the minimum notional amount, and if an integral multiple amount is specified, the notional amount exercised must be equal to, or be an integral multiple of, the integral multiple amount.",
    )
