# generated by datamodel-codegen:
#   filename:  cdm-product-template-CalculationSchedule.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_template_SchedulePeriod_schema


class CalculationSchedule(BaseModel):
    schedule_period: list[cdm_product_template_SchedulePeriod_schema.SchedulePeriod] | None = Field(
        None, alias="schedulePeriod", description="Defines a period of a calculation schedule structure.", min_length=1
    )
