# generated by datamodel-codegen:
#   filename:  cdm-event-common-MarginCallResponseTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class MarginCallResponseTypeEnum(StrEnum):
    AGREEIN_FULL = "AgreeinFull"
    DISPUTE = "Dispute"
    PARTIALLY_AGREE = "PartiallyAgree"
