# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-DayOfWeekEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DayOfWeekEnum(StrEnum):
    fri = "FRI"
    mon = "MON"
    sat = "SAT"
    sun = "SUN"
    thu = "THU"
    tue = "TUE"
    wed = "WED"
