# generated by datamodel-codegen:
#   filename:  cdm-regulation-ExctgPrsn.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_regulation_Prsn_schema


class ExctgPrsn(BaseModel):
    prsn: cdm_regulation_Prsn_schema.Prsn
