# generated by datamodel-codegen:
#   filename:  cdm-observable-common-TimeTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class TimeTypeEnum(StrEnum):
    AS_SPECIFIED_IN_MASTER_CONFIRMATION = "AsSpecifiedInMasterConfirmation"
    CLOSE = "Close"
    DERIVATIVES_CLOSE = "DerivativesClose"
    OSP = "OSP"
    OPEN = "Open"
    SPECIFIC_TIME = "SpecificTime"
    XETRA = "XETRA"
