# generated by datamodel-codegen:
#   filename:  cdm-product-common-schedule-ObservationTerms.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_BusinessCenterTime_schema,
    cdm_base_math_Rounding_schema,
    cdm_observable_asset_FxSpotRateSource_schema,
    cdm_observable_common_TimeTypeEnum_schema,
    cdm_product_common_schedule_CalculationPeriodDates_schema,
    cdm_product_common_schedule_ObservationDates_schema,
)


class ObservationTerms(BaseModel):
    observation_time: cdm_base_datetime_BusinessCenterTime_schema.BusinessCenterTime | None = Field(
        None,
        alias="observationTime",
        description="Defines time in respect to a business calendar location that the price/benchmark/index is observed",
    )
    observation_time_type: cdm_observable_common_TimeTypeEnum_schema.TimeTypeEnum | None = Field(
        None,
        alias="observationTimeType",
        description="The enumerated values to specify points in the day when option exercise and valuation can occur.",
    )
    information_source: cdm_observable_asset_FxSpotRateSource_schema.FxSpotRateSource | None = (
        Field(
            None,
            alias="informationSource",
            description="The information source where a published or displayed market rate will be obtained, e.g. Telerate Page 3750.",
        )
    )
    precision: cdm_base_math_Rounding_schema.Rounding | None = Field(
        None,
        description="Defines rounding rules and precision to be used in the rounding of observations.",
    )
    calculation_period_dates: (
        cdm_product_common_schedule_CalculationPeriodDates_schema.CalculationPeriodDates | None
    ) = Field(
        None,
        alias="calculationPeriodDates",
        description="Defines parameters used to generate the calculation period dates schedule, including the specification of any initial or final stub calculation periods. A calculation period schedule consists of an optional initial stub calculation period, one or more regular calculation periods and an optional final stub calculation period. In the absence of any initial or final stub calculation periods, the regular part of the calculation period schedule is assumed to be between the effective date and the termination date. No implicit stubs are allowed, i.e. stubs must be explicitly specified using an appropriate combination of firstPeriodStartDate, firstRegularPeriodStartDate and lastRegularPeriodEndDate.",
    )
    observation_dates: cdm_product_common_schedule_ObservationDates_schema.ObservationDates = Field(
        ...,
        alias="observationDates",
        description="Describes date details for a set of observation dates in parametric or non-parametric form.",
    )
    number_of_observation_dates: int | None = Field(
        None,
        alias="numberOfObservationDates",
        description="The number of observation dates between observation start date and observation end date.",
    )
