# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-ConcentrationLimit.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_math_MoneyRange_schema,
    cdm_base_math_NumberRange_schema,
    cdm_product_collateral_ConcentrationLimitCriteria_schema,
)


class ConcentrationLimit(BaseModel):
    concentration_limit_criteria: (
        cdm_product_collateral_ConcentrationLimitCriteria_schema.ConcentrationLimitCriteria | None
    ) = Field(
        None,
        alias="concentrationLimitCriteria",
        description="Specifies a set of criteria to describe the assets that the concentration limits apply to.",
    )
    value_limit: cdm_base_math_MoneyRange_schema.MoneyRange | None = Field(
        None, alias="valueLimit", description="Specifies the value of collateral limit represented as a range."
    )
    percentage_limit: cdm_base_math_NumberRange_schema.NumberRange | None = Field(
        None,
        alias="percentageLimit",
        description="Specifies the perecentage of collateral limit represented as a decimal number - example 25% is 0.25.",
    )
