# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-fro-FloatingRateIndexMap.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_rates_FloatingRateIndexEnum_schema,
    cdm_base_staticdata_identifier_Identifier_schema,
    cdm_observable_asset_fro_ContractualDefinitionIdentifier_schema,
)


class FloatingRateIndexMap(BaseModel):
    index: list[cdm_base_staticdata_asset_rates_FloatingRateIndexEnum_schema.FloatingRateIndexEnum] | None = Field(
        None, description=" The FRO name that is being mapped to/from.", min_length=0
    )
    contractual_definition_identifier: (
        cdm_observable_asset_fro_ContractualDefinitionIdentifier_schema.ContractualDefinitionIdentifier | None
    ) = Field(
        None,
        alias="contractualDefinitionIdentifier",
        description="Contractual Definition to which the map applies. Includes Document Type and Document Version",
    )
    identifier: cdm_base_staticdata_identifier_Identifier_schema.Identifier | None = Field(
        None, description="Corresponds to the unique identifier of the Contractual Definition to which the map applies"
    )
