# generated by datamodel-codegen:
#   filename:  cdm-observable-event-TriggerEvent.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_AveragingSchedule_schema,
    cdm_base_datetime_DateList_schema,
    cdm_observable_event_FeaturePayment_schema,
    cdm_observable_event_Trigger_schema,
)


class TriggerEvent(BaseModel):
    schedule: list[cdm_base_datetime_AveragingSchedule_schema.AveragingSchedule] | None = Field(
        None, description="A derivative schedule.", min_length=0
    )
    trigger_dates: cdm_base_datetime_DateList_schema.DateList | None = Field(None, alias="triggerDates", description="The trigger Dates.")
    trigger: cdm_observable_event_Trigger_schema.Trigger = Field(..., description="The trigger level")
    feature_payment: cdm_observable_event_FeaturePayment_schema.FeaturePayment | None = Field(
        None, alias="featurePayment", description="The feature payment, i.e. the payment made following trigger occurrence."
    )
