# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-AdditionalDisruptionEvents.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_AncillaryRoleEnum_schema, cdm_legaldocumentation_transaction_Clause_schema


class AdditionalDisruptionEvents(BaseModel):
    change_in_law: bool | None = Field(None, alias="changeInLaw")
    failure_to_deliver: bool | None = Field(None, alias="failureToDeliver")
    insolvency_filing: bool | None = Field(None, alias="insolvencyFiling")
    hedging_disruption: bool | None = Field(None, alias="hedgingDisruption")
    increased_cost_of_hedging: bool | None = Field(None, alias="increasedCostOfHedging")
    foreign_ownership_event: bool | None = Field(None, alias="foreignOwnershipEvent")
    loss_of_stock_borrow: bool | None = Field(None, alias="lossOfStockBorrow")
    maximum_stock_loan_rate: float | None = Field(
        None,
        alias="maximumStockLoanRate",
        description="Specifies the maximum stock loan rate for Loss of Stock Borrow. A percentage of 5% is represented as 0.05.",
    )
    increased_cost_of_stock_borrow: bool | None = Field(None, alias="increasedCostOfStockBorrow")
    initial_stock_loan_rate: float | None = Field(
        None,
        alias="initialStockLoanRate",
        description="Specifies the initial stock loan per ISDA Def. A percentage of 5% is represented as 0.05.",
    )
    determining_party: cdm_base_staticdata_party_AncillaryRoleEnum_schema.AncillaryRoleEnum | None = Field(
        None, alias="determiningParty", description="Specifies the party which determines additional disruption events."
    )
    additional_bespoke_terms: list[cdm_legaldocumentation_transaction_Clause_schema.Clause] | None = Field(
        None,
        alias="additionalBespokeTerms",
        description="Where parties may optionnaly describe any extra bespoke agreements, in regards of the standardized Extraordinary Events.",
        min_length=0,
    )
