# generated by datamodel-codegen:
#   filename:  cdm-event-common-Instruction.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from ._internal import PrimitiveInstruction
from . import cdm_event_common_metafields_ReferenceWithMetaTradeState_schema


class Instruction(BaseModel):
    primitive_instruction: PrimitiveInstruction | None = Field(
        None,
        alias="primitiveInstruction",
        description="Specifies the primitive instructions that will be used to call primitive event functions.",
    )
    before: (
        cdm_event_common_metafields_ReferenceWithMetaTradeState_schema.ReferenceWithMetaTradeState
        | None
    ) = Field(
        None,
        description="Specifies the trade state that will be acted on by the primitive event functions.",
    )
