# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-PutCallEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class PutCallEnum(StrEnum):
    call = "Call"
    put = "Put"
