# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-SpecifiedEntityTermsEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class SpecifiedEntityTermsEnum(StrEnum):
    ANY_AFFILIATE = "AnyAffiliate"
    MATERIAL_SUBSIDIARY = "MaterialSubsidiary"
    NAMED_SPECIFIED_ENTITY = "NamedSpecifiedEntity"
    NONE = "None"
    OTHER_SPECIFIED_ENTITY = "OtherSpecifiedEntity"
