# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-QuotationRateTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class QuotationRateTypeEnum(StrEnum):
    ASK = "Ask"
    BID = "Bid"
    EXERCISING_PARTY_PAYS = "ExercisingPartyPays"
    MID = "Mid"
