# generated by datamodel-codegen:
#   filename:  cdm-product-asset-floatingrate-FloatingRateProcessingDetails.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_asset_floatingrate_FloatingRateProcessingParameters_schema


class FloatingRateProcessingDetails(BaseModel):
    raw_rate: float = Field(
        ..., alias="rawRate", description="The raw or untreated rate, prior to any of the rate treatments."
    )
    processing_parameters: (
        cdm_product_asset_floatingrate_FloatingRateProcessingParameters_schema.FloatingRateProcessingParameters | None
    ) = Field(None, alias="processingParameters")
    processed_rate: float = Field(..., alias="processedRate", description="The value of the rate after processing.")
    spread_exclusive_rate: float = Field(
        ...,
        alias="spreadExclusiveRate",
        description="The value of the processed rate without the spread applied, for subsequent compounding, etc.",
    )
