# generated by datamodel-codegen:
#   filename:  cdm-product-asset-DividendDateReferenceEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DividendDateReferenceEnum(StrEnum):
    ad_hoc_date = "AdHocDate"
    cash_settle_payment_date_ex_div = "CashSettlePaymentDateExDiv"
    cash_settle_payment_date_issuer_payment = "CashSettlePaymentDateIssuerPayment"
    cash_settlement_payment_date = "CashSettlementPaymentDate"
    cumulative_equity_ex_div = "CumulativeEquityExDiv"
    cumulative_equity_ex_div_before_reset = "CumulativeEquityExDivBeforeReset"
    cumulative_equity_paid = "CumulativeEquityPaid"
    cumulative_equity_paid_before_reset = "CumulativeEquityPaidBeforeReset"
    cumulative_equity_paid_incl_reset = "CumulativeEquityPaidInclReset"
    cumulative_interest_ex_div = "CumulativeInterestExDiv"
    cumulative_interest_paid = "CumulativeInterestPaid"
    cumulative_interest_paid_before_reset = "CumulativeInterestPaidBeforeReset"
    cumulative_interest_paid_incl_reset = "CumulativeInterestPaidInclReset"
    dividend_payment_date = "DividendPaymentDate"
    dividend_valuation_date = "DividendValuationDate"
    equity_payment_date = "EquityPaymentDate"
    ex_date = "ExDate"
    floating_amount_payment_date = "FloatingAmountPaymentDate"
    following_payment_date = "FollowingPaymentDate"
    record_date = "RecordDate"
    share_payment = "SharePayment"
    termination_date = "TerminationDate"
    trade_date = "TradeDate"
    unwind_ex_div = "UnwindExDiv"
    unwind_or_equity_ex_div = "UnwindOrEquityExDiv"
    unwind_or_equity_paid = "UnwindOrEquityPaid"
    unwind_or_interest_ex_div = "UnwindOrInterestExDiv"
    unwind_or_interest_paid = "UnwindOrInterestPaid"
    unwind_paid = "UnwindPaid"
