# generated by datamodel-codegen:
#   filename:  cdm-observable-event-RestructuringEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class RestructuringEnum(StrEnum):
    mod_mod_r = "ModModR"
    mod_r = "ModR"
    r = "R"
