# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-Substitution.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_LegacyConsentEnum_schema


class Substitution(BaseModel):
    needs_consent: bool = Field(
        ...,
        alias="needsConsent",
        description="The election as to whether the Pledgor/Obligor/Chargor must obtain the Secured Partys consent for any collateral substitution.",
    )
    substitution_date_language: str | None = Field(
        None,
        alias="substitutionDateLanguage",
        description="Substitution Date has the meaning specified in Paragraph4(d)(ii), unless otherwise specified.",
    )
    specific_consent_language: str | None = Field(
        None, alias="specificConsentLanguage", description="Specific consent language might be specified by the parties."
    )
    legacy_consent: cdm_legaldocumentation_csa_LegacyConsentEnum_schema.LegacyConsentEnum | None = Field(
        None,
        alias="legacyConsent",
        description="The process for substituting/exchanging one form of collateral held by a party for a different form of collateral, used with legacy agreements.",
    )
