# generated by datamodel-codegen:
#   filename:  cdm-product-asset-floatingrate-FloatingRateIndexProcessingTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class FloatingRateIndexProcessingTypeEnum(StrEnum):
    COMPOUND_INDEX = "CompoundIndex"
    MODULAR = "Modular"
    OIS = "OIS"
    OVERNIGHT_AVG = "OvernightAvg"
    REF_BANKS = "RefBanks"
    SCREEN = "Screen"
