# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-TaxonomySourceEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class TaxonomySourceEnum(StrEnum):
    CFI = "CFI"
    CFTC = "CFTC"
    CSA = "CSA"
    EMIR = "EMIR"
    EU_EMIR_ELIGIBLE_COLLATERAL_ASSET_CLASS = "EU_EMIR_EligibleCollateralAssetClass"
    ICAD = "ICAD"
    ISDA = "ISDA"
    MAS = "MAS"
    OTHER = "Other"
    UK_EMIR_ELIGIBLE_COLLATERAL_ASSET_CLASS = "UK_EMIR_EligibleCollateralAssetClass"
    US_CFTC_PR_ELIGIBLE_COLLATERAL_ASSET_CLASS = "US_CFTC_PR_EligibleCollateralAssetClass"
