# generated by datamodel-codegen:
#   filename:  cdm-product-asset-floatingrate-FloatingRateIndexProcessingTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class FloatingRateIndexProcessingTypeEnum(StrEnum):
    compound_index = "CompoundIndex"
    modular = "Modular"
    ois = "OIS"
    overnight_avg = "OvernightAvg"
    ref_banks = "RefBanks"
    screen = "Screen"
