# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RetrospectiveEffect.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_ExceptionEnum_schema


class RetrospectiveEffect(BaseModel):
    standardised_exception: cdm_legaldocumentation_csa_ExceptionEnum_schema.ExceptionEnum | None = Field(
        None,
        alias="standardisedException",
        description="The Standard Initial Margin Model exception when specified by the party according to one of the enumerated values.",
    )
    as_specified: str | None = Field(
        None,
        alias="asSpecified",
        description="The Standard Initial Margin Model exception when specified as a customized approach by the party.",
    )
