# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyResolutionAlternativeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class LegacyResolutionAlternativeEnum(StrEnum):
    ADDITIONAL_CONDITIONS = "AdditionalConditions"
    NO_ALTERNATIVE = "NoAlternative"
    SPLIT_DIFFERENCE = "SplitDifference"
