# generated by datamodel-codegen:
#   filename:  cdm-event-common-BillingSummaryInstruction.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_RecordAmountTypeEnum_schema


class BillingSummaryInstruction(BaseModel):
    summary_amount_type: cdm_event_common_RecordAmountTypeEnum_schema.RecordAmountTypeEnum = Field(
        ..., alias="summaryAmountType", description="The account level for the billing summary."
    )
