# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-EquitySwapMasterConfirmation2018.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_observable_asset_InterpolationMethodEnum_schema,
    cdm_observable_asset_ValuationDates_schema,
    cdm_product_asset_PriceReturnTerms_schema,
    cdm_product_asset_ReturnTypeEnum_schema,
    cdm_product_common_schedule_PaymentDates_schema,
    cdm_product_common_settlement_SettlementTerms_schema,
)


class EquitySwapMasterConfirmation2018(BaseModel):
    type_of_swap_election: cdm_product_asset_ReturnTypeEnum_schema.ReturnTypeEnum = Field(
        ...,
        alias="typeOfSwapElection",
        description="Per Part 1 Section 4, 'Dividend Obligations', of the 2018 ISDA CDM Equity Confirmation, Para 4.2 'Dividend Returns'.",
    )
    pricing_method_election: cdm_product_asset_PriceReturnTerms_schema.PriceReturnTerms = Field(
        ...,
        alias="pricingMethodElection",
        description="Per Part 1 Section 5, 'Pricing', of the 2018 ISDA CDM Equity Confirmation, Para 5.1.",
    )
    linear_interpolation_election: cdm_observable_asset_InterpolationMethodEnum_schema.InterpolationMethodEnum = Field(
        ...,
        alias="linearInterpolationElection",
        description="Per Part 1 Section 3, 'Floating Obligations', of the 2018 ISDA CDM Equity Confirmation. Para 3.3.",
    )
    settlement_terms: cdm_product_common_settlement_SettlementTerms_schema.SettlementTerms = Field(
        ...,
        alias="settlementTerms",
        description="Per Part 1 Section 8, 'Settlement', of the 2018 ISDA CDM Equity Confirmation for Security Equity Swap.",
    )
    valuation_dates: cdm_observable_asset_ValuationDates_schema.ValuationDates = Field(
        ...,
        alias="valuationDates",
        description="The parameters used to generate the 'Equity Valuation Dates' schedule, including the Effective Date and Termination Date for the Swap.",
    )
    equity_cash_settlement_dates: cdm_product_common_schedule_PaymentDates_schema.PaymentDates = Field(
        ...,
        alias="equityCashSettlementDates",
        description="The parameters used to generate the payment date schedule, relative to the equityCalculationPeriod. Per Part 1 Section 12, 'Definitions', of the 2018 ISDA CDM Equity Confirmation. Para 73.",
    )
