# generated by datamodel-codegen:
#   filename:  cdm-observable-event-ShareExtraordinaryEventEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class ShareExtraordinaryEventEnum(StrEnum):
    ALTERNATIVE_OBLIGATION = "AlternativeObligation"
    CALCULATION_AGENT = "CalculationAgent"
    CANCELLATION_AND_PAYMENT = "CancellationAndPayment"
    COMPONENT = "Component"
    MODIFIED_CALCULATION_AGENT = "ModifiedCalculationAgent"
    OPTIONS_EXCHANGE = "OptionsExchange"
    PARTIAL_CANCELLATION_AND_PAYMENT = "PartialCancellationAndPayment"
