# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-RegulatoryRegimeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class RegulatoryRegimeEnum(StrEnum):
    australia = "Australia"
    brazil = "Brazil"
    cftc = "CFTC"
    canada = "Canada"
    emir = "EMIR"
    hong_kong = "Hong Kong"
    hong_kong_sfc = "Hong Kong SFC"
    japan = "Japan"
    sec = "SEC"
    singapore = "Singapore"
    south_africa = "South Africa"
    south_korea = "South Korea"
    switzerland = "Switzerland"
    prudential = "Prudential"
    united_kingdom = "United Kingdom"
