# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-FxSpotRateSource.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_observable_asset_InformationSource_schema


class FxSpotRateSource(BaseModel):
    primary_source: cdm_observable_asset_InformationSource_schema.InformationSource = Field(
        ...,
        alias="primarySource",
        description="The primary source for where the rate observation will occur. Will typically be either a page or a reference bank published rate.",
    )
    secondary_source: cdm_observable_asset_InformationSource_schema.InformationSource | None = Field(
        None,
        alias="secondarySource",
        description="An alternative, or secondary, source for where the rate observation will occur. Will typically be either a page or a reference bank published rate.",
    )
