# generated by datamodel-codegen:
#   filename:  cdm-product-asset-DividendAmountTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class DividendAmountTypeEnum(StrEnum):
    as_specified_in_master_confirmation = "AsSpecifiedInMasterConfirmation"
    ex_amount = "ExAmount"
    paid_amount = "PaidAmount"
    record_amount = "RecordAmount"
