# generated by datamodel-codegen:
#   filename:  cdm-product-asset-VarianceCapFloor.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_asset_BoundedVariance_schema


class VarianceCapFloor(BaseModel):
    variance_cap: bool = Field(
        ...,
        alias="varianceCap",
        description="If present and true, then variance cap is applicable.",
    )
    unadjusted_variance_cap: float | None = Field(
        None,
        alias="unadjustedVarianceCap",
        description="For use when varianceCap is applicable. Contains the scaling factor of the Variance Cap that can differ on a trade-by-trade basis in the European market. For example, a Variance Cap of 2.5^2 x Variance Strike Price has an unadjustedVarianceCap of 2.5.",
    )
    bounded_variance: cdm_product_asset_BoundedVariance_schema.BoundedVariance | None = Field(
        None,
        alias="boundedVariance",
        description="Conditions which bound variance. The contract specifies one or more boundary levels. These levels are expressed as prices for confirmation purposes Underlyer price must be equal to or higher than Lower Barrier is known as Up Conditional Swap Underlyer price must be equal to or lower than Upper Barrier is known as Down Conditional Swap Underlyer price must be equal to or higher than Lower Barrier and must be equal to or lower than Upper Barrier is known as Barrier Conditional Swap.",
    )
