# generated by datamodel-codegen:
#   filename:  cdm-event-common-ExecutionTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ExecutionTypeEnum(StrEnum):
    electronic = "Electronic"
    off_facility = "OffFacility"
    on_venue = "OnVenue"
