# generated by datamodel-codegen:
#   filename:  cdm-event-common-CallTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class CallTypeEnum(StrEnum):
    expected_call = "ExpectedCall"
    margin_call = "MarginCall"
    notification = "Notification"
