# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-PriceExpressionEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class PriceExpressionEnum(StrEnum):
    ABSOLUTE_TERMS = "AbsoluteTerms"
    PAR_VALUE_FRACTION = "ParValueFraction"
    PER_OPTION = "PerOption"
    PERCENTAGE_OF_NOTIONAL = "PercentageOfNotional"
