# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-AdditionalTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AdditionalTypeEnum(StrEnum):
    EQUITY_OPTION_OR_INDEX_OPTION = "EquityOptionOrIndexOption"
    NOT_APPLICABLE = "NotApplicable"
    OTHER = "Other"
