# generated by datamodel-codegen:
#   filename:  cdm-product-asset-CorrelationReturnTerms.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_math_NumberRange_schema,
    cdm_observable_asset_DividendApplicability_schema,
    cdm_observable_asset_Price_schema,
    cdm_observable_common_DeterminationMethodEnum_schema,
    cdm_product_asset_EquityUnderlierProvisions_schema,
    cdm_product_asset_ValuationTerms_schema,
)


class CorrelationReturnTerms(BaseModel):
    valuation_terms: cdm_product_asset_ValuationTerms_schema.ValuationTerms | None = Field(
        None, alias="valuationTerms", description="Contains all non-date valuation information."
    )
    annualization_factor: int | None = Field(
        None,
        alias="annualizationFactor",
        description="This specifies the numerator of an annualization factor. Frequently this number is equal to the number of observations of prices in a year e.g. 252.",
    )
    dividend_applicability: cdm_observable_asset_DividendApplicability_schema.DividendApplicability | None = Field(
        None, alias="dividendApplicability", description="The parameters which define whether dividends are applicable"
    )
    equity_underlier_provisions: cdm_product_asset_EquityUnderlierProvisions_schema.EquityUnderlierProvisions | None = (
        Field(
            None,
            alias="equityUnderlierProvisions",
            description="Contains Equity Underlyer provisions regarding jurisdiction and fallbacks.",
        )
    )
    share_price_dividend_adjustment: bool | None = Field(
        None,
        alias="sharePriceDividendAdjustment",
        description="Indicates whether the price of shares is adjusted for dividends or not.",
    )
    expected_n: int | None = Field(None, alias="expectedN", description="Expected number of trading days.")
    initial_level: float | None = Field(
        None,
        alias="initialLevel",
        description="Contract will strike off this initial level. Providing just the initialLevel without initialLevelSource, infers that this is AgreedInitialPrice - a specified Initial Index Level.",
    )
    initial_level_source: cdm_observable_common_DeterminationMethodEnum_schema.DeterminationMethodEnum | None = Field(
        None,
        alias="initialLevelSource",
        description="In this context, this is AgreedInitialPrice - a specified Initial Index Level.",
    )
    mean_adjustment: bool | None = Field(
        None,
        alias="meanAdjustment",
        description="Specifies whether Mean Adjustment is applicable or not in the calculation of the Realized Volatility, Variance or Correlation",
    )
    performance: str | None = Field(
        None,
        description="Performance calculation, in accordance with Part 1 Section 12 of the 2018 ISDA CDM Equity Confirmation for Security Equity Swap, Para 75. 'Equity Performance'. Cumulative performance is used as a notional multiplier factor on both legs of an Equity Swap.",
    )
    correlation_strike_price: cdm_observable_asset_Price_schema.Price = Field(
        ...,
        alias="correlationStrikePrice",
        description="Correlation Strike Price in accordance with the ISDA 2011 Equity Derivatives Definitions.",
    )
    bounded_correlation: cdm_base_math_NumberRange_schema.NumberRange | None = Field(
        None,
        alias="boundedCorrelation",
        description="Describes correlation bounds, which form a cap and a floor on the realized correlation.",
    )
    number_of_data_series: int | None = Field(
        None,
        alias="numberOfDataSeries",
        description="Number of data series, normal market practice is that correlation data sets are drawn from geographic market areas, such as America, Europe and Asia Pacific, each of these geographic areas will have its own data series to avoid contagion.",
    )
