# generated by datamodel-codegen:
#   filename:  cdm-base-staticdata-asset-common-DebtType.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_asset_common_DebtClassEnum_schema,
    cdm_base_staticdata_asset_common_DebtEconomics_schema,
)


class DebtType(BaseModel):
    debt_class: cdm_base_staticdata_asset_common_DebtClassEnum_schema.DebtClassEnum | None = Field(
        None, alias="debtClass", description="Specifies the characteristics of a debt instrument."
    )
    debt_economics: list[cdm_base_staticdata_asset_common_DebtEconomics_schema.DebtEconomics] | None = Field(
        None,
        alias="debtEconomics",
        description="Specifies selected financial terms of a debt instrument.",
        min_length=0,
    )
