# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-EligibleCollateralSpecification.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_staticdata_identifier_Identifier_schema,
    cdm_base_staticdata_party_Counterparty_schema,
    cdm_base_staticdata_party_PartyRole_schema,
    cdm_base_staticdata_party_Party_schema,
    cdm_product_collateral_EligibleCollateralCriteria_schema,
)


class EligibleCollateralSpecification(BaseModel):
    identifier: list[cdm_base_staticdata_identifier_Identifier_schema.Identifier] | None = Field(
        None,
        description="Specifies the identifier(s) to uniquely identify eligible collateral or a set of eligible collateral, such as a schedule or equivalant for an identity issuer.",
        min_length=0,
    )
    party: list[cdm_base_staticdata_party_Party_schema.Party] | None = Field(
        None,
        description="The parties associated with the specification.",
        max_length=2,
        min_length=0,
    )
    counterparty: list[cdm_base_staticdata_party_Counterparty_schema.Counterparty] | None = Field(
        None,
        description="Specification of the roles of the counterparties to the specification.",
        max_length=2,
        min_length=0,
    )
    criteria: (
        list[cdm_product_collateral_EligibleCollateralCriteria_schema.EligibleCollateralCriteria]
        | None
    ) = Field(
        None,
        description="Represents a set of criteria used to specify eligible collateral.",
        min_length=1,
    )
    party_role: list[cdm_base_staticdata_party_PartyRole_schema.PartyRole] | None = Field(
        None,
        alias="partyRole",
        description="Specifies the role(s) that each of the party(s) is playing in the context of the specification, eg Payor or Receiver.",
        min_length=0,
    )
