# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-Custodian.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_legaldocumentation_csa_CustodianElection_schema


class Custodian(BaseModel):
    party_election: list[cdm_legaldocumentation_csa_CustodianElection_schema.CustodianElection] | None = Field(
        None, alias="partyElection", description="The party specific elections.", max_length=2, min_length=2
    )
