# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-PeriodTimeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class PeriodTimeEnum(StrEnum):
    HOUR = "Hour"
    MINUTE = "Minute"
    SECOND = "Second"
