# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-ScheduledTransferEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ScheduledTransferEnum(StrEnum):
    corporate_action = "CorporateAction"
    coupon = "Coupon"
    credit_event = "CreditEvent"
    dividend_return = "DividendReturn"
    exercise = "Exercise"
    fixed_rate_return = "FixedRateReturn"
    floating_rate_return = "FloatingRateReturn"
    fractional_amount = "FractionalAmount"
    interest_return = "InterestReturn"
    net_interest = "NetInterest"
    performance = "Performance"
    principal_payment = "PrincipalPayment"
