# generated by datamodel-codegen:
#   filename:  cdm-product-asset-SettledEntityMatrixSourceEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class SettledEntityMatrixSourceEnum(StrEnum):
    confirmation_annex = "ConfirmationAnnex"
    not_applicable = "NotApplicable"
    publisher = "Publisher"
