# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyTransferSettlementTiming.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_legaldocumentation_csa_CashCTSTimeEnum_schema,
    cdm_legaldocumentation_csa_SecuritiesCTSTimeEnum_schema,
)


class LegacyTransferSettlementTiming(BaseModel):
    cash_collateral_transfer_settlement_time: (
        cdm_legaldocumentation_csa_CashCTSTimeEnum_schema.CashCTSTimeEnum | None
    ) = Field(
        None,
        alias="cashCollateralTransferSettlementTime",
        description="Details the day on which collateral is required to be transferred relative to the Notification Time.",
    )
    securitites_collateral_transfer_settlement_time: (
        cdm_legaldocumentation_csa_SecuritiesCTSTimeEnum_schema.SecuritiesCTSTimeEnum | None
    ) = Field(
        None,
        alias="securititesCollateralTransferSettlementTime",
        description="Details the day on which collateral is required to be transferred relative to the Notification Time.",
    )
    additional_language: str | None = Field(
        None,
        alias="additionalLanguage",
        description="The additional language that might be specified by the parties to the legal agreement.",
    )
