# generated by datamodel-codegen:
#   filename:  cdm-observable-event-MarketDisruptionEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class MarketDisruptionEnum(StrEnum):
    modified_postponement = "ModifiedPostponement"
    omission = "Omission"
    postponement = "Postponement"
