# generated by datamodel-codegen:
#   filename:  cdm-product-asset-metafields-FieldWithMetaSpreadScheduleTypeEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import cdm_product_asset_SpreadScheduleTypeEnum_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaSpreadScheduleTypeEnum(BaseModel):
    value: cdm_product_asset_SpreadScheduleTypeEnum_schema.SpreadScheduleTypeEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
