# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-metafields-FieldWithMetaInformationProviderEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import (
    cdm_observable_asset_InformationProviderEnum_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class FieldWithMetaInformationProviderEnum(BaseModel):
    value: cdm_observable_asset_InformationProviderEnum_schema.InformationProviderEnum | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
