# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-metafields-FieldWithMetaPriceSchedule.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel
from . import (
    cdm_observable_asset_PriceSchedule_schema,
    com_rosetta_model_metafields_MetaFields_schema,
)


class FieldWithMetaPriceSchedule(BaseModel):
    value: cdm_observable_asset_PriceSchedule_schema.PriceSchedule | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
