# generated by datamodel-codegen:
#   filename:  cdm-product-asset-AssetDeliveryPeriods.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_asset_AssetDeliveryProfile_schema


class AssetDeliveryPeriods(BaseModel):
    profile: list[cdm_product_asset_AssetDeliveryProfile_schema.AssetDeliveryProfile] | None = Field(
        None,
        description="Defines the delivery profile of the asset, including the load type and the delivery intervals.",
        min_length=0,
    )
    start_date: str | None = Field(None, alias="startDate", description="Delivery start date")
    end_date: str | None = Field(None, alias="endDate", description="Delivery end date")
