# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-DividendApplicability.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field


class DividendApplicability(BaseModel):
    options_exchange_dividends: bool | None = Field(
        None, alias="optionsExchangeDividends", description="If present and true, then options exchange dividends are applicable."
    )
    additional_dividends: bool | None = Field(
        None, alias="additionalDividends", description="If present and true, then additional dividends are applicable."
    )
    all_dividends: bool | None = Field(
        None,
        alias="allDividends",
        description="Represents the European Master Confirmation value of 'All Dividends' which, when applicable, signifies that, for a given Ex-Date, the daily observed Share Price for that day is adjusted (reduced) by the cash dividend and/or the cash value of any non cash dividend per Share (including Extraordinary Dividends) declared by the Issuer. All Dividends in accordance with the ISDA 2002 Equity Derivatives Definitions.",
    )
