# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-AverageTradingVolumeMethodologyEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AverageTradingVolumeMethodologyEnum(StrEnum):
    CONSOLIDATED = "Consolidated"
    SINGLE = "Single"
