# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-common-SpecifiedEntityClauseEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class SpecifiedEntityClauseEnum(StrEnum):
    bankruptcy = "Bankruptcy"
    credit_event_upon_merger = "CreditEventUponMerger"
    cross_default = "CrossDefault"
    default_under_specified_transaction = "DefaultUnderSpecifiedTransaction"
