# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-CollateralTreatment.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_product_collateral_CollateralValuationTreatment_schema,
    cdm_product_collateral_ConcentrationLimit_schema,
)


class CollateralTreatment(BaseModel):
    valuation_treatment: (
        cdm_product_collateral_CollateralValuationTreatment_schema.CollateralValuationTreatment | None
    ) = Field(
        None,
        alias="valuationTreatment",
        description="Specification of the valuation treatment for the specified collateral.",
    )
    concentration_limit: list[cdm_product_collateral_ConcentrationLimit_schema.ConcentrationLimit] | None = Field(
        None,
        alias="concentrationLimit",
        description="Specification of concentration limits applicable to the collateral criteria.",
        min_length=0,
    )
    is_included: bool = Field(
        ...,
        alias="isIncluded",
        description="A boolean attribute to specify whether collateral critieria are inclusion (True) or exclusion (False) criteria.",
    )
