# generated by datamodel-codegen:
#   filename:  cdm-event-workflow-WorkflowStepApproval.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_base_staticdata_party_metafields_ReferenceWithMetaParty_schema, cdm_event_workflow_EventTimestamp_schema


class WorkflowStepApproval(BaseModel):
    approved: bool = Field(..., description="Flag denoting whether the workflow step is approved or not")
    party: cdm_base_staticdata_party_metafields_ReferenceWithMetaParty_schema.ReferenceWithMetaParty = Field(
        ..., description="Reference to the Party who is approving/rejecting this workflow step"
    )
    rejected_reason: str | None = Field(None, alias="rejectedReason", description="Optional reason for rejecting the workflow step")
    timestamp: cdm_event_workflow_EventTimestamp_schema.EventTimestamp = Field(..., description="Timestamp of the approval")
