# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-SpecifiedValueEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class SpecifiedValueEnum(StrEnum):
    FACE_VALUE = "FaceValue"
    MARKET_VALUE = "MarketValue"
    OUTSTANDING_PRINCIPAL_BALANCE = "OutstandingPrincipalBalance"
    STATED_PRINCIPAL_BALANCE = "StatedPrincipalBalance"
