# generated by datamodel-codegen:
#   filename:  cdm-base-math-QuantitySchedule.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_datetime_Frequency_schema,
    cdm_base_math_DatedValue_schema,
    cdm_base_math_Measure_schema,
    cdm_base_math_UnitType_schema,
)


class QuantitySchedule(BaseModel):
    value: float | None = Field(
        None,
        description="Specifies the value of the measure as a number. Optional because in a measure vector or schedule, this single value may be omitted.",
    )
    unit: cdm_base_math_UnitType_schema.UnitType | None = Field(
        None,
        description="Qualifies the unit by which the amount is measured. Optional because a measure may be unit-less (e.g. when representing a ratio between amounts in the same unit).",
    )
    dated_value: list[cdm_base_math_DatedValue_schema.DatedValue] | None = Field(
        None,
        alias="datedValue",
        description="A schedule of step date and value pairs. On each step date the associated step value becomes effective. The step dates are used to order the steps by ascending order. This attribute is optional so the data type may be used to define a schedule with a single value.",
        min_length=0,
    )
    multiplier: cdm_base_math_Measure_schema.Measure | None = Field(
        None,
        description="Defines an optional number that the quantity should be multiplied by to derive a total quantity. This number is associated to a unit. For example in the case of the Coal (API2) CIF ARA (ARGUS-McCloskey) Futures Contract on the CME, where the unit would be contracts, the multiplier value would 1,000 and the mulitiplier unit would be 1,000 MT (Metric Tons).",
    )
    frequency: cdm_base_datetime_Frequency_schema.Frequency | None = Field(
        None,
        description="Defines the frequency to be used when defining a quantity. For example a quantity may be specified as a number of barrels of oil per day, which needs multiplying by the number of days in the relevant period to get the total quantity as a number of barrels.",
    )
