# generated by datamodel-codegen:
#   filename:  cdm-product-collateral-AlternativeToInterestAmountEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class AlternativeToInterestAmountEnum(StrEnum):
    ACTUAL_AMOUNT_RECEIVED = "ActualAmountReceived"
    OTHER = "Other"
    STANDARD = "Standard"
    TRANSFER_IF_DELIVERY_AMOUNT_BELOW_MTA = "TransferIfDeliveryAmountBelowMTA"
