# generated by datamodel-codegen:
#   filename:  cdm-event-common-MarginCallResponseTypeEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class MarginCallResponseTypeEnum(StrEnum):
    agreein_full = "AgreeinFull"
    dispute = "Dispute"
    partially_agree = "PartiallyAgree"
