# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-Frequency.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_base_datetime_PeriodExtendedEnum_schema


class Frequency(BaseModel):
    period_multiplier: int = Field(
        ...,
        alias="periodMultiplier",
        description="A time period multiplier, e.g. 1, 2, or 3. If the period value is T (Term) then period multiplier must contain the value 1.",
    )
    period: cdm_base_datetime_PeriodExtendedEnum_schema.PeriodExtendedEnum = Field(
        ..., description="A time period, e.g. a day, week, month, year or term of the stream."
    )
