# generated by datamodel-codegen:
#   filename:  cdm-product-common-settlement-SettlementProvision.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import cdm_product_common_settlement_ShapingProvision_schema


class SettlementProvision(BaseModel):
    shaping_provisions: cdm_product_common_settlement_ShapingProvision_schema.ShapingProvision | None = Field(
        None,
        alias="shapingProvisions",
        description="Defines the parameters that are necessary to 'shape' a settlement, i.e. break it down into smaller amounts.",
    )
