# generated by datamodel-codegen:
#   filename:  cdm-product-asset-FixedRateSpecification.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_product_common_schedule_RateSchedule_schema


class FixedRateSpecification(BaseModel):
    rate_schedule: cdm_product_common_schedule_RateSchedule_schema.RateSchedule | None = Field(
        None,
        alias="rateSchedule",
        description="The fixed rate or fixed rate schedule expressed as explicit fixed rates and dates. In the case of a schedule, the step dates may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments.",
    )
