# generated by datamodel-codegen:
#   filename:  cdm-observable-asset-metafields-FieldWithMetaObservable.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel
from . import cdm_observable_asset_Observable_schema, com_rosetta_model_metafields_MetaFields_schema


class FieldWithMetaObservable(BaseModel):
    value: cdm_observable_asset_Observable_schema.Observable | None = None
    meta: com_rosetta_model_metafields_MetaFields_schema.MetaFields | None = None
