# generated by datamodel-codegen:
#   filename:  cdm-product-asset-AssetDeliveryInformation.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import (
    cdm_base_math_Quantity_schema,
    cdm_base_staticdata_asset_commodity_ProductGradeEnum_schema,
    cdm_base_staticdata_identifier_LocationIdentifier_schema,
    cdm_product_asset_AssetDeliveryPeriods_schema,
)


class AssetDeliveryInformation(BaseModel):
    periods: cdm_product_asset_AssetDeliveryPeriods_schema.AssetDeliveryPeriods | None = Field(
        None, description="Defines the periods of delivery, including the delivery profile."
    )
    location: list[cdm_base_staticdata_identifier_LocationIdentifier_schema.LocationIdentifier] | None = Field(
        None, description="Defines the location of the delivery of the commodity.", min_length=0
    )
    delivery_capacity: cdm_base_math_Quantity_schema.Quantity | None = Field(
        None,
        alias="deliveryCapacity",
        description="The number of units included in the transaction for each delivery interval",
    )
    commodity_grade: list[cdm_base_staticdata_asset_commodity_ProductGradeEnum_schema.ProductGradeEnum] | None = Field(
        None, alias="commodityGrade", description="Grade of product being delivered (e.g., grade of oil).", min_length=0
    )
