# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-ValuationAgentPartyEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class ValuationAgentPartyEnum(StrEnum):
    party_1 = "Party 1"
    party_2 = "Party 2"
    party_making_the_demand = "Party Making the Demand"
