# generated by datamodel-codegen:
#   filename:  cdm-base-math-DatedValue.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field


class DatedValue(BaseModel):
    date: str = Field(
        ...,
        description="The date on which the associated step value becomes effective. This day may be subject to adjustment in accordance with a business day convention.",
    )
    value: float = Field(
        ...,
        description="The rate of amount which becomes effective on the associated step date. A rate of 5% would be represented as 0.05.",
    )
