# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-transaction-additionalterms-SpecifiedValueEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class SpecifiedValueEnum(StrEnum):
    face_value = "FaceValue"
    market_value = "MarketValue"
    outstanding_principal_balance = "OutstandingPrincipalBalance"
    stated_principal_balance = "StatedPrincipalBalance"
