# generated by datamodel-codegen:
#   filename:  cdm-base-datetime-PeriodEnum.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from enum import StrEnum


class PeriodEnum(StrEnum):
    D = "D"
    M = "M"
    W = "W"
    Y = "Y"
