# generated by datamodel-codegen:
#   filename:  cdm-legaldocumentation-csa-LegacyValuationAgentEnum.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from enum import StrEnum


class LegacyValuationAgentEnum(StrEnum):
    fixed_party_for_disputes = "FixedPartyForDisputes"
    sole_valuation_agent = "SoleValuationAgent"
    switch_upon_default = "SwitchUponDefault"
    switch_upon_failure_to_perform = "SwitchUponFailureToPerform"
