# generated by datamodel-codegen:
#   filename:  cdm-event-common-IndexTransitionInstruction.schema.json
#   timestamp: 2026-05-07T14:39:41+00:00

from pydantic import BaseModel, Field
from . import cdm_event_common_Transfer_schema, cdm_observable_asset_PriceQuantity_schema


class IndexTransitionInstruction(BaseModel):
    price_quantity: list[cdm_observable_asset_PriceQuantity_schema.PriceQuantity] | None = Field(
        None,
        alias="priceQuantity",
        description="Specifies both new floating rate index and spread adjustment for each leg to be updated.  The spread adjustment accounts for the difference between the old floating rate index relative to the new one. This spread amount is added to the existing spread to determine the new spread, which is applied from the specified effective date forward. In the case of the IBOR Fallback Rate Adjustments, the adjustment spread (also known as the Fallback Adjustment) accounts for two distinctions: i) the fact that the replacement Risk-Free Rate is an overnight rate while IBORs have term structures (e.g., 1, 3, 6-month LIBOR); and (ii) the historical spread differential between IBORs and their term equivalent Overnight Risk-Free Rate compounded rates.",
        min_length=1,
    )
    effective_date: str = Field(
        ...,
        alias="effectiveDate",
        description="Specifies the effective date of the index transition event. This is first date on which the floating rate calculation will use the new floating rate index and adjusted spread in the floating rate calculation.",
    )
    cash_transfer: cdm_event_common_Transfer_schema.Transfer | None = Field(
        None, alias="cashTransfer", description="Specifies the cash transfer that can optionally be tied to an index transition event."
    )
