# generated by datamodel-codegen:
#   filename:  com-rosetta-model-metafields-MetaFields.schema.json
#   timestamp: 2026-05-07T23:23:14+00:00

from pydantic import BaseModel, Field
from . import com_rosetta_model_lib_meta_Key_schema


class MetaFields(BaseModel):
    scheme: str | None = None
    global_key: str | None = Field(None, alias="globalKey")
    external_key: str | None = Field(None, alias="externalKey")
    key: list[com_rosetta_model_lib_meta_Key_schema.Key] | None = Field(None, min_length=0)
